-- 012_seed_poolpal_reference.sql
-- 18 verified starter entries for the PoolPal reference database.

insert into poolpal.pool_reference (category, title, equipment_type, pool_type, specification, content_json, source) values

-- Chemical Dosing
('chemical_dosing', 'Chlorine dosing by CYA level', null, 'chlorine', 'APSP/ICC',
 '{"summary": "Free chlorine (FC) must be maintained relative to cyanuric acid (CYA) level. The higher your CYA, the more FC you need. Target FC = 7.5% of CYA for daily maintenance. For algae treatment (SLAM), target FC = 40% of CYA.","key_values":[{"label":"CYA 30 ppm","value":"FC target 2-4 ppm, SLAM 12 ppm"},{"label":"CYA 50 ppm","value":"FC target 4-6 ppm, SLAM 20 ppm"},{"label":"CYA 70 ppm","value":"FC target 5-8 ppm, SLAM 28 ppm"},{"label":"CYA 100 ppm","value":"FC target 8-12 ppm, SLAM 40 ppm"}],"important_notes":["If CYA exceeds 80-100 ppm, chlorine becomes increasingly ineffective — partial drain and refill is the only fix","Liquid chlorine (sodium hypochlorite 12.5%) does NOT add CYA; trichlor and dichlor DO add CYA","Test CYA with a dilution test if reading above 100 ppm — standard tests max out"]}'::jsonb,
 'verified'),

('chemical_dosing', 'pH adjustment with muriatic acid', null, null, null,
 '{"summary": "Muriatic acid (31.45% HCl) lowers pH and total alkalinity. Always add acid to water, never water to acid. Pour slowly around the perimeter with the pump running.","key_values":[{"label":"10,000 gal pool, pH 7.8→7.4","value":"~12 oz (3/4 cup)"},{"label":"10,000 gal pool, pH 8.0→7.4","value":"~20 oz (1.25 cups)"},{"label":"10,000 gal pool, pH 8.2→7.4","value":"~28 oz (1.75 cups)"},{"label":"Effect on TA","value":"~10 ppm TA reduction per 12 oz / 10K gal"}],"important_notes":["Always wear chemical-resistant gloves and safety glasses","Never pour acid directly into the skimmer","Wait 30 minutes, retest, and adjust — do not over-correct in one dose","Acid demand varies by TA level — high TA pools resist pH change"]}'::jsonb,
 'verified'),

('chemical_dosing', 'pH raise with soda ash (sodium carbonate)', null, null, null,
 '{"summary": "Sodium carbonate (soda ash) raises pH with minimal effect on total alkalinity. Preferred over borax when you need pH up without raising TA significantly.","key_values":[{"label":"10,000 gal pool, pH 7.0→7.4","value":"~6 oz"},{"label":"10,000 gal pool, pH 7.2→7.4","value":"~3 oz"},{"label":"Effect on TA","value":"Slight increase (~5 ppm per 6 oz / 10K gal)"}],"important_notes":["Pre-dissolve in a bucket of pool water before adding","Add with pump running, pour near a return jet","Retest after 1 hour — pH can drift back if TA is low"]}'::jsonb,
 'verified'),

('chemical_dosing', 'Total alkalinity adjustment with sodium bicarbonate', null, null, null,
 '{"summary": "Sodium bicarbonate (baking soda) raises total alkalinity (TA) with a slight pH increase. TA acts as a pH buffer — low TA causes pH bounce.","key_values":[{"label":"10,000 gal pool, raise TA 10 ppm","value":"~1.5 lbs"},{"label":"Target TA range","value":"80-120 ppm (plaster), 80-100 ppm (vinyl/fiberglass)"},{"label":"Maximum per dose","value":"2 lbs per 10,000 gal — wait 6 hours between doses"}],"important_notes":["Broadcast dry over the surface with pump running","High TA (above 120) makes pH difficult to control — lower TA first with acid if needed","LSI calculation should guide TA target for plaster pools"]}'::jsonb,
 'verified'),

('chemical_dosing', 'Calcium hardness adjustment', null, null, null,
 '{"summary": "Calcium chloride (CaCl2) raises calcium hardness (CH). Proper CH protects plaster from etching and prevents scaling. There is no chemical to lower CH — only dilution (drain and refill).","key_values":[{"label":"10,000 gal pool, raise CH 10 ppm","value":"~1.25 lbs calcium chloride (77-80%)"},{"label":"Target CH range (plaster)","value":"250-350 ppm"},{"label":"Target CH range (vinyl/fiberglass)","value":"150-250 ppm"},{"label":"Target CH range (salt pool)","value":"200-400 ppm"}],"important_notes":["Pre-dissolve in a bucket — generates significant heat, add slowly","Never add CaCl2 through the skimmer","High CH + high pH + high TA = scale formation — check LSI","Salt pools generate calcium scale on the cell — monitor CH closely"]}'::jsonb,
 'verified'),

('chemical_dosing', 'CYA (stabilizer) addition rates', null, 'chlorine', null,
 '{"summary": "Cyanuric acid (CYA / stabilizer / conditioner) protects chlorine from UV degradation. Too little = chlorine burns off in hours. Too much = chlorine becomes ineffective. Dissolve in a sock hung in the skimmer basket or in front of a return jet.","key_values":[{"label":"10,000 gal pool, raise CYA 10 ppm","value":"~13 oz (dry granular)"},{"label":"Target CYA (residential)","value":"30-50 ppm"},{"label":"Target CYA (commercial)","value":"Per local health code (often 30-100 max)"},{"label":"Salt pools","value":"60-80 ppm recommended"}],"important_notes":["CYA does NOT degrade or evaporate — it only leaves through splash-out, backwash, or drain","If CYA is over 80-100 ppm, partial drain is the only fix","Trichlor tabs add ~6 ppm CYA per 1 ppm FC — this is how CYA creeps up over time","Takes 3-7 days to fully dissolve and register on test"]}'::jsonb,
 'verified'),

-- Equipment
('equipment_spec', 'Variable speed pump sizing guide', 'pump', null, 'DOE Title 20',
 '{"summary": "Variable speed pumps (VSPs) are required by DOE regulation for new pool construction and pump replacements over 1 HP. They reduce energy costs 60-80% vs single-speed by running at lower RPM for longer periods.","key_values":[{"label":"Pool up to 15,000 gal","value":"1.0-1.5 HP VSP (e.g., Pentair IntelliFlo VSF, Hayward Super Pump VS)"},{"label":"Pool 15,000-30,000 gal","value":"1.5-2.0 HP VSP (e.g., Pentair IntelliFlo 3, Hayward TriStar VS)"},{"label":"Pool over 30,000 gal","value":"2.0-3.0 HP VSP (e.g., Pentair IntelliFlo VSF 3HP, Jandy FloPro 2.7 VS)"},{"label":"Turnover target","value":"All water through filter once per 8-12 hours"},{"label":"Min flow for heater","value":"Typically 25-40 GPM — check heater spec"}],"important_notes":["Size by pipe diameter: 1.5 inch pipe maxes at ~45 GPM, 2 inch at ~75 GPM","Run at lowest RPM that maintains adequate filtration and skimming","Program low RPM for filtration, medium for heating, high for spa jets or vacuuming","Salt cells need minimum 2500-3000 RPM to generate chlorine"]}'::jsonb,
 'verified'),

('equipment_spec', 'Salt chlorine generator (SWG) cell maintenance', 'salt_cell', 'salt', null,
 '{"summary": "Salt cells convert dissolved salt (NaCl) to chlorine. Calcium scale buildup on the cell plates reduces output and shortens lifespan. Inspect every 500 hours or 3 months. Typical cell life: 3-5 years or 10,000 hours.","key_values":[{"label":"Ideal salt level","value":"2700-3400 ppm (varies by manufacturer)"},{"label":"Cell cleaning acid mix","value":"4:1 water to muriatic acid"},{"label":"Soak time","value":"5-15 minutes until bubbling stops"},{"label":"Replace when","value":"Output drops below 50% at max setting, or visible plate erosion"}],"important_notes":["Always add acid to water, never water to acid","Do not scrape or wire brush the plates — damages the coating","Most cells shut off below 60°F water temp — this is normal, not a failure","Low salt reading but salt level is correct = dirty cell or failing cell","Reverse-polarity cells self-clean but still need periodic manual acid wash"]}'::jsonb,
 'verified'),

('equipment_spec', 'DE filter maintenance and recharge', 'filter', null, null,
 '{"summary": "Diatomaceous earth (DE) filters provide the finest filtration (2-5 microns). They require periodic backwashing and annual grid inspection. DE powder must be recharged after every backwash.","key_values":[{"label":"Backwash when","value":"Pressure gauge reads 8-10 PSI above clean starting pressure"},{"label":"DE recharge amount","value":"1 lb DE per 10 sq ft of filter area (check label)"},{"label":"Annual teardown","value":"Remove grids, soak in TSP or filter cleaner, inspect for tears"},{"label":"Grid replacement","value":"Every 5-7 years or when fabric shows wear/holes"}],"important_notes":["Add DE through the skimmer with pump running — never dump directly into filter tank","Short-cycling the backwash does not fully purge spent DE — do a full 2-3 minute backwash","If DE returns to pool, a grid is torn — shut down and inspect immediately","Some jurisdictions prohibit DE discharge into storm drains — check local codes"]}'::jsonb,
 'verified'),

('equipment_spec', 'Heater BTU sizing', 'heater', null, null,
 '{"summary": "Pool heaters are sized by BTU/hour output. Proper sizing depends on pool volume, desired temperature rise, and heat loss from wind and evaporation. Undersized heaters run continuously and never reach setpoint.","key_values":[{"label":"10,000 gal pool, 20°F rise","value":"~200,000 BTU (10-12 hours heat-up)"},{"label":"15,000 gal pool, 20°F rise","value":"~300,000 BTU (10-12 hours heat-up)"},{"label":"20,000 gal pool, 20°F rise","value":"~400,000 BTU (10-12 hours heat-up)"},{"label":"Spa (500 gal), 30°F rise","value":"~125,000 BTU (~30 min heat-up)"}],"important_notes":["Rule of thumb: 1 BTU raises 1 lb of water 1°F; 10,000 gal = 83,400 lbs","Wind is the #1 heat loss factor — a solar cover reduces heating cost 50-70%","Gas heaters need adequate gas supply — check BTU capacity of gas meter and line","Heat pumps are 3-5x more efficient but heat slowly — best for maintaining temp, not rapid heat-up"]}'::jsonb,
 'verified'),

-- Code Requirements
('code_requirement', 'VGB Act / APSP-7 suction entrapment prevention', null, null, 'Virginia Graeme Baker Act (P&L 110-140)',
 '{"summary": "The VGB Act (2008) requires all public pools and spas to have compliant drain covers (ASME A112.19.8) and, in many cases, a secondary anti-entrapment system. Single-drain configurations require additional safety devices.","key_values":[{"label":"Drain cover standard","value":"ASME/ANSI A112.19.8-2020 compliant, replaced every service life (check label)"},{"label":"Single main drain","value":"Requires SVRS (safety vacuum release system) or equivalent"},{"label":"Dual main drains","value":"Must be spaced ≥3 feet apart or ≥3 feet from any wall"},{"label":"Applies to","value":"All public pools, spas, wading pools"}],"important_notes":["Drain covers have an expiration date stamped on them — check and replace","Residential pools are governed by state/local codes which may or may not adopt VGB","Unblockable drains (channel drains, T-shaped) do not require SVRS","Document all drain cover replacements with photos and dates for compliance records"]}'::jsonb,
 'verified'),

('code_requirement', 'Commercial pool free chlorine minimums', null, null, 'State health codes (varies)',
 '{"summary": "Commercial (public) pools must maintain minimum free chlorine levels per state health department regulations. Levels vary by jurisdiction but most require 1-3 ppm FC. Bromine pools typically require 3-5 ppm. CYA maximums also apply.","key_values":[{"label":"Typical FC minimum","value":"1.0 ppm (some states require 2.0)"},{"label":"Typical FC maximum","value":"5.0-10.0 ppm"},{"label":"CYA maximum (commercial)","value":"Often 40-100 ppm max (varies widely)"},{"label":"pH range required","value":"7.2-7.8 (most jurisdictions)"}],"important_notes":["Always check your specific state and county health code — there is no single national standard","Records of daily water testing are required — log FC, pH, and temperature at minimum","Superchlorination above 10 ppm requires pool closure until FC drops to safe levels","Some jurisdictions ban CYA entirely for commercial pools"]}'::jsonb,
 'verified'),

('code_requirement', 'Pool barrier fencing requirements', null, null, 'APSP-7 / IRC R326',
 '{"summary": "Pool barrier requirements are set by local building codes, typically adopting APSP-7 or IRC Section R326. Barriers must prevent unsupervised access by children under 5.","key_values":[{"label":"Minimum height","value":"48 inches (4 feet) from grade"},{"label":"Gate","value":"Self-closing and self-latching, opens outward from pool"},{"label":"Latch height","value":"54 inches from grade (or key-operated)"},{"label":"Maximum gap at bottom","value":"4 inches from grade to bottom of barrier"}],"important_notes":["Mesh fencing must meet ASTM F2286 for removable barriers","House wall can serve as one side of the barrier if all doors have alarms or self-closing devices","Inspect gates and latches annually — spring mechanisms wear out","Hot tub/spa covers with locking straps can serve as a barrier in some jurisdictions"]}'::jsonb,
 'verified'),

-- Algae Guides
('algae_guide', 'Green algae identification and SLAM treatment', null, null, null,
 '{"summary": "Green algae is the most common pool algae — free-floating, turns water green/cloudy. Caused by inadequate chlorine relative to CYA, poor circulation, or filter issues. Treated with SLAM (Shock Level And Maintain) method: raise FC to 40% of CYA and hold until clear.","key_values":[{"label":"SLAM FC target (CYA 30)","value":"12 ppm FC, maintain until clear + overnight test passes"},{"label":"SLAM FC target (CYA 50)","value":"20 ppm FC"},{"label":"SLAM FC target (CYA 70)","value":"28 ppm FC"},{"label":"Filter","value":"Run 24/7 during SLAM, clean filter every 12-24 hours"}],"important_notes":["Use liquid chlorine (sodium hypochlorite) for SLAM — do NOT use dichlor/trichlor (adds CYA)","Brush all surfaces thoroughly before and during treatment","Overnight FC loss test: if FC drops more than 1 ppm overnight, algae is still alive — keep going","Green water that does not respond to chlorine may be copper/metals — test metals before continuing SLAM"]}'::jsonb,
 'verified'),

('algae_guide', 'Black algae vs mustard algae identification', null, null, null,
 '{"summary": "Black algae appears as dark blue-green/black spots embedded in plaster, especially in shaded areas. Extremely resistant — has roots that penetrate plaster. Mustard (yellow) algae looks like sand or pollen clinging to shady walls, brushes off easily but returns within 24 hours.","key_values":[{"label":"Black algae treatment","value":"Aggressive brushing with stainless steel brush (plaster only), chlorine tabs held directly on spots, SLAM + algaecide"},{"label":"Mustard algae treatment","value":"SLAM + sodium bromide algaecide (Yellow Out, Yellow Treat), clean ALL items that touched the water"},{"label":"Black algae brush","value":"Stainless steel bristle (plaster) — NEVER on vinyl or fiberglass"},{"label":"Prevention","value":"Maintain proper FC/CYA ratio, good circulation, regular brushing"}],"important_notes":["Black algae on vinyl or fiberglass is extremely rare — if present, it is likely mold and requires different treatment","Mustard algae can hide on pool toys, floats, swimsuits, cleaning tools — sanitize everything","Black algae may require professional plaster repair if roots have caused deep damage","Neither responds to normal shock levels — SLAM is the minimum effective treatment"]}'::jsonb,
 'verified'),

-- Safety
('safety', 'Chemical storage and compatibility', null, null, 'OSHA / NFPA 400',
 '{"summary": "Pool chemicals must be stored properly to prevent fires, toxic gas release, and explosions. The #1 rule: NEVER mix chlorine products with acid. Chlorine + acid = chlorine gas (potentially fatal). Many pool chemical incidents happen during transport or storage, not application.","key_values":[{"label":"Chlorine + acid","value":"NEVER — produces chlorine gas (lethal)"},{"label":"Chlorine + chlorine (different types)","value":"NEVER mix trichlor with cal-hypo — fire/explosion risk"},{"label":"Storage separation","value":"Minimum 20 feet between oxidizers and acids"},{"label":"Storage environment","value":"Cool, dry, ventilated, away from sunlight"}],"important_notes":["Even residual acid in a measuring cup mixed with chlorine produces gas — use dedicated tools per chemical","Cal-hypo (calcium hypochlorite) is an oxidizer and can spontaneously combust if contaminated with organics","If chemical spill occurs, do NOT wash chlorine and acid spills toward each other","Transport chemicals in vehicle trunk or truck bed, never in passenger compartment, containers upright and secured"]}'::jsonb,
 'verified'),

-- Water Chemistry
('water_chemistry', 'Langelier Saturation Index (LSI) for plaster pools', null, null, null,
 '{"summary": "The LSI predicts whether pool water is corrosive (etches plaster) or scaling (deposits calcium). Balanced water has an LSI near 0. Plaster pools should target LSI between -0.3 and +0.3. All five factors interact: pH, temperature, calcium hardness, total alkalinity, and TDS.","key_values":[{"label":"LSI = 0","value":"Balanced — neither corrosive nor scaling"},{"label":"LSI < -0.3","value":"Corrosive — etches plaster, dissolves grout, corrodes metal"},{"label":"LSI > +0.3","value":"Scaling — calcium deposits on surfaces, equipment, salt cells"},{"label":"Factors","value":"pH, water temp, calcium hardness, total alkalinity, TDS/CYA"}],"important_notes":["In winter (cold water), LSI drops significantly — raise CH or TA to compensate","Salt pools tend to run high pH due to SWG process — monitor LSI closely","An LSI calculator app is essential for plaster pool service","Vinyl and fiberglass pools are not affected by LSI the same way — less critical but still best practice"]}'::jsonb,
 'verified'),

('water_chemistry', 'Ideal water chemistry ranges', null, null, null,
 '{"summary": "Quick reference for target water chemistry values. These ranges keep water safe, comfortable, clear, and non-damaging to equipment and surfaces.","key_values":[{"label":"Free Chlorine (FC)","value":"2-4 ppm (residential), per CYA chart"},{"label":"pH","value":"7.4-7.6 ideal (acceptable 7.2-7.8)"},{"label":"Total Alkalinity (TA)","value":"80-120 ppm"},{"label":"Calcium Hardness (CH)","value":"250-350 ppm (plaster), 150-250 ppm (vinyl/fiberglass)"},{"label":"Cyanuric Acid (CYA)","value":"30-50 ppm (residential), per local code (commercial)"},{"label":"Salt (salt pools)","value":"2700-3400 ppm (check SWG manufacturer spec)"},{"label":"Temperature","value":"78-82°F (residential comfort), per code (commercial)"},{"label":"Total Dissolved Solids","value":"Below 1500 ppm above source water"}],"important_notes":["Test FC AND CYA together — FC alone is meaningless without knowing CYA","pH is the most volatile parameter — test and adjust frequently","TA, CH, and CYA change slowly and need less frequent testing","Use a quality drop-based test kit (Taylor K-2005 or K-2006) — strips are less accurate"]}'::jsonb,
 'verified');
