-- 015_seed_voltpal_reference.sql
-- Verified starter entries for the VoltPal reference database.

insert into voltpal.volt_reference (category, title, equipment_type, voltage_class, specification, content_json, source) values

-- Wire Sizing (NEC 310.16)
('wire_sizing', 'Copper conductor ampacity — NEC 310.16 (75°C column)', null, null, 'NEC 310.16',
 '{"summary": "Allowable ampacities of insulated copper conductors rated 0-2000V, in raceway or cable. 75°C column (THWN-2, XHHW) is the most commonly used for equipment terminations rated 75°C.","key_values":[{"label":"14 AWG","value":"15 A"},{"label":"12 AWG","value":"20 A"},{"label":"10 AWG","value":"30 A"},{"label":"8 AWG","value":"40 A"},{"label":"6 AWG","value":"55 A"},{"label":"4 AWG","value":"70 A"},{"label":"3 AWG","value":"85 A"},{"label":"2 AWG","value":"95 A"},{"label":"1 AWG","value":"110 A"},{"label":"1/0 AWG","value":"125 A"},{"label":"2/0 AWG","value":"145 A"},{"label":"3/0 AWG","value":"165 A"},{"label":"4/0 AWG","value":"195 A"},{"label":"250 kcmil","value":"215 A"},{"label":"300 kcmil","value":"240 A"},{"label":"350 kcmil","value":"260 A"},{"label":"500 kcmil","value":"320 A"}],"important_notes":["Apply derating for more than 3 current-carrying conductors in a raceway (NEC 310.15(C)(1))","Apply ambient temperature correction if above 86°F / 30°C","14 AWG breaker max = 15A, 12 AWG = 20A, 10 AWG = 30A per NEC 240.4(D)","Termination temperature rating must match — most equipment is rated 75°C"]}'::jsonb,
 'verified'),

('wire_sizing', 'Aluminum conductor ampacity — NEC 310.16 (75°C column)', null, null, 'NEC 310.16',
 '{"summary": "Allowable ampacities of insulated aluminum conductors. Aluminum requires larger wire sizes than copper for the same ampacity. Minimum size for branch circuits is typically 12 AWG but most jurisdictions require copper for 15A and 20A circuits.","key_values":[{"label":"12 AWG","value":"15 A"},{"label":"10 AWG","value":"25 A"},{"label":"8 AWG","value":"30 A"},{"label":"6 AWG","value":"40 A"},{"label":"4 AWG","value":"55 A"},{"label":"3 AWG","value":"65 A"},{"label":"2 AWG","value":"75 A"},{"label":"1 AWG","value":"85 A"},{"label":"1/0 AWG","value":"100 A"},{"label":"2/0 AWG","value":"115 A"},{"label":"3/0 AWG","value":"130 A"},{"label":"4/0 AWG","value":"150 A"},{"label":"250 kcmil","value":"170 A"},{"label":"300 kcmil","value":"190 A"},{"label":"350 kcmil","value":"210 A"},{"label":"500 kcmil","value":"260 A"}],"important_notes":["Use anti-oxidant compound on all aluminum terminations","Aluminum expands/contracts more than copper — check torque specs annually","CO/ALR rated devices required for 15A and 20A circuits","Minimum feeder size is typically 4 AWG or larger for aluminum"]}'::jsonb,
 'verified'),

-- Motor Circuits (NEC 430)
('motor_circuits', 'Three-phase motor FLA — NEC Table 430.250', 'motor', '460V', 'NEC 430.250',
 '{"summary": "Full-load current (FLA) for three-phase AC motors at 460V. Use these values — not the nameplate — for sizing branch circuit conductors, short-circuit protection, and overload protection per NEC 430.","key_values":[{"label":"1 HP","value":"2.1 A"},{"label":"1.5 HP","value":"3.0 A"},{"label":"2 HP","value":"3.4 A"},{"label":"3 HP","value":"4.8 A"},{"label":"5 HP","value":"7.6 A"},{"label":"7.5 HP","value":"11 A"},{"label":"10 HP","value":"14 A"},{"label":"15 HP","value":"21 A"},{"label":"20 HP","value":"27 A"},{"label":"25 HP","value":"34 A"},{"label":"30 HP","value":"40 A"},{"label":"40 HP","value":"52 A"},{"label":"50 HP","value":"65 A"},{"label":"60 HP","value":"77 A"},{"label":"75 HP","value":"96 A"},{"label":"100 HP","value":"124 A"},{"label":"125 HP","value":"156 A"},{"label":"150 HP","value":"180 A"},{"label":"200 HP","value":"240 A"}],"important_notes":["Wire sizing: 125% of motor FLA (NEC 430.22)","Overload protection: 115-125% of nameplate FLA (NEC 430.32)","Branch circuit protection (inverse time breaker): 250% of FLA (NEC 430.52)","For 230V motors, multiply 460V FLA by 2","For 208V motors, multiply 460V FLA by 2.21"]}'::jsonb,
 'verified'),

('motor_circuits', 'Single-phase motor FLA — NEC Table 430.248', 'motor', '230V', 'NEC 430.248',
 '{"summary": "Full-load current for single-phase AC motors at 115V and 230V. Use NEC table values for conductor and protection sizing, not nameplate amps.","key_values":[{"label":"1/4 HP @ 115V","value":"5.8 A"},{"label":"1/3 HP @ 115V","value":"7.2 A"},{"label":"1/2 HP @ 115V","value":"9.8 A"},{"label":"3/4 HP @ 115V","value":"13.8 A"},{"label":"1 HP @ 115V","value":"16 A"},{"label":"1 HP @ 230V","value":"8 A"},{"label":"1.5 HP @ 230V","value":"10 A"},{"label":"2 HP @ 230V","value":"12 A"},{"label":"3 HP @ 230V","value":"17 A"},{"label":"5 HP @ 230V","value":"28 A"},{"label":"7.5 HP @ 230V","value":"40 A"},{"label":"10 HP @ 230V","value":"50 A"}],"important_notes":["Single-phase motors draw higher current than 3-phase for same HP","Split-phase and capacitor-start motors have high inrush — size protection accordingly","For 120V values, use the 115V column","Wire at 125% of FLA for continuous duty"]}'::jsonb,
 'verified'),

-- Overcurrent Protection
('overcurrent_protection', 'Standard breaker and fuse sizes — NEC 240.6(A)', null, null, 'NEC 240.6(A)',
 '{"summary": "Standard ampere ratings for fuses and inverse time circuit breakers. When calculated ampacity falls between standard sizes, the next size up is permitted for non-motor loads (NEC 240.4(B)).","key_values":[{"label":"Standard sizes","value":"15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 110, 125, 150, 175, 200, 225, 250, 300, 350, 400, 450, 500, 600, 700, 800, 1000, 1200, 1600, 2000, 2500, 3000, 4000, 5000, 6000"},{"label":"Next size up rule","value":"NEC 240.4(B) — permitted when conductor ampacity does not match a standard size"},{"label":"Exception","value":"14 AWG max 15A, 12 AWG max 20A, 10 AWG max 30A — NEC 240.4(D), cannot go to next size up"}],"important_notes":["Motor circuits use separate sizing rules per NEC 430","GFCI breakers add no ampacity derating","Adjustable-trip breakers must be set at or below conductor ampacity","Coordinate breaker ratings with available fault current (AIC rating)"]}'::jsonb,
 'verified'),

-- Grounding
('grounding', 'Equipment grounding conductor sizing — NEC 250.122', null, null, 'NEC 250.122',
 '{"summary": "Minimum size of equipment grounding conductors (EGC) based on the rating of the overcurrent device (breaker or fuse) protecting the circuit. Copper values shown.","key_values":[{"label":"15A breaker","value":"14 AWG Cu"},{"label":"20A breaker","value":"12 AWG Cu"},{"label":"30A breaker","value":"10 AWG Cu"},{"label":"40A breaker","value":"10 AWG Cu"},{"label":"60A breaker","value":"10 AWG Cu"},{"label":"100A breaker","value":"8 AWG Cu"},{"label":"200A breaker","value":"6 AWG Cu"},{"label":"300A breaker","value":"4 AWG Cu"},{"label":"400A breaker","value":"3 AWG Cu"},{"label":"500A breaker","value":"2 AWG Cu"},{"label":"600A breaker","value":"1 AWG Cu"},{"label":"800A breaker","value":"1/0 AWG Cu"},{"label":"1000A breaker","value":"2/0 AWG Cu"},{"label":"1200A breaker","value":"3/0 AWG Cu"},{"label":"1600A breaker","value":"4/0 AWG Cu"},{"label":"2000A breaker","value":"250 kcmil Cu"}],"important_notes":["Increase EGC size proportionally if conductors are upsized for voltage drop","Aluminum EGC must be two sizes larger than copper","EGC must be continuous — no splices except irreversible compression","Metal raceways can serve as EGC if listed and properly installed"]}'::jsonb,
 'verified'),

-- Conduit Fill
('conduit_fill', 'Conduit fill — maximum conductors', null, null, 'NEC Chapter 9 Table 1',
 '{"summary": "Maximum percentage of conduit cross-sectional area that can be filled with conductors. Based on NEC Chapter 9, Table 1.","key_values":[{"label":"1 conductor","value":"53% fill"},{"label":"2 conductors","value":"31% fill"},{"label":"3+ conductors","value":"40% fill"},{"label":"1/2\" EMT (3+ wires)","value":"4x 12 AWG THHN, 3x 10 AWG THHN"},{"label":"3/4\" EMT (3+ wires)","value":"7x 12 AWG THHN, 5x 10 AWG THHN, 4x 8 AWG THHN"},{"label":"1\" EMT (3+ wires)","value":"12x 12 AWG THHN, 9x 10 AWG THHN, 5x 8 AWG THHN, 3x 6 AWG THHN"},{"label":"1-1/4\" EMT","value":"Approx 2x capacity of 1\" EMT"},{"label":"1-1/2\" EMT","value":"Approx 2.5x capacity of 1\" EMT"},{"label":"2\" EMT","value":"Approx 3.5x capacity of 1\" EMT"}],"important_notes":["Count ALL conductors including grounds in fill calculation","Nipples (24 inches or less) are permitted 60% fill","Use actual wire OD from NEC Chapter 9 Table 5 for exact calculations","Reduce ampacity (derate) when more than 3 current-carrying conductors per NEC 310.15(C)(1)"]}'::jsonb,
 'verified'),

-- NEC Reference
('nec_reference', 'GFCI protection requirements — NEC 210.8', null, null, 'NEC 210.8 (2023)',
 '{"summary": "Ground-fault circuit interrupter (GFCI) protection is required for 125V through 250V receptacles in specific locations. The 2023 NEC significantly expanded GFCI requirements.","key_values":[{"label":"Bathrooms","value":"All receptacles — 125V-250V, all amperages"},{"label":"Kitchens","value":"All receptacles serving countertop surfaces + within 6 ft of sink"},{"label":"Outdoors","value":"All receptacles — residential and commercial"},{"label":"Garages / Accessory buildings","value":"All receptacles"},{"label":"Crawl spaces / Unfinished basements","value":"All receptacles"},{"label":"Laundry areas","value":"All receptacles"},{"label":"Within 6 ft of any sink","value":"All receptacles (2023 NEC)"},{"label":"Indoor damp/wet locations","value":"All 125V-250V up to 50A (2023 NEC)"},{"label":"Commercial kitchens","value":"All receptacles — 125V-250V up to 50A (2023 NEC)"}],"important_notes":["GFCI trips at 4-6 mA ground fault current within 25ms","Test GFCI devices monthly per manufacturer instructions","GFCI protection can be at the breaker, receptacle, or upstream device","Dedicated equipment on individual branch circuit may have exceptions — check local amendments"]}'::jsonb,
 'verified'),

('nec_reference', 'Arc-fault circuit interrupter (AFCI) requirements — NEC 210.12', null, null, 'NEC 210.12 (2023)',
 '{"summary": "AFCI protection is required for 120V, 15A and 20A branch circuits supplying outlets and devices in dwelling unit rooms. AFCIs detect dangerous arcing conditions that can cause fires.","key_values":[{"label":"Required locations","value":"All habitable rooms in dwelling units: bedrooms, living rooms, dining rooms, kitchens, hallways, closets, laundry, sunrooms"},{"label":"Not required","value":"Bathrooms, garages, outdoors, unfinished basements (these get GFCI instead)"},{"label":"Types","value":"Combination-type AFCI breaker is the standard — detects series and parallel arcs"},{"label":"Dual function","value":"AFCI/GFCI combo breakers available for rooms requiring both"}],"important_notes":["AFCI nuisance tripping is common with certain loads — vacuum motors, treadmills, some LED dimmers","If AFCI trips repeatedly, investigate for actual arcing (damaged conductor, loose connection) before bypassing","AFCI is required on new circuits and circuit extensions in existing homes","Some jurisdictions have not adopted the full 2023 NEC AFCI requirements — check local code"]}'::jsonb,
 'verified'),

-- Safety
('safety', 'Arc flash PPE categories — NFPA 70E Table 130.7(C)(15)(a)', null, null, 'NFPA 70E',
 '{"summary": "Arc flash PPE categories define the minimum protective clothing and equipment required when working on or near energized equipment. Higher categories = greater arc flash energy = more protection needed.","key_values":[{"label":"Category 1 (4 cal/cm²)","value":"Arc-rated shirt + pants, safety glasses, hearing protection, leather gloves"},{"label":"Category 2 (8 cal/cm²)","value":"Arc-rated shirt + pants or coverall, arc-rated face shield + balaclava, safety glasses, hearing protection, leather gloves"},{"label":"Category 3 (25 cal/cm²)","value":"Arc flash suit (jacket + pants), arc-rated hood with face shield, safety glasses, hearing protection, rubber insulating gloves + leather protectors"},{"label":"Category 4 (40 cal/cm²)","value":"Arc flash suit (jacket + pants), arc-rated hood with face shield, safety glasses, hearing protection, rubber insulating gloves + leather protectors"},{"label":"Above 40 cal/cm²","value":"DO NOT WORK — de-energize the equipment"}],"important_notes":["Always check the arc flash label on the equipment for incident energy level","Category method is an alternative to incident energy analysis — use one or the other","Arc-rated (AR) clothing is NOT the same as flame-resistant (FR) — it must be tested to ASTM F1959","Rubber insulating gloves must be tested every 6 months per ASTM D120"]}'::jsonb,
 'verified'),

('safety', 'Lockout/tagout (LOTO) procedure — OSHA 1910.147', null, null, 'OSHA 1910.147',
 '{"summary": "The six essential steps of a lockout/tagout procedure for servicing or maintaining electrical equipment. LOTO is required whenever unexpected energization could cause injury.","key_values":[{"label":"Step 1: Preparation","value":"Identify all energy sources, notify affected employees, gather locks/tags"},{"label":"Step 2: Shutdown","value":"Shut down equipment using normal operating controls"},{"label":"Step 3: Isolation","value":"Open disconnects, close valves, block/bleed stored energy"},{"label":"Step 4: Lock & Tag","value":"Apply personal lock and tag to each energy-isolating device"},{"label":"Step 5: Verify","value":"Try to start the equipment — confirm zero energy state. Test with meter."},{"label":"Step 6: Perform work","value":"Complete servicing with equipment in verified zero-energy state"}],"important_notes":["Each worker applies their OWN lock — no sharing locks","Try-start is the most critical step — never skip verification","Stored energy (capacitors, springs, pneumatic, hydraulic) must be relieved","Group LOTO requires a designated coordinator and lockbox procedure","Removal of another persons lock requires documented employer procedure"]}'::jsonb,
 'verified'),

-- VFD / Drives
('vfd_drives', 'Common VFD fault codes — general reference', 'vfd', null, null,
 '{"summary": "Most common VFD (variable frequency drive) fault codes and their typical causes. Exact codes vary by manufacturer but the underlying faults are universal across Allen-Bradley, Siemens, ABB, Yaskawa, Danfoss, and others.","key_values":[{"label":"Overcurrent (OC / F001)","value":"Motor short, cable damage, drive undersized, accel time too fast"},{"label":"Overvoltage (OV / F002)","value":"Decel time too fast (regeneration), incoming voltage spike, DC bus charge"},{"label":"Ground fault (GF / F003)","value":"Motor insulation failure, cable damage, moisture in junction box"},{"label":"Overtemperature (OH / F004)","value":"Blocked ventilation, ambient too high, fan failure, overloaded"},{"label":"Undervoltage (UV / F005)","value":"Incoming power sag/loss, loose connection, undersized supply"},{"label":"Motor overload (OL / F006)","value":"Mechanical binding, overloaded, motor params not set correctly"},{"label":"Communication loss (CE / F007)","value":"Network cable/connection issue, PLC not sending run command"},{"label":"Output phase loss (OPL)","value":"Loose motor lead, contactor between drive and motor, cable break"}],"important_notes":["Always check fault history — pattern of faults tells the story","Overcurrent on startup = check motor and cables with megger before resetting","Ground fault = megger test motor windings to ground before resetting","Never bypass a VFD to test a motor on line power without disconnecting the drive output first","Check DC bus voltage with drive powered off before working inside — capacitors hold lethal charge"]}'::jsonb,
 'verified'),

-- Voltage Drop
('wire_sizing', 'Voltage drop calculation', null, null, 'NEC 210.19(A) Informational Note',
 '{"summary": "Voltage drop should not exceed 3% for branch circuits or 5% total (feeder + branch). While NEC 210.19(A) is informational, most engineers and inspectors treat it as a design requirement.","key_values":[{"label":"Formula (single phase)","value":"Vd = (2 × L × I × R) / 1000 — L in feet, R = ohms per 1000 ft"},{"label":"Formula (three phase)","value":"Vd = (1.732 × L × I × R) / 1000"},{"label":"12 AWG Cu resistance","value":"1.93 ohms / 1000 ft (at 75°C)"},{"label":"10 AWG Cu resistance","value":"1.21 ohms / 1000 ft"},{"label":"8 AWG Cu resistance","value":"0.764 ohms / 1000 ft"},{"label":"6 AWG Cu resistance","value":"0.491 ohms / 1000 ft"},{"label":"4 AWG Cu resistance","value":"0.308 ohms / 1000 ft"},{"label":"2 AWG Cu resistance","value":"0.194 ohms / 1000 ft"},{"label":"1/0 AWG Cu resistance","value":"0.122 ohms / 1000 ft"},{"label":"Max 3% on 120V","value":"3.6V drop allowed"},{"label":"Max 3% on 240V","value":"7.2V drop allowed"},{"label":"Max 3% on 480V","value":"14.4V drop allowed"}],"important_notes":["Long runs to outbuildings, wells, and submersible pumps often require upsizing for voltage drop","Motors are sensitive to voltage drop — low voltage causes higher current draw and overheating","LED drivers and electronic equipment may malfunction below 5% drop even though NEC allows it","Calculate voltage drop at the actual load current, not the breaker rating"]}'::jsonb,
 'verified');
