-- 018_seed_pipepal_reference.sql
-- Verified starter entries for the PipePal reference database.

insert into pipepal.pipe_reference (category, title, equipment_type, system_type, specification, content_json, source) values

-- Pipe Sizing
('pipe_sizing', 'Water supply pipe sizing — fixture unit method', null, 'potable_water', 'IPC Table 604.3 / UPC Table 6-4',
 '{"summary": "Water supply pipe sizing is based on Water Supply Fixture Units (WSFU). Total fixture units determine minimum pipe diameter. Velocity should not exceed 8 fps for cold water or 5 fps for hot water to prevent erosion and water hammer.","key_values":[{"label":"1/2\" copper","value":"Up to 4 WSFU"},{"label":"3/4\" copper","value":"Up to 14 WSFU"},{"label":"1\" copper","value":"Up to 30 WSFU"},{"label":"1-1/4\" copper","value":"Up to 46 WSFU"},{"label":"1-1/2\" copper","value":"Up to 70 WSFU"},{"label":"2\" copper","value":"Up to 124 WSFU"},{"label":"Lavatory faucet","value":"1 WSFU"},{"label":"Kitchen faucet","value":"1.4 WSFU"},{"label":"Bathtub/shower","value":"1.4 WSFU"},{"label":"Toilet (tank)","value":"2.2 WSFU"},{"label":"Clothes washer","value":"1.4 WSFU"},{"label":"Dishwasher","value":"1.4 WSFU"},{"label":"Hose bibb","value":"2.2 WSFU"}],"important_notes":["These values assume 60 psi street pressure with adequate residual","Derate for long runs, elevation changes, and pressure losses through PRVs","PEX sizing differs from copper — check manufacturer flow charts","Hot water recirculation lines are sized by heat loss, not fixture units"]}'::jsonb,
 'verified'),

('pipe_sizing', 'DWV drain pipe sizing — drainage fixture units', null, 'dwv', 'IPC Table 710.1',
 '{"summary": "Drain, waste, and vent (DWV) pipe sizing is based on Drainage Fixture Units (DFU). Horizontal drains must maintain minimum slope (1/4 inch per foot for pipes 3 inches and smaller, 1/8 inch per foot for 4 inches and larger).","key_values":[{"label":"1-1/2\" drain","value":"3 DFU max (lavatory, tub, shower)"},{"label":"2\" drain","value":"6 DFU max (kitchen sink, washing machine)"},{"label":"3\" drain","value":"20 DFU max (floor drain, multiple fixtures)"},{"label":"4\" drain","value":"160 DFU max (building drain, toilets)"},{"label":"Lavatory","value":"1 DFU"},{"label":"Bathtub/shower","value":"2 DFU"},{"label":"Kitchen sink","value":"2 DFU"},{"label":"Toilet","value":"3 DFU (requires 3\" minimum drain)"},{"label":"Clothes washer","value":"2 DFU"},{"label":"Floor drain","value":"2 DFU"},{"label":"Min slope 1-1/2\" to 3\"","value":"1/4\" per foot"},{"label":"Min slope 4\" and larger","value":"1/8\" per foot"}],"important_notes":["Toilets (water closets) require minimum 3-inch drain — cannot be reduced downstream","Building drain/sewer must be minimum 4 inches for residential","Vent connections must be above the flood rim of the highest fixture served","Horizontal wet venting is permitted in some codes — check local amendments"]}'::jsonb,
 'verified'),

-- Pipe Materials
('pipe_materials', 'Copper pipe types and applications', null, null, 'ASTM B88',
 '{"summary": "Copper pipe comes in three wall thicknesses: Type K (thickest, green), Type L (medium, blue), and Type M (thinnest, red). All are available in hard-drawn (rigid) and soft (annealed) temper.","key_values":[{"label":"Type K","value":"Underground, water service, heavy-duty — thickest wall"},{"label":"Type L","value":"Interior water supply, general plumbing — most common for residential"},{"label":"Type M","value":"Drain, vent, low-pressure — thinnest wall, not permitted in all jurisdictions for water supply"},{"label":"DWV","value":"Drain/waste/vent only — yellow stripe, cannot be used for pressure"},{"label":"Solder — lead-free","value":"Required for potable water (95/5 tin-antimony or tin-silver)"},{"label":"Solder — 50/50","value":"Prohibited on potable water since 1986 (Safe Drinking Water Act)"},{"label":"Brazing","value":"BCuP-5 (Sil-Fos 15%) for copper-to-copper, requires nitrogen purge for ACR"}],"important_notes":["All potable water solder must be lead-free per federal law","Flux must be water-soluble and listed for potable water","Soft copper (rolled) used for underground and refrigeration — easier to bend but lower burst pressure","Dielectric unions required where copper connects to steel to prevent galvanic corrosion"]}'::jsonb,
 'verified'),

('pipe_materials', 'PEX tubing types and connections', null, 'potable_water', 'ASTM F876/F877',
 '{"summary": "PEX (cross-linked polyethylene) is the dominant residential water supply piping. Three types: PEX-A (Engel method, most flexible), PEX-B (silane method, most common), PEX-C (irradiation method). All are rated 160 psi at 73°F.","key_values":[{"label":"PEX-A","value":"Most flexible, expansion fittings (Uponor/Wirsbo), self-healing from kinks"},{"label":"PEX-B","value":"Most common, crimp or clamp fittings, slightly stiffer"},{"label":"PEX-C","value":"Least common, crimp fittings, most susceptible to kinking"},{"label":"Connection methods","value":"Crimp (copper rings), clamp (stainless cinch), expansion (cold expansion), push-fit (SharkBite)"},{"label":"Max temperature","value":"200°F (rated 180°F continuous)"},{"label":"UV sensitivity","value":"Do NOT expose to sunlight — max 60 days during construction"},{"label":"Color coding","value":"Red = hot, blue = cold, white = either"}],"important_notes":["PEX cannot be used within 18 inches of a water heater — use copper stub-outs","PEX is not permitted for exterior above-grade use (UV degradation)","Crimp rings require a go/no-go gauge to verify — required by code","Brass fittings must be lead-free (NSF 61) for potable water","PEX-A expansion fittings have the highest flow rate (full-port, no restriction)"]}'::jsonb,
 'verified'),

-- Gas Piping
('gas_piping', 'Gas pipe sizing — BTU capacity by pipe size and length', null, 'natural_gas', 'NFPA 54 / IFGC',
 '{"summary": "Natural gas pipe sizing is based on total connected BTU load, pipe length from meter to appliance, and specific gravity of gas (0.60 for natural gas). Undersized gas pipe causes low pressure at the appliance, resulting in poor performance or safety shutoff.","key_values":[{"label":"1/2\" black iron, 20 ft","value":"92,000 BTU/hr"},{"label":"1/2\" black iron, 50 ft","value":"56,000 BTU/hr"},{"label":"3/4\" black iron, 20 ft","value":"213,000 BTU/hr"},{"label":"3/4\" black iron, 50 ft","value":"130,000 BTU/hr"},{"label":"1\" black iron, 20 ft","value":"430,000 BTU/hr"},{"label":"1\" black iron, 50 ft","value":"265,000 BTU/hr"},{"label":"1-1/4\" black iron, 20 ft","value":"786,000 BTU/hr"},{"label":"1-1/4\" black iron, 50 ft","value":"487,000 BTU/hr"},{"label":"Typical furnace","value":"40,000-120,000 BTU"},{"label":"Typical water heater","value":"30,000-75,000 BTU"},{"label":"Gas range","value":"65,000 BTU"},{"label":"Gas dryer","value":"22,000-35,000 BTU"},{"label":"Fireplace (gas log)","value":"25,000-60,000 BTU"}],"important_notes":["Measure total pipe length from meter to farthest appliance — longest run sizes the main","Add all BTU loads on each pipe section — size for cumulative load","CSST (corrugated stainless steel tubing) has its own sizing tables — do not use black iron tables","Pressure test gas lines at 3 psi (IPC) or per local code before turning on","All gas pipe joints must be tested with approved leak detection solution or electronic sniffer"]}'::jsonb,
 'verified'),

-- Code Requirements
('code_requirements', 'Trap and vent requirements — IPC / UPC basics', null, 'dwv', 'IPC Section 1002/UPC Section 1001',
 '{"summary": "Every plumbing fixture must have a trap and a vent. The trap provides a water seal (2-4 inches) to prevent sewer gas from entering the building. The vent allows air behind the water to prevent siphoning the trap.","key_values":[{"label":"Trap seal depth","value":"2 to 4 inches of water (IPC 1002.4)"},{"label":"Max trap arm length (1-1/2\")","value":"5 feet (IPC Table 1002.2) / 3-1/2 ft (UPC)"},{"label":"Max trap arm length (2\")","value":"8 feet (IPC) / 5 ft (UPC)"},{"label":"Max trap arm length (3\")","value":"12 feet (IPC) / 6 ft (UPC)"},{"label":"Min vent size","value":"1-1/4\" (for 1-1/2\" trap), never smaller than half the drain size"},{"label":"S-traps","value":"Prohibited — must use P-trap with proper venting"},{"label":"Drum traps","value":"Prohibited in most jurisdictions (except bathtubs in some codes)"},{"label":"AAV (Air Admittance Valve)","value":"Permitted as individual/branch vent in IPC — prohibited in UPC"}],"important_notes":["Every fixture MUST be vented — an unvented fixture will siphon its trap and allow sewer gas in","Double-trapping is prohibited — each fixture gets exactly one trap","Cleanouts required at every change of direction >45° and every 100 ft of horizontal drain","Horizontal vent pipes must slope upward to the point of connection to prevent moisture blocking"]}'::jsonb,
 'verified'),

('code_requirements', 'Water heater installation requirements', 'water_heater', null, 'IPC/IMC/IFGC',
 '{"summary": "Water heater installations must comply with plumbing, mechanical, and fuel gas codes. Key requirements include temperature/pressure relief valve discharge, seismic strapping (where required), expansion tank (closed systems), and proper venting for gas units.","key_values":[{"label":"T&P relief valve","value":"Required on every water heater — must discharge to safe location"},{"label":"T&P discharge","value":"Within 6 inches of floor or to exterior — no traps, no threads, no reduction"},{"label":"Expansion tank","value":"Required when system has backflow preventer or PRV (closed system)"},{"label":"Seismic strapping","value":"Required in seismic zones (California, Pacific NW, etc.)"},{"label":"Gas vent clearance","value":"Single wall: 6\" from combustibles; B-vent: 1\" from combustibles"},{"label":"Drain pan","value":"Required when installed above living space or where leakage causes damage"},{"label":"Max temperature","value":"120°F recommended, 140°F max for residential (scalding prevention)"},{"label":"Shut-off valve","value":"Required on cold water inlet within sight of water heater"}],"important_notes":["NEVER cap, plug, or reduce the T&P relief valve discharge pipe","Gas water heaters need combustion air — verify room volume or provide makeup air ducts","Tankless water heaters require Category III stainless vent (not B-vent)","Electric water heaters require dedicated circuit — typically 30A/240V for 40-50 gallon","Recirculation pumps must have check valve and timer or demand-activated control"]}'::jsonb,
 'verified'),

-- Backflow Prevention
('backflow', 'Backflow prevention device types and applications', null, 'potable_water', 'IPC Section 608/ASSE Standards',
 '{"summary": "Backflow preventers protect potable water from contamination. Device selection is based on degree of hazard (high vs low) and type of backflow (backpressure vs back-siphonage). More hazardous cross-connections require more robust devices.","key_values":[{"label":"Air gap (AG)","value":"Highest protection — 2x pipe diameter minimum, used for indirect waste"},{"label":"RPZ (Reduced Pressure Zone)","value":"High hazard, backpressure & back-siphonage — irrigation, boilers, fire sprinklers"},{"label":"DCVA (Double Check Valve)","value":"Low hazard, backpressure & back-siphonage — fire lines (non-toxic)"},{"label":"PVB (Pressure Vacuum Breaker)","value":"High hazard, back-siphonage only — irrigation (must be 12\" above highest outlet)"},{"label":"AVB (Atmospheric Vacuum Breaker)","value":"Low hazard, back-siphonage only — hose bibbs, utility sinks"},{"label":"Hose bibb vacuum breaker","value":"Required on all hose connections per code"}],"important_notes":["RPZ and DCVA must be tested annually by certified backflow tester","RPZ assemblies discharge water during operation — install with adequate drainage","PVB cannot be installed where backpressure is possible (below downstream piping)","Local water utility may require specific devices — check with the purveyor","Testable devices need isolation valves and test cocks — install per manufacturer specs"]}'::jsonb,
 'verified'),

-- Safety
('safety', 'Soldering and brazing safety for plumbers', null, null, 'OSHA / CGA',
 '{"summary": "Soldering and brazing with open flame in occupied buildings requires fire watch procedures, fire extinguisher within reach, and hot work permits in commercial settings.","key_values":[{"label":"Fire extinguisher","value":"Minimum 10-lb ABC within 10 feet of work area"},{"label":"Fire watch","value":"Maintain 30 minutes after last flame operation"},{"label":"Heat shield","value":"Required when soldering near combustibles — use flame guard blanket"},{"label":"Ventilation","value":"Flux fumes are irritating — work in ventilated areas or use fume extraction"},{"label":"Hot work permit","value":"Required in most commercial/institutional buildings"},{"label":"MAP gas vs propane","value":"MAP burns hotter (3730°F vs 3600°F) — faster brazing but more fire risk"},{"label":"Nitrogen purge","value":"Required when brazing ACR copper to prevent oxide scale inside pipe"}],"important_notes":["Never solder or braze on a line with pressure — drain and verify zero pressure first","Lead-free solder ONLY for potable water — 50/50 is prohibited","Check behind walls with thermal camera after soldering to ensure no smoldering","CPVC requires solvent cement, not heat — NEVER solder near CPVC (it will ignite)","PEX cannot be exposed to open flame — maintain safe distance when soldering nearby copper"]}'::jsonb,
 'verified'),

-- Fixture Installation
('fixture_install', 'Toilet (water closet) rough-in dimensions', 'toilet', null, 'IPC/UPC',
 '{"summary": "Standard toilet rough-in is 12 inches from finished wall to center of closet flange. Code minimum clearances must be maintained for accessibility and functionality.","key_values":[{"label":"Standard rough-in","value":"12 inches (center of flange to finished wall)"},{"label":"10-inch rough-in","value":"Available for tight spaces — requires 10\" rough toilet"},{"label":"14-inch rough-in","value":"Older homes — use 14\" rough toilet or offset flange"},{"label":"Min side clearance","value":"15 inches center to side wall/obstruction (IPC)"},{"label":"Min front clearance","value":"21 inches from front of toilet to wall/fixture (IPC) — 24\" recommended"},{"label":"ADA clearance","value":"18 inches center to side wall, 60\" clear floor space"},{"label":"Closet flange height","value":"1/4 inch above finished floor (set on top of tile, not under)"},{"label":"Wax ring vs wax-free","value":"Wax: traditional, single-use; Wax-free: reusable, better for uneven flanges"}],"important_notes":["Always measure rough-in from finished wall, not framing","Closet flange must be solidly secured to floor — wobble = leak","If flange is below floor level, use an extra-thick wax ring or flange extender","Do not overtighten closet bolts — porcelain cracks easily","Replace supply line (braided stainless) at every toilet install — old lines burst"]}'::jsonb,
 'verified'),

-- Venting
('venting', 'Vent pipe sizing and types', null, 'dwv', 'IPC Section 904/906',
 '{"summary": "Vent pipes allow air into the drainage system to prevent trap siphonage and equalize pressure. Multiple venting methods exist — individual vent, common vent, wet vent, circuit vent, and air admittance valve (AAV).","key_values":[{"label":"Individual vent","value":"Dedicated vent from each fixture trap to vent stack — most reliable"},{"label":"Common vent","value":"Two fixtures at same level sharing one vent — e.g., back-to-back lavatories"},{"label":"Wet vent","value":"Drain pipe that also serves as vent for downstream fixtures — size up one pipe size"},{"label":"Circuit vent","value":"Single vent serving a group of fixtures on a horizontal branch — max 8 fixtures"},{"label":"AAV (Studor vent)","value":"Mechanical one-way valve — allows air in, blocks sewer gas out. Permitted in IPC, not UPC"},{"label":"Stack vent","value":"Extension of a soil/waste stack above highest fixture — must extend through roof"},{"label":"Min vent through roof","value":"6 inches above roof (12 inches in snow regions)"}],"important_notes":["Vent must connect above the flood rim of the highest fixture it serves","Dry vent pipes must slope upward minimum 1/4 inch per foot to prevent moisture blockage","Vent terminals must be minimum 10 feet from any openable window or air intake","AAVs must be accessible for service — cannot be sealed inside a wall permanently","Island sink venting requires special loop vent or AAV configuration"]}'::jsonb,
 'verified'),

-- Tankless Water Heaters
('equipment', 'Tankless water heater troubleshooting reference', 'tankless_water_heater', null, null,
 '{"summary": "Tankless (on-demand) water heaters are gas or electric units that heat water only when needed. Common issues relate to flow rate, scale buildup, venting, and minimum activation flow.","key_values":[{"label":"Min activation flow","value":"0.4-0.75 GPM depending on model — low-flow fixtures may not trigger"},{"label":"Scale flush interval","value":"Every 12-18 months (hard water) or annually (moderate water)"},{"label":"Descaling solution","value":"White vinegar or commercial descaler — circulate 45-60 minutes"},{"label":"Error: No ignition","value":"Check gas supply, gas valve, igniter, flame rod, venting blockage"},{"label":"Error: Overheating","value":"Scale buildup restricting flow, blocked heat exchanger fins"},{"label":"Error: Cold water sandwich","value":"Normal in non-recirculating systems — install buffer tank or recirculation"},{"label":"Venting","value":"Category III stainless steel (gas) — cannot use standard B-vent"},{"label":"Gas line sizing","value":"Most require 3/4\" gas line minimum — verify BTU input vs gas capacity"}],"important_notes":["Tankless units demand very high BTU input (150,000-199,000) — gas line must be sized accordingly","Electric tankless units require massive electrical service (100-150A at 240V for whole-house)","Hard water above 7 grains = install a water softener upstream or plan for frequent descaling","Condensing tankless units are more efficient (98%+) and use PVC venting instead of stainless","Multiple units in parallel may be needed for large homes — single unit typically serves 2-3 fixtures simultaneously"]}'::jsonb,
 'verified');
