-- 035_seed_splicepal_cert_questions.sql
-- Seed ~100 cert prep questions for SplicePal (fiber optic certifications).
-- Cert levels: FOT, CFOT, CFOS_S, CFOS_T
-- Categories: fiber_fundamentals, splicing, otdr, testing, osp, isp, standards, safety

-- ============================================================
-- FOT (Fiber Optic Technician) — 25 questions (entry level)
-- ============================================================

INSERT INTO splicepal.cert_prep_questions (cert_level, category, question, option_a, option_b, option_c, option_d, correct_answer, explanation, code_reference, difficulty) VALUES

('FOT', 'fiber_fundamentals', 'What principle allows light to travel through an optical fiber?', 'Reflection off the buffer coating', 'Total internal reflection at the core-cladding boundary', 'Absorption and re-emission of photons', 'Electromagnetic induction', 'B', 'Light is guided through fiber by total internal reflection (TIR). When the angle of incidence exceeds the critical angle at the core-cladding interface, light is completely reflected back into the core.', 'TIA-568.3-D', 'easy'),

('FOT', 'fiber_fundamentals', 'The cladding of a standard single-mode fiber has a diameter of:', '50 micrometers', '62.5 micrometers', '125 micrometers', '250 micrometers', 'C', 'All standard telecommunications fibers (single-mode and multimode) have a 125 µm cladding diameter per ITU-T G.652 and TIA-568.3-D. The 250 µm dimension is the buffer coating.', 'ITU-T G.652', 'easy'),

('FOT', 'fiber_fundamentals', 'Which fiber type supports only one mode of light propagation?', 'OM1 multimode', 'OM3 multimode', 'OS2 single-mode', 'OM5 multimode', 'C', 'Single-mode fiber (OS1/OS2) has a core diameter of approximately 8-9 µm, which permits only one transverse mode to propagate. All OM designations are multimode.', 'TIA-568.3-D', 'easy'),

('FOT', 'fiber_fundamentals', 'A multimode fiber designated OM3 has a core diameter of:', '8.3 micrometers', '50 micrometers', '62.5 micrometers', '100 micrometers', 'B', 'OM3 is a laser-optimized 50/125 µm multimode fiber designed for 10 Gbps Ethernet up to 300 meters. OM1 uses 62.5 µm core.', 'TIA-568.3-D', 'easy'),

('FOT', 'fiber_fundamentals', 'The numerical aperture (NA) of a fiber determines its:', 'Maximum bandwidth', 'Light-gathering ability and acceptance cone', 'Tensile strength', 'Color coding', 'B', 'NA describes the cone of light that can enter the fiber and still undergo total internal reflection. A higher NA means a larger acceptance angle but generally more modal dispersion in multimode fiber.', 'TIA-568.3-D', 'medium'),

('FOT', 'fiber_fundamentals', 'What is the standard wavelength used for testing single-mode fiber?', '850 nm and 1300 nm', '1310 nm and 1550 nm', '780 nm and 850 nm', '1625 nm and 1650 nm', 'B', 'Single-mode fiber is tested at 1310 nm and 1550 nm. These correspond to the O-band and C-band windows where attenuation is lowest. 850 nm and 1300 nm are multimode test wavelengths.', 'TIA-526-14-B', 'easy'),

('FOT', 'fiber_fundamentals', 'Bend-insensitive single-mode fiber (ITU-T G.657.A2) is primarily designed for:', 'Long-haul submarine cables', 'Indoor and FTTH installations with tight bends', 'Data center backbone runs', 'Aerial cable plant', 'B', 'G.657.A2 fiber maintains low loss at bend radii down to 7.5 mm, making it ideal for fiber-to-the-home (FTTH) installations, MDUs, and tight indoor routing where macrobend loss would otherwise be a problem.', 'ITU-T G.657', 'medium'),

('FOT', 'safety', 'Bare fiber scraps from cleaving should be:', 'Left on the work surface for later cleanup', 'Disposed of in a designated fiber scrap container', 'Swept onto the floor', 'Placed in a regular trash can', 'B', 'Fiber scraps are nearly invisible glass slivers that can penetrate skin or eyes. They must be collected in a designated container (fiber scrap box) and never left on surfaces or disposed of in regular trash.', 'OSHA General Duty Clause', 'easy'),

('FOT', 'safety', 'When working with optical fiber test equipment, what class of laser is typically used in an OTDR?', 'Class 1 (eye safe)', 'Class 1M or 3R', 'Class 4 (high power)', 'Class 2 (visible)', 'B', 'Most OTDRs use Class 1M or Class 3R lasers. While the beam divergence limits direct hazard, viewing with optical instruments (such as looking into a fiber with a microscope) can concentrate the beam and cause eye injury.', 'IEC 60825-1', 'medium'),

('FOT', 'safety', 'Before performing any work in a manhole, a technician must first:', 'Set up the fusion splicer', 'Test the atmosphere for oxygen, combustible gas, and toxic gases', 'Begin pulling cable immediately', 'Contact the central office', 'B', 'Manholes are OSHA-defined confined spaces. Atmospheric testing for O₂ level, combustible gases (LEL), and toxic gases (H₂S, CO) must be completed before entry per OSHA 1910.146.', 'OSHA 1910.146', 'easy'),

('FOT', 'testing', 'An optical power meter measures light in what unit?', 'Ohms', 'Decibels referenced to one milliwatt (dBm)', 'Volts', 'Hertz', 'B', 'Optical power is measured in dBm (decibels relative to 1 milliwatt). The meter converts detected optical power to a logarithmic scale. Absolute power can also be displayed in milliwatts or microwatts.', 'TIA-526-14-B', 'easy'),

('FOT', 'testing', 'A Tier 1 (basic) fiber test includes:', 'OTDR trace and event map', 'Insertion loss and length measurement', 'Chromatic dispersion measurement', 'PMD testing', 'B', 'Tier 1 testing per TIA-568.3-D uses a light source and power meter (LSPM) to measure insertion loss, and may include length. Tier 2 adds OTDR testing. Dispersion testing is beyond both tiers.', 'TIA-568.3-D', 'easy'),

('FOT', 'testing', 'When testing a fiber link, the reference method that uses two test reference cords is called:', '1-cord reference', '2-cord reference (method B)', '3-cord reference', 'Enhanced reference', 'B', 'The 2-cord (or 2-jumper) reference method, also called Method B, nulls out both test cords. This tests only the link under test including its end connectors.', 'TIA-526-14-B', 'medium'),

('FOT', 'standards', 'According to TIA-568.3-D, the maximum allowable insertion loss for a mated pair of single-mode connectors is:', '0.25 dB', '0.50 dB', '0.75 dB', '1.0 dB', 'C', 'TIA-568.3-D specifies a maximum of 0.75 dB for a mated connector pair for both single-mode and multimode. Factory-terminated connectors should achieve 0.50 dB or better.', 'TIA-568.3-D', 'medium'),

('FOT', 'fiber_fundamentals', 'The color code for a 12-fiber ribbon follows which standard?', 'EIA/TIA-598-D', 'ANSI/TIA-606-C', 'TIA-568.3-D', 'NFPA 70E', 'A', 'TIA-598-D defines the standard fiber color code: blue, orange, green, brown, slate, white, red, black, yellow, violet, rose, aqua for positions 1-12.', 'TIA-598-D', 'easy'),

('FOT', 'osp', 'When pulling fiber cable through conduit, the maximum recommended pulling tension for a standard indoor/outdoor cable is typically:', '25 lbs', '100 lbs', '600 lbs', 'Determined by the cable manufacturer rating', 'D', 'Maximum pulling tension varies by cable type and manufacturer. The cable datasheet specifies maximum long-term and short-term tension ratings. Exceeding them causes fiber stress and potential microbend loss.', 'GR-20 CORE', 'medium'),

('FOT', 'osp', 'The minimum bend radius for a standard 12-fiber indoor cable under no load is typically:', '0.5 inches', '1 inch (25 mm)', '10 times the cable outer diameter', '50 times the cable outer diameter', 'C', 'The general rule is 10x cable OD for no-load and 20x cable OD under tension. Always check the manufacturer specification for the exact cable being installed.', 'TIA-568.3-D', 'easy'),

('FOT', 'isp', 'In a structured cabling system, the horizontal cable run from the telecommunications room to the work area outlet must not exceed:', '50 meters', '90 meters', '100 meters', '300 meters', 'B', 'TIA-568.1-D specifies a maximum of 90 meters for the permanent horizontal link. The total channel (including patch cords at both ends) may not exceed 100 meters.', 'TIA-568.1-D', 'easy'),

('FOT', 'standards', 'The jacket color typically used for single-mode fiber cable is:', 'Orange', 'Aqua', 'Yellow', 'Violet', 'C', 'Per TIA-598-D, yellow is the standard jacket color for single-mode fiber. Orange is multimode (OM1/OM2), aqua is OM3/OM4, and violet (lime green) is OM5.', 'TIA-598-D', 'easy'),

('FOT', 'fiber_fundamentals', 'Macrobend loss in fiber occurs when:', 'The fiber is bent below its minimum bend radius', 'A connector is improperly polished', 'Two different fiber types are spliced together', 'The fiber absorbs water', 'A', 'Macrobend loss occurs when the fiber is bent too tightly. Light rays exceed the critical angle at the core-cladding boundary and escape into the cladding. Bend-insensitive fiber is designed to minimize this.', 'TIA-568.3-D', 'easy'),

('FOT', 'testing', 'A visual fault locator (VFL) is used to:', 'Measure insertion loss', 'Identify breaks, tight bends, and bad connectors by visible red light', 'Create an OTDR trace', 'Measure optical return loss', 'B', 'A VFL emits visible red laser light (typically 650 nm) into the fiber. Light escapes at breaks, tight bends, or cracked connectors, making faults visible to the naked eye.', 'General practice', 'easy'),

('FOT', 'isp', 'When routing fiber cable through a building, it should never be:', 'Placed in cable tray', 'Run through innerduct', 'Laid directly on suspended ceiling tiles', 'Pulled through conduit', 'C', 'Fiber cable must never rest on ceiling tiles. It must be supported in J-hooks, cable tray, or innerduct. NEC Article 770 requires proper support and routing per building codes.', 'NEC Article 770', 'easy'),

('FOT', 'fiber_fundamentals', 'Attenuation in optical fiber is measured in:', 'dB per kilometer (dB/km)', 'Watts per meter', 'Ohms per kilometer', 'Volts per foot', 'A', 'Attenuation is the loss of optical power as light travels through fiber, expressed in dB/km. Typical values are 0.35 dB/km at 1310 nm and 0.22 dB/km at 1550 nm for single-mode.', 'TIA-568.3-D', 'easy'),

('FOT', 'testing', 'When using a power meter and light source, the test result is expressed as:', 'Optical return loss in dB', 'Insertion loss in dB', 'Chromatic dispersion in ps/nm·km', 'Bandwidth in MHz·km', 'B', 'A Tier 1 test with LSPM measures insertion loss — the total end-to-end attenuation of the link in dB. ORL requires a different instrument or additional OTDR analysis.', 'TIA-526-14-B', 'easy'),

('FOT', 'standards', 'The TIA standard that covers field testing of optical fiber cabling is:', 'TIA-568.3-D', 'TIA-526-14-B', 'TIA-606-C', 'TIA-607-D', 'B', 'TIA-526-14-B covers optical fiber field testing methods including reference setting, loss measurement, and reporting. TIA-568.3-D covers optical fiber cabling components and design. TIA-606-C covers administration/labeling.', 'TIA-526-14-B', 'medium'),

-- ============================================================
-- CFOT (Certified Fiber Optic Technician) — 30 questions
-- ============================================================

('CFOT', 'fiber_fundamentals', 'Modal dispersion limits bandwidth in multimode fiber because:', 'Light is absorbed by the coating', 'Different modes travel at different speeds, spreading the pulse', 'Single wavelengths cannot propagate', 'The fiber NA is too low', 'B', 'In multimode fiber, light travels in many modes (ray paths). Higher-order modes travel longer paths than axial modes, causing pulse spreading (modal dispersion) that limits bandwidth-distance.', 'TIA-568.3-D', 'medium'),

('CFOT', 'fiber_fundamentals', 'Chromatic dispersion in single-mode fiber is caused by:', 'Multiple modes propagating at different speeds', 'Different wavelengths of light traveling at different velocities in the glass', 'Bending of the fiber beyond minimum radius', 'Contamination on connector end-faces', 'B', 'Even a "single-mode" laser source emits a narrow range of wavelengths. Each wavelength travels at a slightly different velocity (material dispersion) and the waveguide geometry also contributes (waveguide dispersion). Together these form chromatic dispersion.', 'ITU-T G.652', 'medium'),

('CFOT', 'fiber_fundamentals', 'The water peak in optical fiber occurs near which wavelength?', '850 nm', '1310 nm', '1383 nm', '1550 nm', 'C', 'Hydroxyl (OH⁻) ions absorbed during manufacturing create an attenuation peak near 1383 nm. Modern "zero water peak" fibers (G.652.D) eliminate this, enabling full spectrum CWDM use.', 'ITU-T G.652.D', 'hard'),

('CFOT', 'splicing', 'The primary advantage of fusion splicing over mechanical splicing is:', 'Lower equipment cost', 'Lower average splice loss and greater long-term reliability', 'Faster deployment in emergency restoration', 'No electricity required', 'B', 'Fusion splices average 0.02-0.05 dB loss compared to 0.1-0.5 dB for mechanical splices. Fusion splices also have superior long-term reliability and lower reflectance, making them preferred for permanent installations.', 'TIA-568.3-D', 'easy'),

('CFOT', 'splicing', 'Before fusion splicing, the fiber must be stripped and then:', 'Buffed with polishing film', 'Cleaved to produce a flat end-face perpendicular to the fiber axis', 'Coated with index-matching gel', 'Bent to stress-relieve the glass', 'B', 'A precision cleave is essential for low-loss fusion splicing. The cleave angle must typically be less than 1 degree. The flat, mirror-like end-faces allow proper alignment and arc fusion.', 'General practice', 'easy'),

('CFOT', 'splicing', 'A typical acceptable fusion splice loss for single-mode fiber is:', 'Less than 0.1 dB', 'Less than 0.5 dB', 'Less than 1.0 dB', 'Less than 0.01 dB', 'A', 'Modern fusion splicers routinely achieve 0.02-0.05 dB on single-mode fiber. An acceptance criterion of 0.1 dB or less is standard. Losses above 0.1 dB should be re-spliced.', 'TIA-568.3-D', 'easy'),

('CFOT', 'splicing', 'What causes a high splice loss reading on a fusion splicer?', 'Perfect fiber alignment', 'Contamination, poor cleave, or core eccentricity', 'Using the correct splice protection sleeve', 'Proper arc current settings', 'B', 'High splice loss results from contaminated fiber, bad cleave angle (exceeding 1°), core/cladding eccentricity, or incorrect arc parameters. Cleaning fibers and achieving consistent cleaves are essential.', 'General practice', 'easy'),

('CFOT', 'testing', 'The 1-cord reference method (Method A) for loss testing includes:', 'The loss of one connector at each end of the link under test', 'Only the fiber loss with no connector loss', 'The loss of both test reference cords', 'Three connectors at each end', 'A', 'Method A references with one cord, then tests the link. This means one connection at each end of the LUT is included in the measurement, giving a more conservative (higher loss) result than Method B.', 'TIA-526-14-B', 'medium'),

('CFOT', 'testing', 'Optical return loss (ORL) is important because high reflections can:', 'Increase fiber bandwidth', 'Cause instability in laser transmitters and increase bit error rates', 'Improve splice quality', 'Reduce attenuation', 'B', 'High reflections (low ORL) can destabilize laser sources, especially DFB lasers used in single-mode systems, causing increased noise, reduced signal quality, and elevated bit error rates (BER).', 'TIA-568.3-D', 'medium'),

('CFOT', 'testing', 'An APC (Angled Physical Contact) connector reduces back-reflection by:', 'Using a flat polished end-face', 'Polishing the ferrule end at an 8-degree angle to deflect reflections out of the fiber core', 'Applying anti-reflective coating', 'Using a larger core fiber', 'B', 'APC connectors have an 8-degree angled end-face that directs Fresnel reflections away from the core and into the cladding, achieving return loss of 65 dB or better compared to ~55 dB for UPC.', 'TIA-568.3-D', 'medium'),

('CFOT', 'testing', 'What happens when you mate an APC connector with a UPC connector?', 'The connection works normally', 'Both ferrule end-faces are damaged, and high loss and reflections result', 'Return loss improves', 'Only APC connector is damaged', 'B', 'Mating APC (angled) with UPC (flat) connectors results in an air gap, causing high insertion loss (potentially > 3 dB), high reflections, and permanent damage to both ferrule end-faces. They must never be mated.', 'TIA-568.3-D', 'easy'),

('CFOT', 'standards', 'TIA-568.3-D maximum insertion loss budget for a multimode channel of 300 m at 850 nm with OM3 fiber includes:', 'Fiber loss only', 'Fiber loss + connector pair loss + splice loss', 'Connector loss only', 'Splice loss only', 'B', 'A channel loss budget per TIA-568.3-D accounts for fiber attenuation (dB/km × length), all mated connector pairs (≤ 0.75 dB each), and any splices (≤ 0.3 dB each).', 'TIA-568.3-D', 'medium'),

('CFOT', 'standards', 'The maximum splice loss allowed by TIA-568.3-D for installed splices is:', '0.1 dB', '0.3 dB', '0.5 dB', '0.75 dB', 'B', 'TIA-568.3-D specifies a maximum of 0.3 dB for any single splice. This is a field acceptance criterion; fusion splices should typically achieve well under this limit.', 'TIA-568.3-D', 'medium'),

('CFOT', 'osp', 'In an outside plant fiber route, a "hand hole" is:', 'A manhole with limited clearance', 'A shallow, non-entry grade-level access vault for splicing and cable management', 'An aerial cable clamp', 'A fiber distribution terminal', 'B', 'A hand hole is a small below-grade enclosure that provides access to cables without requiring personnel entry. Technicians reach in from the surface to pull cables, make splices, or access slack loops.', 'General practice', 'easy'),

('CFOT', 'osp', 'When installing aerial fiber cable using lashing wire, the cable should be:', 'Pulled under maximum tension', 'Attached to a support strand (messenger wire) with a continuous spiral lash', 'Laid directly on power lines', 'Stapled to the pole', 'B', 'Lashed aerial cable is supported by a separate steel messenger strand. A continuous spiral of lashing wire secures the cable to the messenger. This method allows cable expansion and contraction with temperature.', 'NESC', 'easy'),

('CFOT', 'osp', 'What is the minimum separation distance between fiber optic cable and power conductors when sharing a utility pole?', '6 inches', '12 inches (300 mm)', '40 inches (1000 mm)', 'No separation required', 'C', 'The NESC requires a communication safety zone at least 40 inches below power conductors on shared utility poles. The exact clearance depends on voltage level and pole configuration.', 'NESC Rule 235', 'hard'),

('CFOT', 'fiber_fundamentals', 'OM5 (wideband multimode) fiber is optimized for:', 'Long-haul single-mode transmission', 'Short-wavelength division multiplexing (SWDM) using 850-953 nm wavelengths', 'Analog CATV signals', 'Bend-insensitive single-mode applications', 'B', 'OM5 fiber is a 50/125 µm multimode fiber optimized for wavelengths from 850 to 953 nm, enabling short-wavelength division multiplexing (SWDM) for 100G and 400G over 4 wavelengths.', 'TIA-568.3-D', 'medium'),

('CFOT', 'safety', 'NFPA 70E requires fiber technicians working near energized electrical equipment to:', 'Use standard safety glasses only', 'Perform an arc flash risk assessment and use appropriate PPE', 'Work without PPE if voltage is below 600V', 'Only wear leather gloves', 'B', 'NFPA 70E mandates an arc flash risk assessment before work on or near energized equipment. Fiber technicians routing cables in electrical rooms or near panels must follow arc flash boundaries and PPE requirements.', 'NFPA 70E', 'medium'),

('CFOT', 'safety', 'The primary risk when viewing an active fiber with a microscope is:', 'Fiber breakage', 'Laser radiation entering the eye, amplified by the microscope optics', 'Static electricity damage', 'Chemical exposure', 'B', 'A microscope or magnifier concentrates the laser beam. Even a Class 1M source becomes hazardous when viewed through optical instruments. Always verify fibers are dark before inspecting with magnification.', 'IEC 60825-1', 'medium'),

('CFOT', 'testing', 'Connector end-face inspection should be performed:', 'Only when loss test fails', 'Before every mating — both patch panel and test reference cord ends', 'Only on new connectors', 'After the connection is made', 'B', 'IEC 61300-3-35 and industry best practice require inspecting and cleaning every connector end-face before mating. Contamination is the number one cause of insertion loss and reflectance failures.', 'IEC 61300-3-35', 'easy'),

('CFOT', 'testing', 'According to IEC 61300-3-35, a connector end-face pass/fail inspection looks at:', 'Color of the ferrule', 'Scratches, pits, and contamination within defined zones (core, cladding, adhesive, contact)', 'Ferrule length', 'Connector housing color', 'B', 'The IEC standard defines four concentric zones on the end-face (core, cladding, adhesive/epoxy, contact) and specifies maximum defect sizes and contamination allowed in each zone.', 'IEC 61300-3-35', 'medium'),

('CFOT', 'splicing', 'A mass fusion splicer differs from a single-fiber splicer in that it:', 'Produces lower quality splices', 'Can splice an entire 12-fiber ribbon simultaneously', 'Cannot splice single-mode fiber', 'Requires no cleaving', 'B', 'Mass fusion splicers align and splice all fibers in a ribbon (typically 12 or 24) simultaneously. This dramatically increases productivity in ribbon cable installations while maintaining splice quality.', 'General practice', 'easy'),

('CFOT', 'splicing', 'The purpose of a splice protection sleeve (heat-shrink) is to:', 'Increase splice loss', 'Protect the bare glass splice point from mechanical stress and moisture', 'Reduce return loss', 'Align the fibers before splicing', 'B', 'After fusion, the bare glass at the splice point is fragile. A heat-shrink sleeve with a strength member (steel rod or glass rod) protects against bending, tension, and environmental ingress.', 'General practice', 'easy'),

('CFOT', 'isp', 'In a fiber distribution hub (FDH) in an FTTH network, the primary component is:', 'An OTDR', 'An optical splitter', 'A media converter', 'A fusion splicer', 'B', 'An FDH houses optical splitters that divide the feeder fiber into multiple distribution fibers serving individual subscribers in a passive optical network (PON) architecture.', 'General practice', 'medium'),

('CFOT', 'osp', 'Direct-buried fiber cable must be placed at a minimum depth of:', '6 inches', '12 inches', '18-24 inches depending on local codes and cable type', '48 inches', 'C', 'NEC Article 830 and local regulations specify burial depths typically from 18 to 24 inches for direct-buried fiber cable. Concrete encased or conduit installations may permit shallower depths per local code.', 'NEC Article 830', 'medium'),

('CFOT', 'fiber_fundamentals', 'Fresnel reflection occurs at:', 'Every bend in the fiber', 'Any interface where the refractive index changes abruptly (e.g., glass-to-air)', 'Only in multimode fiber', 'Only at wavelengths above 1550 nm', 'B', 'Fresnel reflection occurs whenever light encounters an abrupt refractive index change, such as a glass-to-air gap at a connector or open fiber end. A flat-polished glass-to-air interface reflects approximately 3.5% (-14.7 dB).', 'General physics / TIA-568.3-D', 'medium'),

('CFOT', 'splicing', 'Index-matching gel in a mechanical splice serves to:', 'Glue the fibers permanently', 'Reduce Fresnel reflections by filling the air gap between fiber end-faces', 'Increase the splice loss intentionally', 'Clean the fiber end-face', 'B', 'The gel has a refractive index close to the fiber core, eliminating the glass-to-air interface and its ~0.3 dB Fresnel reflection loss. This significantly reduces both loss and back-reflection in mechanical splices.', 'General practice', 'medium'),

('CFOT', 'testing', 'Encircled flux (EF) launch conditions for multimode testing ensure:', 'Maximum power is coupled into the fiber', 'A consistent, repeatable mode fill that matches real-world transceiver launch conditions', 'Only cladding modes are excited', 'The fiber is tested at maximum bandwidth', 'B', 'Encircled flux per TIA-526-14-B Annex D defines a standardized modal launch that prevents overfilled or underfilled conditions, which would make loss measurements inconsistent and unrepeatable.', 'TIA-526-14-B', 'hard'),

-- ============================================================
-- CFOS/S (Certified Fiber Optic Specialist — Splicing) — 25 questions
-- ============================================================

('CFOS_S', 'splicing', 'The typical cleave angle specification for quality fusion splicing is:', 'Less than 5 degrees', 'Less than 2 degrees', 'Less than 1 degree', 'Less than 0.5 degrees', 'C', 'Most fusion splicers require a cleave angle under 1 degree for reliable low-loss splices. Cleave angles exceeding 1 degree cause light to refract at the splice point rather than passing straight through.', 'General practice / splicer specifications', 'easy'),

('CFOS_S', 'splicing', 'Core alignment fusion splicers achieve lower loss than cladding alignment splicers because:', 'They use higher arc temperatures', 'They actively align the fiber cores using a profile alignment system (PAS) camera', 'They do not require cleaving', 'They only work with multimode fiber', 'B', 'Core alignment splicers image the fiber profile from two orthogonal angles and actively position the cores in alignment. Cladding alignment relies on V-groove positioning of the outer cladding, which does not account for core eccentricity.', 'General practice', 'medium'),

('CFOS_S', 'splicing', 'When splicing dissimilar fiber types (e.g., G.652 to G.657), the splicer should be set to:', 'Standard SM mode — fibers are compatible', 'A specific mismatch mode; the splicer may need MFD compensation arc parameters', 'The splicer cannot join different fiber types', 'Mechanical splice mode', 'B', 'While G.652 and G.657 are compatible, their mode field diameters (MFDs) differ slightly. Advanced splicers offer fiber type selection that adjusts arc power and duration to optimize the splice for MFD mismatch.', 'ITU-T G.657 / splicer manuals', 'hard'),

('CFOS_S', 'splicing', 'A gainer (apparent negative loss) seen on an OTDR at a splice point usually indicates:', 'An exceptionally good splice', 'A transition from smaller to larger mode field diameter fiber, creating a measurement artifact', 'A broken fiber', 'A reflective mechanical splice', 'B', 'When testing from fiber with a smaller MFD into fiber with a larger MFD, more backscatter returns from the larger fiber, making the splice appear as a gain. Bidirectional averaging reveals the true splice loss.', 'TIA-526-14-B', 'medium'),

('CFOS_S', 'splicing', 'The recommended arc test procedure on a fusion splicer should be performed:', 'Once per year', 'At the start of each splicing session and when environmental conditions change', 'Only when splices fail', 'Never — factory settings are permanent', 'B', 'Arc tests calibrate the electrode discharge to ambient temperature, humidity, and altitude. Running arc tests at session start and when conditions change (e.g., moving from a vehicle to a manhole) ensures consistent fusion.', 'Splicer manufacturer guidelines', 'easy'),

('CFOS_S', 'splicing', 'When preparing ribbon fiber for mass fusion splicing, the ribbon strip length must be:', 'Exactly equal to the heat-shrink protector length', 'Sufficient for the splicer V-grooves plus cleave length, typically 30-40 mm of exposed fiber', 'As short as possible', '100 mm of bare fiber', 'B', 'The strip length must provide enough exposed fiber to sit in the cleaver and splicer V-grooves. Too short and the fibers will not reach the electrodes; too long increases handling risk. 30-40 mm is typical for most mass splicers.', 'Splicer manufacturer guidelines', 'medium'),

('CFOS_S', 'splicing', 'Electrode wear on a fusion splicer results in:', 'Lower splice loss over time', 'Inconsistent arc discharge, higher splice loss, and potential fiber deformation', 'Improved cleave quality', 'No effect on splice quality', 'B', 'As electrodes erode, the arc becomes asymmetric and less predictable. This leads to inconsistent melting, higher splice loss, and visible deformation at the splice point. Electrodes should be replaced per the manufacturers schedule.', 'Splicer manufacturer guidelines', 'medium'),

('CFOS_S', 'splicing', 'When a splice protection sleeve wrinkles or has bubbles after heating, the technician should:', 'Accept it — appearance does not matter', 'Re-do the heat-shrink or use a new sleeve, as wrinkles indicate inadequate protection', 'Add more heat to melt it flat', 'Cut away the wrinkled portion', 'B', 'Wrinkles or bubbles in a heat-shrink sleeve indicate it did not seal properly and may allow moisture ingress or provide inadequate bend protection. The sleeve should be removed and replaced.', 'General practice', 'easy'),

('CFOS_S', 'splicing', 'The purpose of pre-fusion (cleaning arc) on a fusion splicer is to:', 'Fully splice the fibers', 'Burn off surface contaminants on the fiber ends before the main fusion arc', 'Test electrode condition', 'Strip the buffer coating', 'B', 'A short low-power pre-fusion arc removes dust, moisture, and other surface contaminants from the fiber end-faces just before the main fusion, improving splice consistency.', 'Splicer manufacturer guidelines', 'medium'),

('CFOS_S', 'splicing', 'When organizing fibers in a splice tray, the minimum fiber loop diameter should be:', '30 mm (1.2 inches)', '60 mm (2.4 inches) for standard fiber, 30 mm for bend-insensitive', '10 mm (0.4 inches)', '120 mm (4.7 inches)', 'B', 'Standard single-mode fiber requires a minimum storage loop of approximately 60 mm diameter. Bend-insensitive fiber (G.657.A2/B3) can tolerate 30 mm. Loops below minimum cause macrobend loss.', 'TIA-568.3-D / ITU-T G.657', 'medium'),

('CFOS_S', 'splicing', 'A common cause of high splice loss on 250 µm bare fiber is:', 'Using a core alignment splicer', 'Fiber curl (residual curvature from buffer memory) causing misalignment in V-grooves', 'Splicing in a warm environment', 'Using alcohol to clean the fiber', 'B', 'Bare 250 µm fiber can retain curvature from the buffer tube or reel, causing the fiber to lift out of the V-grooves. This is especially problematic in cladding-alignment splicers where V-groove positioning is critical.', 'General practice', 'hard'),

('CFOS_S', 'splicing', 'After completing splicing in a closure, a technician should perform what test?', 'Visual inspection only', 'An end-to-end OTDR or power meter test to verify all splices meet acceptance criteria', 'No testing is required if splicer estimates are good', 'A bend test on each splice', 'B', 'Splicer-estimated losses are approximate. End-to-end testing (OTDR or LSPM) after closure is essential to verify that all splices, fiber routing, and the closure itself have not introduced unexpected loss.', 'TIA-526-14-B', 'easy'),

('CFOS_S', 'splicing', 'When re-splicing a bad splice, the technician must account for:', 'Nothing — just re-cleave and splice', 'Fiber length consumed by each cleave, which reduces available slack', 'Only arc power adjustment', 'Electrode replacement first', 'B', 'Each strip and cleave consumes approximately 30-40 mm of fiber. After several re-splices, available slack may become insufficient. Planning for re-splice attempts during initial fiber slack storage is critical.', 'General practice', 'medium'),

('CFOS_S', 'splicing', 'Splicing a 50 µm multimode fiber to a 62.5 µm multimode fiber will result in:', 'No loss in either direction', 'High loss when light travels from the 62.5 µm fiber into the 50 µm fiber', 'High loss only from 50 µm to 62.5 µm', 'Improved bandwidth', 'B', 'When light exits the larger 62.5 µm core into the smaller 50 µm core, the core area mismatch causes significant loss (approximately 2.1 dB). In the reverse direction, loss is minimal because the 50 µm output overfills the larger core less.', 'TIA-568.3-D', 'medium'),

('CFOS_S', 'osp', 'A fiber optic splice closure must be:', 'Only waterproof', 'Re-enterable, environmentally sealed, and capable of protecting splices from moisture, rodents, and mechanical stress', 'Permanently sealed — never reopened', 'Left open for ventilation', 'B', 'Closures must provide long-term environmental protection while remaining re-enterable for future maintenance, adds, and changes. They must resist water, temperature extremes, and physical damage.', 'GR-771 CORE', 'easy'),

('CFOS_S', 'splicing', 'The estimated splice loss displayed by a fusion splicer is calculated by:', 'Measuring actual light throughput', 'Analyzing core alignment offset from the PAS camera images and applying a mathematical model', 'Testing with a built-in OTDR', 'Measuring the arc current', 'B', 'The splicer estimates loss by analyzing the residual core offset, MFD mismatch, and deformation visible in the camera images. This is an estimate — actual loss measured by OTDR may differ.', 'Splicer manufacturer documentation', 'medium'),

('CFOS_S', 'splicing', 'When splicing fibers at altitude (above 5,000 feet / 1,500 m), a technician should:', 'Use the same arc settings as sea level', 'Perform arc calibration tests — lower air pressure requires arc adjustments', 'Avoid fusion splicing entirely', 'Use mechanical splices only', 'B', 'At altitude, reduced air density affects arc behavior. The arc may be wider and cooler. Running the splicer arc test recalibrates the discharge for current atmospheric pressure.', 'Splicer manufacturer guidelines', 'medium'),

('CFOS_S', 'splicing', 'A "bubble" visible at the splice point after fusion indicates:', 'A perfect splice', 'Trapped air or contamination that was vaporized, requiring a re-splice', 'Normal glass flow', 'Electrode alignment', 'B', 'Bubbles at the splice indicate contamination (dirt, moisture, or residual coating) that vaporized during the arc. The bubble creates a void that increases loss and weakens the splice. The splice must be re-done.', 'General practice', 'easy'),

('CFOS_S', 'splicing', 'For a 288-fiber cable build with ribbon fiber, the most efficient splice method is:', 'Single fiber fusion splicing each fiber individually', 'Mass fusion splicing 12 or 24 fibers at a time', 'Mechanical splicing all 288 fibers', 'Pigtail splicing with pre-connectorized assemblies', 'B', 'Mass fusion splicing of 12- or 24-fiber ribbons dramatically reduces splicing time on high-count cables. A 288-fiber cable requires only 24 mass splices (12-fiber) versus 288 individual splices.', 'General practice', 'easy'),

('CFOS_S', 'safety', 'Isopropyl alcohol (IPA) used for fiber cleaning should be:', '70% concentration for maximum cleaning', '99% or higher purity — lower concentrations leave water residue on fiber', '50% diluted with water', 'Replaced with acetone only', 'B', 'Only 99%+ pure IPA should be used for fiber cleaning. Lower concentrations contain water that leaves residue on the glass, increasing splice loss. IPA should also be kept in a sealed container to prevent moisture absorption.', 'General practice', 'easy'),

('CFOS_S', 'splicing', 'A pigtail splice is:', 'A splice between two cables', 'A factory-terminated fiber with a connector on one end, spliced to field cable on the other', 'A type of mechanical splice', 'A technique for splicing ribbon fiber', 'B', 'Pigtails are factory-terminated fiber assemblies (connector + short fiber). The bare end is fusion-spliced to field cable fibers, providing high-quality connectorization without field polishing.', 'General practice', 'easy'),

('CFOS_S', 'standards', 'The Telcordia GR-326 standard governs:', 'Fiber cable construction', 'Single-mode optical connector performance and reliability', 'OTDR testing procedures', 'Splice closure design', 'B', 'GR-326-CORE specifies requirements for single-mode connectors including insertion loss, return loss, durability, environmental stability, and end-face geometry.', 'GR-326-CORE', 'hard'),

('CFOS_S', 'splicing', 'Proof testing a splice by applying a calibrated pull (tension test) verifies:', 'Splice optical loss', 'Mechanical strength of the splice — typically 1-2 Newtons minimum', 'The fiber type being spliced', 'Electrode condition', 'B', 'Some splicers include a tension test that applies a calibrated pull to the completed splice. This verifies the fused glass joint can withstand the minimum tensile load without breaking, ensuring long-term mechanical reliability.', 'IEC 61073-1', 'hard'),

-- ============================================================
-- CFOS/T (Certified Fiber Optic Specialist — Testing) — 20 questions
-- ============================================================

('CFOS_T', 'otdr', 'An OTDR measures fiber characteristics using:', 'A continuous beam of light and a power meter', 'Short pulses of light and analysis of Rayleigh backscatter and Fresnel reflections', 'An electrical signal injected into the fiber', 'A broadband white light source', 'B', 'An OTDR launches short laser pulses and measures the time and intensity of backscattered (Rayleigh) and reflected (Fresnel) light returning to the instrument. This creates a distance-vs-loss trace of the entire fiber.', 'TIA-526-14-B', 'easy'),

('CFOS_T', 'otdr', 'The dead zone of an OTDR is:', 'A length of fiber with zero loss', 'The distance after a reflective event during which the OTDR receiver is saturated and cannot detect other events', 'A damaged section of fiber', 'The maximum range of the OTDR', 'B', 'After a strong reflection (e.g., from a connector), the OTDR receiver becomes temporarily saturated. The distance during this recovery is the dead zone. Shorter pulse widths reduce dead zones but also reduce dynamic range.', 'General OTDR theory', 'easy'),

('CFOS_T', 'otdr', 'A ghost (or phantom) event on an OTDR trace appears as:', 'A real splice loss event', 'A reflective event at a distance that is a multiple of the actual reflective event distance, with no corresponding physical feature', 'A break in the fiber', 'Normal backscatter', 'B', 'Ghosts occur when reflected light bounces between two reflective events (e.g., the OTDR front panel connector and a near connector). The double-transit creates a false event at twice the distance. Ghosts are non-reflective and disappear with longer pulse widths or launch fiber.', 'General OTDR theory', 'medium'),

('CFOS_T', 'otdr', 'Using a launch fiber (dead zone box) before the fiber under test:', 'Is unnecessary for modern OTDRs', 'Moves the OTDR dead zone away from the first connector so it can be properly characterized', 'Adds unwanted loss', 'Is only needed for multimode testing', 'B', 'A launch fiber (typically 100-500 m) pushes the near-end dead zone past the first connector of the link under test, allowing its loss and reflectance to be measured. A receive fiber similarly characterizes the far-end connector.', 'TIA-526-14-B', 'easy'),

('CFOS_T', 'otdr', 'When selecting the OTDR pulse width, shorter pulses provide:', 'Greater dynamic range', 'Better event resolution (shorter dead zones) but less dynamic range', 'Higher backscatter levels', 'No difference in measurement quality', 'B', 'Shorter pulses inject less energy and therefore have less dynamic range (cannot test as far), but they create shorter dead zones and better separate closely spaced events. Longer pulses see farther but blur nearby events.', 'General OTDR theory', 'easy'),

('CFOS_T', 'otdr', 'Bidirectional OTDR testing is required because:', 'It doubles the measurement speed', 'Splice loss measured from one direction can be affected by MFD differences; averaging both directions gives true splice loss', 'One direction tests multimode and the other tests single-mode', 'It is a TIA requirement for Tier 1 testing only', 'B', 'Due to differences in backscatter coefficients between fibers joined at a splice, unidirectional OTDR measurements can show gainers or exaggerated losses. Bidirectional averaging eliminates this artifact and reveals the true splice loss.', 'TIA-526-14-B', 'medium'),

('CFOS_T', 'otdr', 'On an OTDR trace, a non-reflective event (downward step with no spike) most likely indicates:', 'A connector', 'A fusion splice, macrobend, or fiber stress point', 'An open fiber end', 'A mechanical splice', 'B', 'Fusion splices and bends cause loss without Fresnel reflection, appearing as a downward step in the backscatter trace. Connectors and mechanical splices typically show reflective events (upward spike followed by a step).', 'General OTDR theory', 'easy'),

('CFOS_T', 'otdr', 'The refractive index setting on an OTDR must match the fiber under test because:', 'It affects the laser wavelength', 'The OTDR uses the index of refraction to convert time-of-flight to accurate distance', 'It changes the pulse width', 'It calibrates the power meter', 'B', 'The OTDR calculates distance as d = (c × t) / (2 × n), where n is the group index of refraction. An incorrect index setting causes all distance measurements to be proportionally wrong.', 'General OTDR theory', 'medium'),

('CFOS_T', 'testing', 'When performing attenuation testing at 1550 nm vs 1310 nm on single-mode fiber, you should expect:', 'Higher loss at 1550 nm', 'Lower loss at 1550 nm because the fiber attenuation coefficient is lower', 'Identical loss at both wavelengths', 'No meaningful difference', 'B', 'Standard single-mode fiber (G.652) has typical attenuation of 0.35 dB/km at 1310 nm and 0.22 dB/km at 1550 nm. Testing at 1550 nm will show lower fiber attenuation but may reveal macrobend losses that are invisible at 1310 nm.', 'ITU-T G.652', 'medium'),

('CFOS_T', 'testing', 'Testing at 1550 nm is particularly useful for detecting:', 'Connector contamination', 'Macrobend losses — fiber is more sensitive to bending at longer wavelengths', 'Splice contamination', 'Broken fibers', 'B', 'Longer wavelengths are more susceptible to macrobend loss. A fiber link that passes at 1310 nm but fails at 1550 nm almost certainly has a tight bend. This is why dual-wavelength testing is required.', 'TIA-526-14-B', 'medium'),

('CFOS_T', 'testing', 'Polarization mode dispersion (PMD) is a concern for:', 'Multimode systems only', 'High-speed single-mode systems (10 Gbps and above) over long distances', 'Short indoor fiber runs', 'All fiber systems regardless of speed', 'B', 'PMD causes differential group delay between orthogonal polarization modes in single-mode fiber. It becomes significant at 10 Gbps and above on long spans. PMD is a statistical phenomenon that varies with temperature and vibration.', 'TIA-455-124-A (FOTP-124)', 'hard'),

('CFOS_T', 'testing', 'Length measurement using an OTDR is accurate to approximately:', '±0.001%', '±1% of the measured distance', '±10% of the measured distance', '±0.01 meters regardless of distance', 'B', 'OTDR length accuracy depends on the refractive index setting accuracy and is typically ±1% (±0.5% to ±1.5% depending on the instrument). For precise length measurement, an optical time domain reflectometer is good but not as exact as a calibrated test fiber.', 'General OTDR specifications', 'medium'),

('CFOS_T', 'otdr', 'A high-reflectance event (large spike) followed by a complete signal drop on an OTDR trace indicates:', 'A good splice', 'An open connector, broken fiber, or fiber end', 'A macrobend', 'Normal end of the fiber with a termination', 'B', 'A large Fresnel reflection followed by loss of all backscatter signal indicates an abrupt fiber end — either a clean break, an unterminated connector, or the physical end of the fiber.', 'General OTDR theory', 'easy'),

('CFOS_T', 'testing', 'For Tier 2 certification testing, TIA-526-14-B requires:', 'Only insertion loss measurement', 'OTDR testing providing a fiber trace showing all events, in addition to Tier 1 LSPM results', 'Visual inspection only', 'Only length measurement', 'B', 'Tier 2 testing adds OTDR characterization to the Tier 1 LSPM insertion loss test. The OTDR trace identifies and locates individual events (splices, connectors, bends) along the entire fiber link.', 'TIA-526-14-B', 'easy'),

('CFOS_T', 'otdr', 'The dynamic range of an OTDR is defined as:', 'The maximum pulse width available', 'The difference in dB between the initial backscatter level and the noise floor', 'The distance the OTDR can measure', 'The number of events it can detect', 'B', 'Dynamic range (in dB) is the measurement between the initial backscatter level and the point where the signal meets the noise floor. Greater dynamic range allows testing of longer fibers or links with higher total loss.', 'General OTDR specifications', 'medium'),

('CFOS_T', 'testing', 'When testing a PON (passive optical network) with an OTDR, the main challenge is:', 'The fibers are too short', 'Splitters divide optical power, causing large loss events (e.g., 1:32 = ~17 dB) and limiting visibility beyond the splitter', 'PON fibers cannot be tested with an OTDR', 'The OTDR wavelength is incompatible', 'B', 'A 1:32 splitter introduces approximately 17 dB of loss. The OTDR must have sufficient dynamic range at a PON-compatible wavelength (1625 nm or 1650 nm to avoid disrupting live 1310/1490 nm services) to see past the splitter.', 'ITU-T G.984', 'hard'),

('CFOS_T', 'testing', 'The reference method that produces the most conservative (highest) loss measurement is:', 'Method A (1-cord reference)', 'Method B (2-cord reference)', 'Method C (3-cord reference)', 'All methods give identical results', 'A', 'Method A includes one mated connection at each end of the link in the measurement, resulting in the highest measured loss. Method B excludes test cord connections. Method C substitutes a known-good cord.', 'TIA-526-14-B', 'medium'),

('CFOS_T', 'standards', 'ANSI/TIA-455 (FOTP series) standards cover:', 'Cable installation practices', 'Test procedures for measuring specific fiber and component parameters', 'Building cabling design', 'Fiber color coding', 'B', 'The TIA-455 series (Fiber Optic Test Procedures / FOTPs) are individual standards each covering a specific measurement method such as attenuation, bandwidth, NA, cutoff wavelength, etc.', 'ANSI/TIA-455', 'easy'),

('CFOS_T', 'otdr', 'When testing installed fiber, the OTDR wavelength should be set to:', 'Any convenient wavelength', 'The wavelength(s) specified by the applicable standard for the fiber type being tested', 'Always 850 nm', 'The highest wavelength available', 'B', 'Single-mode fiber must be tested at 1310 nm and 1550 nm per TIA-526-14-B. Multimode is tested at 850 nm and 1300 nm. Using incorrect wavelengths produces invalid certification results.', 'TIA-526-14-B', 'easy'),

('CFOS_T', 'testing', 'An optical loss test set (OLTS) differs from a standalone power meter and light source in that:', 'It uses an OTDR', 'It integrates both source and meter with bidirectional capability, often testing two fibers simultaneously', 'It only tests multimode fiber', 'It measures chromatic dispersion', 'B', 'An OLTS is an integrated instrument pairing a calibrated source and meter at each end, enabling simultaneous bidirectional loss testing of two fibers. This doubles testing efficiency and ensures matched reference conditions.', 'TIA-526-14-B', 'medium');
