-- 037_seed_voltpal_cert_questions.sql
-- Seed ~100 cert prep questions for VoltPal (electrical certifications).
-- Cert levels: APPRENTICE, JOURNEYMAN, MASTER, NFPA_70E
-- Categories: nec_code, circuits, motors_drives, grounding, safety, transformers, controls

INSERT INTO voltpal.cert_prep_questions (cert_level, category, question, option_a, option_b, option_c, option_d, correct_answer, explanation, code_reference, difficulty) VALUES

-- ============================================================
-- APPRENTICE — 25 questions
-- ============================================================
('APPRENTICE', 'circuits', 'According to Ohm''s law, what is the current through a 24-ohm resistor with 120 V applied?', '2.88 A', '5 A', '10 A', '24 A', 'B', 'Ohm''s law: I = V / R = 120 / 24 = 5 A.', 'Ohm''s Law (basic theory)', 'easy'),
('APPRENTICE', 'circuits', 'What is the total resistance of three 30-ohm resistors connected in parallel?', '10 ohms', '30 ohms', '90 ohms', '15 ohms', 'A', 'For identical resistors in parallel: R_total = R / n = 30 / 3 = 10 ohms.', 'Basic circuit theory', 'easy'),
('APPRENTICE', 'nec_code', 'Per NEC Article 310, what is the maximum allowable ampacity of a 12 AWG copper conductor (THHN) in a raceway at 30 C ambient?', '20 A', '25 A', '30 A', '35 A', 'C', '12 AWG THHN copper is rated at 30 A per NEC Table 310.16. Note that overcurrent protection is limited to 20 A per NEC 240.4(D).', 'NEC 310.16', 'easy'),
('APPRENTICE', 'nec_code', 'What is the maximum number of 12 AWG THHN conductors permitted in a 3/4-inch EMT conduit?', '9', '12', '16', '6', 'C', 'NEC Chapter 9, Table C.1 allows 16 conductors of 12 AWG THHN in 3/4-inch EMT.', 'NEC Chapter 9, Table C.1', 'medium'),
('APPRENTICE', 'nec_code', 'The NEC requires receptacle outlets in a dwelling unit to be placed so that no point along the floor line is more than how many feet from an outlet?', '4 feet', '6 feet', '8 feet', '12 feet', 'B', 'NEC 210.52(A)(1) requires receptacles so that no point along the floor line in any wall space is more than 6 feet from a receptacle.', 'NEC 210.52(A)(1)', 'easy'),
('APPRENTICE', 'safety', 'What color is used to identify an equipment grounding conductor per NEC 250.119?', 'White', 'Red', 'Green or green with yellow stripe', 'Blue', 'C', 'NEC 250.119 requires equipment grounding conductors to be identified by a continuous green color, green with one or more yellow stripes, or bare.', 'NEC 250.119', 'easy'),
('APPRENTICE', 'grounding', 'What is the minimum size copper grounding electrode conductor for a 200 A service?', '4 AWG', '6 AWG', '8 AWG', '2 AWG', 'A', 'Per NEC Table 250.66, a 200 A service with up to 2/0 AWG copper service conductors requires a minimum 4 AWG copper grounding electrode conductor.', 'NEC Table 250.66', 'medium'),
('APPRENTICE', 'circuits', 'In a 120/240 V single-phase system, what voltage is measured between the two ungrounded (hot) conductors?', '120 V', '208 V', '240 V', '277 V', 'C', 'In a single-phase 120/240 V system, the two hot legs are 180 degrees out of phase, yielding 240 V line-to-line.', 'Basic electrical theory', 'easy'),
('APPRENTICE', 'nec_code', 'Per NEC 210.8, GFCI protection is required for all 125 V, 15 and 20 A receptacles in which of the following locations?', 'Bedrooms', 'Living rooms', 'Bathrooms', 'Hallways', 'C', 'NEC 210.8(A)(1) requires GFCI protection for all 125-volt, 15- and 20-ampere receptacles installed in bathrooms.', 'NEC 210.8(A)(1)', 'easy'),
('APPRENTICE', 'nec_code', 'What is the standard height above the floor for a residential light switch per industry practice?', '36 inches', '48 inches', '60 inches', '42 inches', 'B', 'While the NEC does not mandate a specific height, standard practice and ADA guidelines call for switches at 48 inches to the center of the box.', 'NEC 404.8 / ADA', 'easy'),
('APPRENTICE', 'safety', 'Before working on a circuit, a qualified person must verify the circuit is de-energized using:', 'A voltage detector that has been verified on a known source', 'Their hand', 'A continuity tester', 'Visual inspection only', 'A', 'OSHA and NFPA 70E require using a properly rated voltage tester that has been verified on a known live source before and after testing.', 'NFPA 70E 120.5', 'easy'),
('APPRENTICE', 'circuits', 'What is the power consumed by a 240 V, 20 A resistive heating element?', '2,400 W', '4,800 W', '1,200 W', '6,000 W', 'B', 'P = V x I = 240 x 20 = 4,800 W.', 'Basic electrical theory', 'easy'),
('APPRENTICE', 'nec_code', 'Per NEC 314.16, a standard single-gang device box (18 cubic inches) can contain a maximum of how many 12 AWG conductors?', '6', '8', '9', '5', 'B', 'NEC 314.16(B) assigns 2.25 cu in per 12 AWG conductor. 18 / 2.25 = 8 conductors (before deductions for devices, clamps, and grounds).', 'NEC 314.16(B)', 'medium'),
('APPRENTICE', 'grounding', 'Which NEC article covers grounding and bonding requirements?', 'Article 200', 'Article 210', 'Article 250', 'Article 300', 'C', 'NEC Article 250 provides comprehensive requirements for grounding and bonding of electrical systems and equipment.', 'NEC Article 250', 'easy'),
('APPRENTICE', 'nec_code', 'What is the minimum burial depth for a direct-buried UF cable supplying a residential 120 V, 20 A GFCI-protected circuit?', '6 inches', '12 inches', '18 inches', '24 inches', 'B', 'NEC Table 300.5 allows 12-inch burial depth for residential 120 V, 20 A GFCI-protected branch circuits using UF cable.', 'NEC Table 300.5', 'medium'),
('APPRENTICE', 'circuits', 'In a three-phase 208/120 V wye system, the phase-to-neutral voltage is:', '120 V', '208 V', '240 V', '277 V', 'A', 'In a 208/120 V wye system, the phase-to-neutral voltage is 120 V, and the phase-to-phase voltage is 208 V.', 'Basic electrical theory', 'easy'),
('APPRENTICE', 'safety', 'What is the minimum approach distance from exposed 120 V energized parts for an unqualified person?', '1 foot', '3 feet', '3.5 feet', '10 feet', 'C', 'NFPA 70E Table 130.4(E)(a) specifies 3.5 feet (42 inches) limited approach boundary for 120 V systems for unqualified persons.', 'NFPA 70E Table 130.4(E)(a)', 'medium'),
('APPRENTICE', 'nec_code', 'NEC 404.2 requires that a switch controlling lighting must have what conductor present at the switch box?', 'A red wire', 'A grounded (neutral) conductor', 'Two ground wires', 'A 10 AWG conductor', 'B', 'NEC 404.2(C) requires a grounded (neutral) conductor at switch locations to support occupancy sensors and smart switches.', 'NEC 404.2(C)', 'medium'),
('APPRENTICE', 'nec_code', 'Per NEC 240.4(D), the maximum overcurrent protection for 14 AWG copper is:', '15 A', '20 A', '25 A', '30 A', 'A', 'NEC 240.4(D) limits overcurrent protection to 15 A for 14 AWG, 20 A for 12 AWG, and 30 A for 10 AWG copper conductors.', 'NEC 240.4(D)', 'easy'),
('APPRENTICE', 'circuits', 'A 120 V circuit has a load of 1,800 W. What is the current draw?', '12 A', '15 A', '18 A', '20 A', 'B', 'I = P / V = 1,800 / 120 = 15 A.', 'Basic electrical theory', 'easy'),
('APPRENTICE', 'grounding', 'A ground rod must be driven to a minimum depth of:', '4 feet', '6 feet', '8 feet', '10 feet', 'C', 'NEC 250.53(G) requires ground rods to be driven to a minimum depth of 8 feet.', 'NEC 250.53(G)', 'easy'),
('APPRENTICE', 'nec_code', 'What type of cable is commonly used for residential wiring in walls and ceilings?', 'MC cable', 'NM-B (Romex)', 'MI cable', 'TC cable', 'B', 'NM-B (nonmetallic-sheathed cable, commonly called Romex) is the standard residential wiring method for interior walls and ceilings per NEC Article 334.', 'NEC Article 334', 'easy'),
('APPRENTICE', 'safety', 'When using a ladder near overhead power lines, what is the OSHA minimum clearance distance for lines under 50 kV?', '5 feet', '10 feet', '15 feet', '20 feet', 'B', 'OSHA 1926.1408 requires a minimum 10-foot clearance from overhead power lines energized at 50 kV or less.', 'OSHA 1926.1408', 'easy'),
('APPRENTICE', 'nec_code', 'NEC 110.26 requires a minimum of how many feet of clear working space in front of a 120/240 V panel?', '2 feet', '3 feet', '4 feet', '5 feet', 'B', 'NEC 110.26(A)(1) requires a minimum of 3 feet of clear working space in front of electrical equipment rated 0-150 V to ground (Condition 1).', 'NEC 110.26(A)(1)', 'easy'),
('APPRENTICE', 'circuits', 'What is the voltage drop across a 100-foot run of 12 AWG copper carrying 16 A on a 120 V single-phase circuit?', '3.1 V', '6.2 V', '8.0 V', '12.4 V', 'B', 'Vd = 2 x I x R x L / 1000. Using 12 AWG at 1.93 ohms/1000ft: Vd = 2 x 16 x 1.93 x 100 / 1000 = 6.18 V, approximately 6.2 V (5.2%).', 'NEC Chapter 9, Table 8', 'medium'),

-- ============================================================
-- JOURNEYMAN — 30 questions
-- ============================================================
('JOURNEYMAN', 'nec_code', 'Per NEC 220.12, the general lighting load for an office building is calculated at how many VA per square foot?', '2 VA', '3 VA', '3.5 VA', '5 VA', 'C', 'NEC Table 220.12 specifies 3.5 VA per square foot for office buildings for general lighting load calculations.', 'NEC Table 220.12', 'medium'),
('JOURNEYMAN', 'circuits', 'A 480 V, 3-phase motor has a full-load current of 52 A. What is the minimum conductor ampacity required per NEC 430.22?', '52 A', '60 A', '65 A', '78 A', 'C', 'NEC 430.22 requires branch circuit conductors to have an ampacity of not less than 125% of the motor FLC: 52 x 1.25 = 65 A.', 'NEC 430.22', 'medium'),
('JOURNEYMAN', 'motors_drives', 'What is the maximum rating for a time-delay fuse protecting a motor branch circuit with a 40 A full-load current per NEC 430.52?', '50 A', '70 A', '100 A', '80 A', 'B', 'NEC Table 430.52 allows time-delay fuses up to 175% of FLC for standard motors: 40 x 1.75 = 70 A.', 'NEC Table 430.52', 'medium'),
('JOURNEYMAN', 'nec_code', 'When derating conductors for more than 3 current-carrying conductors in a raceway per NEC 310.15(C)(1), what is the adjustment factor for 4-6 conductors?', '70%', '80%', '90%', '60%', 'B', 'NEC Table 310.15(C)(1) requires an 80% adjustment factor when there are 4 to 6 current-carrying conductors in a raceway.', 'NEC Table 310.15(C)(1)', 'medium'),
('JOURNEYMAN', 'grounding', 'Per NEC 250.122, the minimum equipment grounding conductor size for a 60 A circuit is:', '10 AWG copper', '8 AWG copper', '6 AWG copper', '12 AWG copper', 'A', 'NEC Table 250.122 requires a minimum 10 AWG copper EGC for a circuit protected by a 60 A overcurrent device.', 'NEC Table 250.122', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 430.24, the ampacity of conductors supplying several motors must be at least:', '100% of all motor FLCs', '125% of largest motor FLC plus 100% of all other motor FLCs', '125% of all motor FLCs', '150% of the largest motor FLC', 'B', 'NEC 430.24 requires feeder conductors sized at 125% of the largest motor FLC plus the sum of all other motor FLCs at 100%.', 'NEC 430.24', 'medium'),
('JOURNEYMAN', 'circuits', 'A three-phase transformer bank has a 480 V delta primary and a 208/120 V wye secondary. What is the turns ratio?', '2:1', '4:1', '2.31:1', '1.73:1', 'C', 'The turns ratio is primary phase voltage / secondary phase voltage = 480 / 208 = 2.31:1 (or equivalently 480 / (120 x sqrt(3))).', 'Transformer theory', 'hard'),
('JOURNEYMAN', 'nec_code', 'NEC Article 500 classifies hazardous locations by class, division, and group. Class I locations contain:', 'Combustible dusts', 'Flammable gases or vapors', 'Ignitible fibers', 'Metallic dusts', 'B', 'Class I hazardous locations contain flammable gases, vapors, or liquids. Class II is combustible dust. Class III is ignitible fibers/flyings.', 'NEC 500.5(B)', 'medium'),
('JOURNEYMAN', 'transformers', 'Per NEC 450.3(B), the maximum overcurrent protection for a dry-type transformer rated over 600 V on the primary side (with primary-only protection) is:', '125%', '150%', '200%', '300%', 'A', 'NEC Table 450.3(A) allows a maximum of 125% for the primary overcurrent protection of transformers over 600 V with primary-only protection. For the next standard fuse size up, the maximum is 150%.', 'NEC Table 450.3(A)', 'hard'),
('JOURNEYMAN', 'motors_drives', 'A VFD (variable frequency drive) controls motor speed by varying:', 'Only voltage', 'Only frequency', 'Both voltage and frequency', 'Only current', 'C', 'VFDs control speed by varying both the frequency and voltage supplied to the motor to maintain the proper V/Hz ratio for optimal torque.', 'Motor control theory', 'easy'),
('JOURNEYMAN', 'nec_code', 'Per NEC 210.19(A)(1), branch circuit conductors must have an ampacity of not less than:', 'The maximum load', '125% of the continuous load plus 100% of the noncontinuous load', '100% of the total load', '115% of the total load', 'B', 'NEC 210.19(A)(1) requires branch circuit conductor ampacity of at least 125% of the continuous load plus 100% of the noncontinuous load.', 'NEC 210.19(A)(1)', 'medium'),
('JOURNEYMAN', 'grounding', 'Per NEC 250.64(E), when multiple service disconnects are supplied from a single service drop, the grounding electrode conductor may be connected to a:', 'Common grounding bus bar', 'Single disconnect only', 'Water pipe only', 'Any disconnect at random', 'A', 'NEC 250.64(E) permits the grounding electrode conductor to be connected to a common grounding electrode conductor bus bar sized per 250.66.', 'NEC 250.64(E)', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 230.71, the maximum number of service disconnecting means permitted in a single enclosure is:', '2', '4', '6', '8', 'C', 'NEC 230.71(A) permits a maximum of six disconnects grouped at one location to serve as the service disconnecting means.', 'NEC 230.71(A)', 'easy'),
('JOURNEYMAN', 'circuits', 'A 3-phase, 480 V motor draws 28 A at 0.85 power factor. What is the kW load?', '13.4 kW', '19.7 kW', '23.2 kW', '28.0 kW', 'B', 'P = sqrt(3) x V x I x PF = 1.732 x 480 x 28 x 0.85 = 19,752 W, approximately 19.7 kW.', 'Three-phase power formula', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 215.2(A)(1), feeder conductors must have an ampacity of at least 125% of the continuous load plus 100% of the noncontinuous load. A feeder supplies 40 A continuous and 30 A noncontinuous. Minimum ampacity is:', '70 A', '80 A', '87.5 A', '100 A', 'B', '125% of 40 A = 50 A, plus 100% of 30 A = 30 A. Total = 80 A minimum ampacity.', 'NEC 215.2(A)(1)', 'medium'),
('JOURNEYMAN', 'controls', 'In a 3-wire motor control circuit, the seal-in (holding) contact is wired:', 'In series with the motor', 'In parallel with the start pushbutton', 'In series with the stop pushbutton', 'In parallel with the overload relay', 'B', 'The seal-in contact is wired in parallel with the momentary start button. When the start button is released, the holding contact maintains the circuit.', 'Motor control theory', 'easy'),
('JOURNEYMAN', 'nec_code', 'What is the demand factor applied to the first 10 kW of electric range load in a dwelling per NEC Table 220.55?', '80%', '70%', '100%', '8 kW (Column C)', 'D', 'NEC Table 220.55 Column C permits 8 kW for a single range rated not more than 12 kW. This is not a simple percentage but a specific value.', 'NEC Table 220.55', 'hard'),
('JOURNEYMAN', 'transformers', 'A 75 kVA, 480/208-120 V three-phase transformer has a secondary full-load current of approximately:', '104 A', '156 A', '208 A', '90 A', 'C', 'I = kVA / (sqrt(3) x V) = 75,000 / (1.732 x 208) = 208.2 A.', 'Transformer calculations', 'medium'),
('JOURNEYMAN', 'grounding', 'Per NEC 250.52(A)(1), a metal underground water pipe must be at least how many feet in contact with earth to serve as a grounding electrode?', '5 feet', '8 feet', '10 feet', '20 feet', 'C', 'NEC 250.52(A)(1) requires at least 10 feet of metal underground water pipe in direct contact with the earth.', 'NEC 250.52(A)(1)', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 408.36, the total load on a panelboard must not exceed what percentage of its bus rating in a commercial installation?', '80%', '100%', '125%', '90%', 'A', 'NEC 408.36 combined with 210.20(A) limits panelboard continuous loads to 80% of the bus bar rating (unless the breaker and bus are listed for 100%).', 'NEC 408.36 / 210.20(A)', 'medium'),
('JOURNEYMAN', 'motors_drives', 'A motor nameplate reads FLA 28 A. Per NEC Table 430.250, the FLC listed for that HP and voltage is 27 A. For sizing branch circuit conductors and OCPD, you must use:', 'The nameplate FLA of 28 A', 'The NEC Table 430.250 FLC of 27 A', 'The average of the two values', 'The larger of the two values', 'B', 'NEC 430.6(A)(1) requires using the FLC from NEC Table 430.250 (not the nameplate FLA) for sizing branch circuit conductors and OCPD.', 'NEC 430.6(A)(1)', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 300.4(A)(1), when NM cable passes through a bored hole in wood framing, the edge of the hole must be at least how far from the nearest edge of the stud?', '1 inch', '1-1/4 inches', '1-1/2 inches', '2 inches', 'B', 'NEC 300.4(A)(1) requires bored holes in wood to be at least 1-1/4 inches from the nearest edge, or the cable must be protected by a steel plate.', 'NEC 300.4(A)(1)', 'medium'),
('JOURNEYMAN', 'circuits', 'What is the impedance of a circuit with 30 ohms resistance and 40 ohms inductive reactance?', '50 ohms', '70 ohms', '35 ohms', '10 ohms', 'A', 'Z = sqrt(R^2 + X_L^2) = sqrt(900 + 1600) = sqrt(2500) = 50 ohms.', 'AC circuit theory', 'medium'),
('JOURNEYMAN', 'nec_code', 'Per NEC 250.30(A), a separately derived system (such as a transformer secondary) requires its own:', 'Grounding electrode conductor connection', 'Separate service entrance', 'Transfer switch', 'Main lug panel only', 'A', 'NEC 250.30(A) requires separately derived systems to have a grounding electrode conductor connected to the nearest grounding electrode.', 'NEC 250.30(A)', 'medium'),
('JOURNEYMAN', 'controls', 'What type of overload relay uses a eutectic alloy (solder pot) element?', 'Bimetallic', 'Melting alloy', 'Electronic', 'Magnetic', 'B', 'Melting alloy (solder pot) overload relays use a eutectic alloy that melts at a precise temperature when overcurrent flows through the heater element.', 'Motor control theory', 'easy'),
('JOURNEYMAN', 'nec_code', 'When conduit fill exceeds 40% for more than 2 conductors per NEC Chapter 9, Table 1, what is the maximum permitted fill percentage?', '31%', '40%', '53%', '60%', 'B', 'NEC Chapter 9, Table 1 allows 40% fill for 3 or more conductors. Over 2 wires: 40%. Two conductors: 31%. One conductor: 53%.', 'NEC Chapter 9, Table 1', 'medium'),
('JOURNEYMAN', 'transformers', 'When paralleling two single-phase transformers, they must have the same:', 'kVA rating only', 'Voltage ratio, impedance, and polarity', 'Physical size', 'Manufacturer', 'B', 'Paralleling transformers requires matching voltage ratios, percent impedance, and correct polarity to prevent circulating currents and unequal load sharing.', 'IEEE C57.12.00', 'hard'),
('JOURNEYMAN', 'nec_code', 'NEC 110.14(C)(1) sets terminal temperature ratings. Unless the equipment is listed otherwise, conductors sized 1 AWG and larger must use the _____ column for ampacity.', '60 C', '75 C', '90 C', '105 C', 'B', 'NEC 110.14(C)(1)(b) requires conductors 1 AWG and larger to use the 75 C ampacity column unless all terminations are rated for 90 C.', 'NEC 110.14(C)(1)(b)', 'hard'),
('JOURNEYMAN', 'safety', 'Per NEC 110.26(A)(3), the minimum headroom for working spaces around 480 V equipment is:', '5 feet', '6 feet', '6-1/2 feet', '7 feet', 'C', 'NEC 110.26(A)(3) requires a minimum headroom of 6-1/2 feet or the height of the equipment, whichever is greater.', 'NEC 110.26(A)(3)', 'medium'),

-- ============================================================
-- MASTER — 25 questions
-- ============================================================
('MASTER', 'nec_code', 'Per NEC 220.87, the demand factor method for existing installations allows you to use what percentage of the highest demand in a 12-month period plus the new load?', '100% peak plus new load', '125% of the peak demand reading', '100% of peak demand plus 125% of new load', '100% peak demand plus new load at applicable demand factors', 'D', 'NEC 220.87 allows the use of actual demand data: 100% of the highest 15-minute demand in the preceding 12 months, plus the new load computed per applicable Article 220 demand factors, times 125% for continuous loads.', 'NEC 220.87', 'hard'),
('MASTER', 'circuits', 'A 200 kVA, 480 V three-phase transformer with 5% impedance will have a short circuit current at the secondary of approximately:', '2,406 A', '4,812 A', '8,020 A', '12,030 A', 'B', 'I_FLC = 200,000 / (1.732 x 480) = 240.6 A. I_SC = I_FLC / Z_pu = 240.6 / 0.05 = 4,812 A.', 'Short circuit calculations / IEEE 141', 'hard'),
('MASTER', 'nec_code', 'Per NEC 110.24, service equipment in other than dwelling units must be field-marked with:', 'The installer''s name', 'The available fault current and date of calculation', 'The utility account number', 'The wire size used', 'B', 'NEC 110.24(A) requires the available fault current and the date the calculation was performed to be field-marked on service equipment.', 'NEC 110.24(A)', 'medium'),
('MASTER', 'transformers', 'A delta-wye transformer bank produces what phase shift between primary and secondary?', '0 degrees', '30 degrees', '45 degrees', '90 degrees', 'B', 'A delta-wye (or wye-delta) transformer connection inherently produces a 30-degree phase shift between primary and secondary voltages.', 'IEEE C57.12.00', 'medium'),
('MASTER', 'nec_code', 'Per NEC 695.6, fire pump supply conductors must be sized to carry what percentage of the locked-rotor current of the fire pump motor?', '100%', '115%', '125%', '150%', 'C', 'NEC 695.6(C)(1) requires fire pump supply conductors to have an ampacity of at least 125% of the full-load current of the fire pump motor, and the conductors must be capable of carrying locked-rotor current indefinitely.', 'NEC 695.6(C)(1)', 'hard'),
('MASTER', 'grounding', 'Per NEC 250.102(C), the supply-side bonding jumper for a parallel service with four sets of 500 kcmil conductors per phase must be sized based on:', 'The largest single phase conductor', 'The equivalent area of the parallel conductors per phase', 'A fixed 3/0 AWG minimum', 'NEC Table 250.66', 'B', 'NEC 250.102(C) requires the supply-side bonding jumper to be sized per Table 250.102(C)(1) based on the equivalent cross-sectional area of the largest phase conductor, which is the total area of all parallel conductors per phase.', 'NEC 250.102(C)', 'hard'),
('MASTER', 'controls', 'In a PLC, a normally-closed input device should be programmed as a _____ instruction to maintain fail-safe operation.', 'Normally open (XIC)', 'Normally closed (XIO)', 'Either will work', 'Output energize (OTE)', 'A', 'For fail-safe programming, an NC input device should be programmed as an examine-if-closed (XIC) instruction. If the wire breaks, the input drops, and the XIC goes false, safely de-energizing the output.', 'ISA-S5.1 / PLC programming', 'hard'),
('MASTER', 'nec_code', 'Per NEC 700.12, emergency systems must have power restored within how many seconds of power failure?', '5 seconds', '10 seconds', '30 seconds', '60 seconds', 'B', 'NEC 700.12 requires the alternate source for emergency systems to automatically supply power within 10 seconds of failure of the normal supply.', 'NEC 700.12', 'medium'),
('MASTER', 'circuits', 'The available short circuit current at a 208/120 V panel is 22,000 A symmetrical. All installed breakers must have an interrupting rating of at least:', '10,000 AIC', '14,000 AIC', '22,000 AIC', '42,000 AIC', 'C', 'NEC 110.9 requires equipment intended to interrupt current at fault levels to have an interrupting rating not less than the available fault current: at least 22,000 AIC in this case.', 'NEC 110.9', 'medium'),
('MASTER', 'nec_code', 'NEC 517.13 requires redundant grounding in patient care areas. This means:', 'Two equipment grounding conductors — one through the raceway and one insulated copper within', 'Double the wire size for ground', 'Two ground rods', 'A ground ring only', 'A', 'NEC 517.13 requires both a metal raceway qualifying as an EGC and a separate insulated copper equipment grounding conductor for patient care areas.', 'NEC 517.13', 'hard'),
('MASTER', 'transformers', 'A 500 kVA pad-mounted transformer serving a commercial building has an impedance of 5.75%. The maximum fault current contribution from this transformer alone at the secondary is approximately:', '5,008 A', '8,710 A', '10,042 A', '12,200 A', 'C', 'I_FLC = 500,000 / (1.732 x 480) = 577.4 A (assuming 480V secondary). I_SC = 577.4 / 0.0575 = 10,042 A.', 'Short circuit calculations', 'hard'),
('MASTER', 'nec_code', 'Per NEC 240.86, a series combination rating of circuit breakers is permitted only when:', 'The utility approves', 'The breakers are tested and listed for the specific series combination', 'Any two breakers of the same manufacturer are used', 'The main breaker is larger than the branch', 'B', 'NEC 240.86 allows series-rated combinations only when the breakers are specifically tested, listed, and marked for that combination per the testing lab.', 'NEC 240.86', 'hard'),
('MASTER', 'grounding', 'Per NEC 250.30(A)(1), the system bonding jumper for a separately derived system must be installed at:', 'Any convenient location', 'The source of the separately derived system only (or first disconnect)', 'The main panel only', 'Each subpanel', 'B', 'NEC 250.30(A)(1) requires the system bonding jumper to be installed at the source (transformer) or at the first system disconnecting means, but not both.', 'NEC 250.30(A)(1)', 'hard'),
('MASTER', 'nec_code', 'For a commercial kitchen, NEC 220.56 allows what demand factor for commercial cooking equipment when there are 6 or more units?', '55%', '65%', '70%', '100%', 'B', 'NEC Table 220.56 allows a 65% demand factor when 6 or more commercial cooking appliances are on the same feeder.', 'NEC Table 220.56', 'hard'),
('MASTER', 'circuits', 'Selective coordination per NEC 700.32 for emergency systems requires:', 'All breakers to be the same type', 'OCPDs to be coordinated so a fault is cleared by the nearest upstream device without tripping devices further upstream', 'The use of fuses only', 'Only main breaker protection', 'B', 'NEC 700.32 requires selective coordination so that a fault at any point is isolated by the OCPD closest to the fault without affecting upstream devices, ensuring continuity of emergency power.', 'NEC 700.32', 'hard'),
('MASTER', 'controls', 'In a motor control center, Type B wiring per UL 845 means:', 'No interlocking between units', 'All units can receive power simultaneously even with doors open', 'A separate control transformer for each unit', 'Wiring between units can be field installed without listing', 'A', 'UL 845 Type B wiring does not provide interlocking. Type C provides mechanical interlocking to prevent access to live parts. Type B is the most common for standard motor control centers.', 'UL 845', 'hard'),
('MASTER', 'nec_code', 'Per NEC 310.15(B)(7), the service conductor allowance for a 120/240 V single-phase dwelling unit permits 83% of the service rating for:', '1/0 AWG copper at 150 A', '2/0 AWG copper at 175 A', 'Both A and B are applications of this section', '4/0 AWG at 200 A', 'C', 'NEC 310.15(B)(7) provides special ampacity allowances for dwelling unit service and feeder conductors, permitting smaller conductors than standard table values (e.g., 2/0 Cu for 200 A is replaced by specific table listings).', 'NEC 310.15(B)(7)', 'hard'),
('MASTER', 'nec_code', 'Per NEC 501.10(A), in a Class I, Division 1 hazardous location, which wiring method is permitted?', 'NM cable', 'Rigid metal conduit with listed fittings', 'MC cable (standard)', 'Surface metal raceway', 'B', 'NEC 501.10(A) permits threaded rigid metal conduit, threaded steel IMC, and Type MI cable in Class I, Division 1 locations. All fittings must be listed for the location.', 'NEC 501.10(A)', 'medium'),
('MASTER', 'transformers', 'An open-delta transformer bank using two single-phase transformers each rated 100 kVA can supply a maximum three-phase load of:', '100 kVA', '141 kVA', '173 kVA', '200 kVA', 'C', 'An open-delta bank delivers 86.6% of the capacity of a full delta bank: 2 x 100 x 0.866 = 173.2 kVA (equivalent to sqrt(3) x single transformer rating).', 'Transformer theory / IEEE C57', 'hard'),
('MASTER', 'motors_drives', 'A 460 V, 3-phase, 100 HP motor has an NEC Table 430.250 FLC of 124 A. The minimum size of the motor disconnecting means per NEC 430.110 must be rated at least:', '124 A', '155 A', '175 A', '200 A', 'B', 'NEC 430.110(A) requires the motor disconnect to be rated at least 115% of the motor FLC: 124 x 1.15 = 142.6 A. The next standard switch size is 200 A, but a circuit breaker rated at 155 A or the next standard size is acceptable.', 'NEC 430.110(A)', 'hard'),
('MASTER', 'nec_code', 'Per NEC 408.36(A), each panelboard must be individually protected on the supply side by overcurrent devices having a rating not greater than:', 'The panelboard bus rating', '80% of the bus rating', '125% of the bus rating', 'The sum of all branch breaker ratings', 'A', 'NEC 408.36(A) requires each panelboard to be protected by an overcurrent device having a rating not greater than the panelboard bus rating.', 'NEC 408.36(A)', 'medium'),
('MASTER', 'circuits', 'To correct a power factor from 0.75 to 0.95 on a 480 V, 3-phase, 200 kW load, the required kVAR of capacitors is approximately:', '75 kVAR', '95 kVAR', '108 kVAR', '120 kVAR', 'C', 'kVAR = kW x (tan(arccos(0.75)) - tan(arccos(0.95))) = 200 x (0.8819 - 0.3287) = 200 x 0.5532 = 110.6 kVAR, approximately 108 kVAR using standard table values.', 'Power factor correction theory', 'hard'),
('MASTER', 'controls', 'In an industrial control panel rated per UL 508A, the short circuit current rating (SCCR) is determined by:', 'The highest rated component', 'The lowest rated component in the power circuit', 'The average of all component ratings', 'The panel enclosure type', 'B', 'Per UL 508A, the SCCR of an industrial control panel is limited by the lowest-rated component in the power circuit (weakest link method), unless listed series combination ratings apply.', 'UL 508A', 'hard'),

-- ============================================================
-- NFPA_70E — 20 questions
-- ============================================================
('NFPA_70E', 'safety', 'Per NFPA 70E, an arc flash risk assessment must be performed before a worker:', 'Enters the building', 'Approaches exposed energized electrical conductors within the arc flash boundary', 'Leaves the job site', 'Files a permit', 'B', 'NFPA 70E 130.5(A) requires an arc flash risk assessment before any person approaches exposed energized electrical conductors or circuit parts within the arc flash boundary.', 'NFPA 70E 130.5(A)', 'easy'),
('NFPA_70E', 'safety', 'The arc flash boundary is defined as the distance at which the incident energy equals:', '0.5 cal/cm2', '1.2 cal/cm2', '4 cal/cm2', '8 cal/cm2', 'B', 'NFPA 70E 130.5(B)(1) defines the arc flash boundary as the distance where incident energy equals 1.2 cal/cm2, sufficient to cause a second-degree burn.', 'NFPA 70E 130.5(B)(1)', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E Table 130.5(C), arc-rated PPE Category 1 provides protection up to what incident energy level?', '1.2 cal/cm2', '4 cal/cm2', '8 cal/cm2', '12 cal/cm2', 'B', 'NFPA 70E Table 130.5(C) specifies PPE Category 1 at a minimum arc rating of 4 cal/cm2.', 'NFPA 70E Table 130.5(C)', 'easy'),
('NFPA_70E', 'safety', 'PPE Category 2 per NFPA 70E requires an arc-rated minimum of:', '4 cal/cm2', '8 cal/cm2', '12 cal/cm2', '25 cal/cm2', 'B', 'NFPA 70E Table 130.5(C) defines PPE Category 2 as requiring a minimum arc rating of 8 cal/cm2.', 'NFPA 70E Table 130.5(C)', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E 130.5(C), PPE Category 4 (the highest standard category) provides protection up to:', '12 cal/cm2', '25 cal/cm2', '40 cal/cm2', '100 cal/cm2', 'C', 'PPE Category 4 requires a minimum arc rating of 40 cal/cm2. Tasks exceeding 40 cal/cm2 require de-energizing the equipment.', 'NFPA 70E Table 130.5(C)', 'medium'),
('NFPA_70E', 'safety', 'Per NFPA 70E 120.5, an electrically safe work condition requires all of the following EXCEPT:', 'Identify all sources of supply', 'Verify a zero-energy state using a proximity detector only (no contact tester)', 'Apply lockout/tagout devices', 'Test each phase conductor with an adequately rated test instrument', 'B', 'NFPA 70E 120.5(7) requires verification using an adequately rated test instrument (contact tester), not just a proximity detector. The tester must be verified on a known source before and after.', 'NFPA 70E 120.5', 'medium'),
('NFPA_70E', 'safety', 'NFPA 70E defines a "qualified person" as one who has:', 'An electrical license only', 'Skills and knowledge related to the construction and operation of electrical equipment and has received safety training', 'At least 10 years of experience', 'A college degree in electrical engineering', 'B', 'NFPA 70E Article 100 defines a qualified person as one with demonstrated skills and knowledge of construction and operation of equipment and the hazards involved, who has received safety training.', 'NFPA 70E Article 100', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E 130.4, the shock protection approach boundaries include the limited, restricted, and _____ approach boundaries.', 'Arc flash', 'Prohibited', 'Extreme', 'Safe', 'B', 'NFPA 70E 130.4 defines three shock approach boundaries: limited, restricted, and prohibited approach boundaries for shock hazard protection.', 'NFPA 70E 130.4', 'easy'),
('NFPA_70E', 'safety', 'The restricted approach boundary for exposed 480 V conductors per NFPA 70E Table 130.4(E)(a) is:', '1 foot', '3.5 feet', '5 feet', '10 feet', 'A', 'NFPA 70E Table 130.4(E)(a) lists the restricted approach boundary for 301-750 V as 1 foot (12 inches) for movable conductors.', 'NFPA 70E Table 130.4(E)(a)', 'medium'),
('NFPA_70E', 'safety', 'An energized electrical work permit (EEWP) per NFPA 70E 130.2(B) must include all of the following EXCEPT:', 'Description of the circuit and equipment', 'Justification for why work must be done energized', 'The worker''s home address', 'Shock and arc flash risk assessment results', 'C', 'NFPA 70E 130.2(B)(2) lists required EEWP content: circuit description, justification for energized work, risk assessment results, safe work practices, PPE requirements, and more. A worker''s home address is not required.', 'NFPA 70E 130.2(B)(2)', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E 110.2(D)(1), electrical safety training must be provided at intervals not exceeding:', '1 year', '3 years', '5 years', 'No retraining required', 'B', 'NFPA 70E 110.2(D)(1) requires retraining at intervals not exceeding 3 years. More frequent training is required if task assignments change or inspections reveal deficiencies.', 'NFPA 70E 110.2(D)(1)', 'medium'),
('NFPA_70E', 'safety', 'When using the incident energy analysis method per NFPA 70E 130.5(B)(1), the working distance used for calculations on a 480 V panelboard is:', '12 inches', '18 inches', '24 inches', '36 inches', 'B', 'IEEE 1584 and NFPA 70E use an 18-inch typical working distance for panelboards and motor control centers in arc flash calculations.', 'IEEE 1584 / NFPA 70E 130.5(B)(1)', 'medium'),
('NFPA_70E', 'safety', 'Per NFPA 70E, barricades and attendants are required when:', 'Working near water', 'The arc flash boundary extends into areas accessible to unqualified persons', 'The voltage exceeds 1000 V', 'More than two workers are present', 'B', 'NFPA 70E 130.7(E)(1) requires barricades or attendants when the arc flash boundary or shock protection boundaries extend into areas where unqualified persons could be exposed.', 'NFPA 70E 130.7(E)(1)', 'medium'),
('NFPA_70E', 'safety', 'Which IEEE standard provides the calculation method most commonly referenced for arc flash incident energy analysis?', 'IEEE 141', 'IEEE 1584', 'IEEE 519', 'IEEE C57.12', 'B', 'IEEE 1584 (Guide for Performing Arc Flash Hazard Calculations) is the industry standard method referenced by NFPA 70E for calculating arc flash incident energy.', 'IEEE 1584', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E, rubber insulating gloves rated Class 00 are tested and rated for a maximum use voltage of:', '500 V AC', '1,000 V AC', '7,500 V AC', '250 V AC', 'A', 'ASTM D120 / NFPA 70E: Class 00 rubber insulating gloves are rated for maximum use voltage of 500 V AC.', 'ASTM D120 / NFPA 70E Table 130.7(C)(7)(a)', 'medium'),
('NFPA_70E', 'safety', 'Lockout/tagout per NFPA 70E 120.5 requires that the lockout device be applied by:', 'The supervisor only', 'Each individual worker exposed to the hazard (individual employee control)', 'The building owner', 'Any available worker', 'B', 'NFPA 70E 120.5 requires individual employee control — each worker exposed to the electrical hazard must apply their own lock and tag.', 'NFPA 70E 120.5', 'easy'),
('NFPA_70E', 'safety', 'An arc flash label on equipment must include all of the following EXCEPT:', 'Available incident energy or PPE category', 'Arc flash boundary', 'Equipment cost', 'Voltage rating', 'C', 'NFPA 70E 130.5(H) requires labels showing incident energy or PPE category, arc flash boundary, and other safety info. Equipment cost is not required.', 'NFPA 70E 130.5(H)', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E, the term "incident energy" is defined as the amount of thermal energy at a specified distance from an arc fault, measured in:', 'BTU per hour', 'Calories per square centimeter (cal/cm2)', 'Watts per square meter', 'Joules per second', 'B', 'NFPA 70E defines incident energy in calories per square centimeter (cal/cm2) at a specified working distance from the arc source.', 'NFPA 70E Article 100', 'easy'),
('NFPA_70E', 'safety', 'Per NFPA 70E 130.7(C)(1), when an arc flash PPE category method is used and the task is not listed in the tables, the worker must:', 'Wear Category 4 PPE automatically', 'Use the incident energy analysis method instead', 'Refuse to perform the task', 'Wear no PPE since it is not listed', 'B', 'If a task is not listed in the NFPA 70E arc flash PPE category tables, the incident energy analysis method per 130.5(B)(1) must be used to determine proper PPE.', 'NFPA 70E 130.5(B)(1)', 'medium'),
('NFPA_70E', 'safety', 'NFPA 70E requires that when an incident energy analysis yields a result exceeding 40 cal/cm2, the worker must:', 'Wear additional layers of PPE', 'Not perform the task while the equipment is energized', 'Use a face shield only', 'Work faster to reduce exposure', 'B', 'NFPA 70E prohibits energized work when incident energy exceeds 40 cal/cm2. Equipment must be de-energized and an electrically safe work condition established.', 'NFPA 70E 130.5(B)(1)', 'medium');
