-- 038_seed_pipepal_cert_questions.sql
-- Cert prep question bank for PipePal (plumbing/pipefitting): ~80 questions
-- ~20 per cert level: APPRENTICE, JOURNEYMAN, MASTER, MEDICAL_GAS

INSERT INTO pipepal.cert_prep_questions (cert_level, category, question, option_a, option_b, option_c, option_d, correct_answer, explanation, code_reference, difficulty) VALUES

-- ============================================================
-- APPRENTICE — 20 questions
-- ============================================================
('APPRENTICE', 'code_compliance', 'According to the IPC, what is the minimum size for a building sewer?', '2 inches', '3 inches', '4 inches', '6 inches', 'B', 'The IPC requires a minimum 3-inch building sewer. Some jurisdictions using UPC may require 4 inches, but the IPC standard is 3 inches.', 'IPC 703.1', 'easy'),
('APPRENTICE', 'drainage', 'What is the minimum slope for a 4-inch horizontal drain pipe?', '1/16 inch per foot', '1/8 inch per foot', '1/4 inch per foot', '1/2 inch per foot', 'B', 'Horizontal drain pipes 3 inches and larger require a minimum slope of 1/8 inch per foot. Pipes smaller than 3 inches require 1/4 inch per foot.', 'IPC 704.1', 'easy'),
('APPRENTICE', 'drainage', 'What is the maximum length of a trap arm for a 1-1/2 inch fixture drain?', '3 feet 6 inches', '5 feet', '6 feet', '8 feet', 'C', 'The maximum trap arm length for a 1-1/2 inch pipe is 6 feet per the IPC. This ensures the trap seal is maintained by staying within the developed length limit.', 'IPC 909.1', 'medium'),
('APPRENTICE', 'water_supply', 'What is the standard residential water heater temperature setting recommended to prevent scalding?', '100°F', '120°F', '140°F', '160°F', 'B', 'A maximum of 120°F is recommended to prevent scalding while still providing adequate hot water. Higher temperatures increase burn risk, especially for children and elderly.', 'IPC 501.2', 'easy'),
('APPRENTICE', 'fixtures', 'How many fixture units does a standard bathroom lavatory have?', '1 DFU', '2 DFU', '3 DFU', '4 DFU', 'A', 'A lavatory has a drainage fixture unit (DFU) value of 1. This is one of the most basic fixture unit values to memorize for sizing drain piping.', 'IPC Table 709.1', 'easy'),
('APPRENTICE', 'safety', 'What is the maximum depth of a trench that can be dug without shoring or sloping per OSHA?', '3 feet', '4 feet', '5 feet', '6 feet', 'C', 'OSHA requires protective systems (sloping, shoring, or shielding) for all trenches 5 feet or deeper, unless the excavation is in stable rock.', 'OSHA 1926.652', 'easy'),
('APPRENTICE', 'drainage', 'A P-trap must maintain a minimum water seal depth of:', '1 inch', '2 inches', '3 inches', '4 inches', 'B', 'The IPC requires a minimum 2-inch water seal in all traps. The maximum seal depth is 4 inches to prevent excessive siphoning resistance.', 'IPC 1002.1', 'easy'),
('APPRENTICE', 'water_supply', 'What type of fitting is prohibited for use underground on water supply piping?', 'Compression fitting', 'Soldered joint', 'Push-fit coupling', 'Rubber banded coupling', 'A', 'Compression fittings are generally not approved for underground or concealed water piping because they can loosen over time and are not accessible for maintenance.', 'IPC 605.3', 'medium'),
('APPRENTICE', 'code_compliance', 'What test pressure is required for a DWV rough-in air test?', '3 psi', '5 psi', '10 psi', '15 psi', 'B', 'The IPC requires a 5 psi air test for DWV systems, held for 15 minutes with no pressure drop. Air tests are an alternative to the water test.', 'IPC 312.3', 'easy'),
('APPRENTICE', 'drainage', 'Which type of fitting is required for a horizontal-to-vertical change of direction in DWV piping?', 'Short sweep 90', 'Sanitary tee', 'Long sweep 90 or two 45s', 'Wye fitting only', 'B', 'A sanitary tee is used for horizontal-to-vertical connections where the flow enters from the horizontal branch into a vertical stack.', 'IPC 706.3', 'medium'),
('APPRENTICE', 'fixtures', 'What is the minimum size vent required for a water closet?', '1-1/4 inches', '1-1/2 inches', '2 inches', '3 inches', 'C', 'A water closet requires a minimum 2-inch individual vent per the IPC vent sizing tables.', 'IPC Table 916.1', 'easy'),
('APPRENTICE', 'water_supply', 'Copper water tubing type L is identified by what color marking?', 'Red', 'Blue', 'Green', 'Yellow', 'B', 'Type L copper is marked blue. Type M is red, Type K is green, and DWV is yellow. Type L is the most common for interior water supply.', 'ASTM B88', 'easy'),
('APPRENTICE', 'safety', 'When soldering copper pipe, the maximum lead content allowed in solder for potable water systems is:', '0%', '0.2%', '5%', '50%', 'B', 'The Safe Drinking Water Act requires lead-free solder (maximum 0.2% lead) for all potable water piping. Tin-antimony or tin-silver solders are used.', 'IPC 605.15', 'easy'),
('APPRENTICE', 'drainage', 'A combination wye and 1/8 bend is used for:', 'Connecting a horizontal branch to a horizontal drain', 'Connecting a vent to a stack', 'Cleanout access only', 'Water supply connections', 'A', 'A combo (wye + 1/8 bend) is the standard fitting for connecting a horizontal branch to a horizontal drain, allowing proper flow direction.', 'IPC 706.3', 'easy'),
('APPRENTICE', 'code_compliance', 'How far above a finished floor must a cleanout be accessible?', '12 inches', '18 inches', 'Must be at floor level or within 12 inches', 'No height requirement', 'C', 'Cleanouts must be accessible and installed so the cover is at or within 12 inches of the finished floor or grade. They need 18 inches of clearance for rodding.', 'IPC 708.3', 'medium'),
('APPRENTICE', 'water_supply', 'What device prevents contaminated water from flowing back into the potable supply?', 'Check valve', 'Backflow preventer', 'Pressure reducing valve', 'Expansion tank', 'B', 'A backflow preventer (such as RPZ, DCVA, or AVB) is specifically designed to prevent contaminated water from reverse-flowing into the potable supply.', 'IPC 608.1', 'easy'),
('APPRENTICE', 'fixtures', 'What is the drainage fixture unit value for a standard bathtub?', '1 DFU', '2 DFU', '3 DFU', '4 DFU', 'B', 'A standard bathtub has a DFU value of 2 per the IPC fixture unit tables.', 'IPC Table 709.1', 'easy'),
('APPRENTICE', 'safety', 'What type of PPE is required when cutting cast iron pipe?', 'Gloves only', 'Safety glasses and hearing protection', 'Hard hat only', 'No special PPE needed', 'B', 'Cutting cast iron generates flying debris and loud noise. Safety glasses (or face shield) and hearing protection are essential, along with gloves.', 'OSHA 1926.102', 'easy'),
('APPRENTICE', 'drainage', 'What is the purpose of a vent in a DWV system?', 'To drain condensation', 'To equalize air pressure and protect trap seals', 'To increase flow velocity', 'To provide cleanout access', 'B', 'Vents equalize air pressure in the drainage system, preventing siphonage or back pressure from breaking trap seals.', 'IPC 901.2', 'easy'),
('APPRENTICE', 'code_compliance', 'The water test for a DWV system requires filling the system to a minimum height of:', '5 feet', '10 feet', 'The full height of the system', '3 feet above the highest fitting', 'B', 'The IPC requires the DWV system to be filled with water to a height of not less than 10 feet, or to the highest point of the system if less than 10 feet.', 'IPC 312.2', 'medium'),

-- ============================================================
-- JOURNEYMAN — 20 questions
-- ============================================================
('JOURNEYMAN', 'code_compliance', 'Per the IPC, what is the maximum number of drainage fixture units allowed on a 3-inch horizontal branch?', '12 DFU', '20 DFU', '35 DFU', '42 DFU', 'B', 'A 3-inch horizontal branch is limited to 20 DFU per the IPC drainage fixture unit tables.', 'IPC Table 710.1(2)', 'medium'),
('JOURNEYMAN', 'water_supply', 'An RPZ (Reduced Pressure Zone) backflow preventer is required for:', 'Low-hazard cross-connections only', 'High-hazard cross-connections where backpressure may occur', 'Residential hose bibbs only', 'Fire sprinkler systems only', 'B', 'RPZ assemblies protect against both backsiphonage and backpressure in high-hazard situations (chemical injection, boiler feeds, etc.).', 'IPC 608.16.2', 'medium'),
('JOURNEYMAN', 'gas_piping', 'What is the standard test pressure for a natural gas piping system per the IPC?', '3 psi for 10 minutes', '10 psi for 10 minutes', '15 psi for 30 minutes', '1.5 times working pressure for 15 minutes', 'A', 'The IPC requires a 3 psi air test for 10 minutes with no perceptible drop on natural gas systems operating at less than 14 inches water column.', 'IPC 406.4', 'medium'),
('JOURNEYMAN', 'drainage', 'What is the maximum distance from the crown weir of a trap to the vent for a 2-inch trap arm?', '5 feet', '6 feet', '8 feet', '10 feet', 'C', 'The maximum developed length of a 2-inch trap arm is 8 feet per the IPC. Exceeding this distance risks losing the trap seal.', 'IPC Table 909.1', 'medium'),
('JOURNEYMAN', 'water_supply', 'When sizing water supply piping, friction loss is most affected by:', 'Pipe material only', 'Flow velocity and pipe diameter', 'Water temperature only', 'Time of day', 'B', 'Friction loss is primarily determined by flow velocity and pipe diameter. Smaller pipes and higher velocities create exponentially greater friction losses.', 'IPC Chapter 6', 'medium'),
('JOURNEYMAN', 'gas_piping', 'What pipe material is NOT approved for interior natural gas piping?', 'Black steel', 'Galvanized steel', 'CSST (corrugated stainless steel tubing)', 'PVC', 'D', 'PVC is never approved for interior gas piping. Approved materials include black steel, galvanized steel, copper (in some jurisdictions), and CSST.', 'IPC 403.4', 'easy'),
('JOURNEYMAN', 'code_compliance', 'A relief valve discharge pipe for a water heater must terminate:', 'Into the sanitary drain', 'Within 6 inches of the floor or to an approved indirect waste receptor', 'Outside the building only', 'Into the vent stack', 'B', 'The T&P relief valve discharge must terminate within 6 inches of the floor or outside, discharging in a manner visible to occupants and not into the drainage system directly.', 'IPC 504.6', 'medium'),
('JOURNEYMAN', 'drainage', 'What fitting is prohibited when making a horizontal-to-horizontal connection in the direction of flow?', 'Wye', 'Sanitary tee', 'Combination wye and 1/8 bend', 'Long sweep 90', 'B', 'A sanitary tee shall not be used for horizontal-to-horizontal changes of direction. It would cause turbulence and blockages. Use a wye or combo fitting instead.', 'IPC 706.3', 'medium'),
('JOURNEYMAN', 'water_supply', 'What is the maximum water velocity recommended in water supply piping to control noise and erosion?', '4 fps', '6 fps', '8 fps', '10 fps', 'C', 'The IPC recommends a maximum velocity of 8 feet per second in water supply piping to prevent water hammer, noise, and pipe erosion.', 'IPC 604.3', 'medium'),
('JOURNEYMAN', 'gas_piping', 'When sizing gas piping, the demand is measured in:', 'Gallons per minute', 'BTU per hour', 'Cubic feet per second', 'Pounds per square inch', 'B', 'Gas pipe sizing is based on total BTU per hour demand of all connected appliances, combined with pipe length, specific gravity, and available pressure drop.', 'IPC 402.4', 'easy'),
('JOURNEYMAN', 'fixtures', 'What is the minimum air gap required for an indirect waste receptor for a commercial dishwasher?', 'Equal to the pipe diameter', 'Twice the effective opening of the drain', '1 inch', '6 inches', 'B', 'The air gap for an indirect waste must be at least twice the effective opening of the drain being served, but not less than 1 inch.', 'IPC 801.2', 'hard'),
('JOURNEYMAN', 'safety', 'Before entering a trench deeper than 4 feet, OSHA requires:', 'A ladder within 25 feet of workers', 'Atmospheric testing for hazardous gases', 'Both A and B', 'Only a hard hat', 'C', 'OSHA requires a means of egress (ladder, steps, or ramp) within 25 feet of workers in trenches 4+ feet deep, and atmospheric testing when hazardous conditions may exist.', 'OSHA 1926.651', 'medium'),
('JOURNEYMAN', 'drainage', 'A wet vent serves as both a vent and a:', 'Water supply', 'Drain for upstream fixtures', 'Gas vent', 'Relief pipe', 'B', 'A wet vent is a vent pipe that also receives the discharge of fixtures upstream. It must be sized for both venting and drainage functions.', 'IPC 911.1', 'medium'),
('JOURNEYMAN', 'water_supply', 'Expansion tanks are required on water heaters when:', 'The system has a check valve or PRV creating a closed system', 'The water heater exceeds 50 gallons', 'The building is over 3 stories', 'Always', 'A', 'When a check valve, backflow preventer, or pressure reducing valve creates a closed system, thermal expansion has nowhere to go. An expansion tank absorbs the increased volume.', 'IPC 607.3.2', 'medium'),
('JOURNEYMAN', 'gas_piping', 'CSST (corrugated stainless steel tubing) for gas piping must be:', 'Bonded to the grounding electrode system', 'Wrapped in insulation', 'Installed only outdoors', 'Painted yellow', 'A', 'CSST must be bonded to the building grounding electrode system to protect against damage from lightning-induced surges per NFPA 54 and manufacturer instructions.', 'NFPA 54 §7.13', 'medium'),
('JOURNEYMAN', 'code_compliance', 'How many water closets can be connected to a single 3-inch horizontal branch?', '1', '2', '3', '4', 'C', 'A 3-inch horizontal branch can serve up to 3 water closets (at 4 DFU each = 12 DFU, within the 20 DFU limit for a 3-inch branch), though total DFU from all fixtures must not exceed the table limit.', 'IPC Table 710.1(2)', 'hard'),
('JOURNEYMAN', 'drainage', 'The minimum size of a horizontal wet vent serving a bathroom group is:', '1-1/2 inches', '2 inches', '3 inches', '4 inches', 'B', 'The minimum wet vent size is 2 inches for a bathroom group. It must be sized for the total DFU of all fixtures it serves for both drain and vent functions.', 'IPC 911.2', 'medium'),
('JOURNEYMAN', 'water_supply', 'A water hammer arrestor is sized based on:', 'Pipe length', 'Number of fixture units served', 'Water pressure only', 'Water temperature', 'B', 'Water hammer arrestors are sized according to the number of fixture units served, per ASSE 1010 and PDI WH-201.', 'ASSE 1010', 'medium'),
('JOURNEYMAN', 'safety', 'Hot work permits for soldering or brazing near combustibles require a fire watch for how long after work is complete?', '15 minutes', '30 minutes', '60 minutes', '90 minutes', 'B', 'A fire watch must be maintained for at least 30 minutes after all hot work is completed to ensure no smoldering or delayed ignition occurs.', 'OSHA 1926.352', 'medium'),
('JOURNEYMAN', 'fixtures', 'The minimum number of plumbing fixtures for an office building with 30 employees (15 male, 15 female) is determined by:', 'The architect', 'The plumber', 'IPC Table 403.1 based on occupancy type and count', 'The building owner preference', 'C', 'The IPC provides minimum fixture counts in Table 403.1 based on occupancy classification and number of occupants.', 'IPC Table 403.1', 'easy'),

-- ============================================================
-- MASTER — 20 questions
-- ============================================================
('MASTER', 'code_compliance', 'A master plumber designing a system with 250 total DFU needs a building drain of at least:', '3 inches', '4 inches', '5 inches', '6 inches', 'C', 'Per the IPC building drain sizing table, 250 DFU at 1/8 inch per foot slope requires a minimum 5-inch drain. A 4-inch drain at 1/8 slope handles only 216 DFU.', 'IPC Table 710.1(1)', 'hard'),
('MASTER', 'water_supply', 'When calculating peak demand for a building water supply, the most widely used method is:', 'Straight addition of all fixture demands', 'The Hunter Curve (fixture unit method)', 'Average daily use divided by hours', 'Tank capacity method', 'B', 'The Hunter Curve (probability-based fixture unit method) accounts for the fact that not all fixtures operate simultaneously, yielding realistic peak GPM demand.', 'IPC Chapter 6', 'medium'),
('MASTER', 'code_compliance', 'A plumbing system serving a building with both domestic and fire suppression water must have:', 'Separate water services always', 'A combined service with a backflow preventer on the fire line', 'No special requirements', 'Only a check valve', 'B', 'Fire sprinkler connections to a domestic water supply require a backflow preventer (typically DCVA or RPZ) to protect the potable supply from stagnant fire line water.', 'IPC 608.16.4', 'medium'),
('MASTER', 'drainage', 'Suds pressure zones in a drainage stack occur when:', 'The stack is oversized', 'A horizontal offset receives discharge from upper floors at a point where suds accumulate', 'The building is under 3 stories', 'Only with garbage disposals', 'B', 'Suds pressure zones form where horizontal branches connect to the stack within specific floors of the base. Detergent-laden water creates foam that can blow trap seals.', 'IPC 711.2', 'hard'),
('MASTER', 'gas_piping', 'For a gas system with a total demand of 500,000 BTU/h and a longest run of 200 feet, the minimum pipe size for natural gas at 0.5" WC pressure drop is approximately:', '1 inch', '1-1/4 inches', '1-1/2 inches', '2 inches', 'C', 'Using IPC gas pipe sizing tables for natural gas at 0.5" WC drop over 200 feet with 500 CFH demand, a 1-1/2 inch pipe is required.', 'IPC Table 402.4', 'hard'),
('MASTER', 'water_supply', 'A booster pump system for a high-rise building must be designed with:', 'A single pump for all floors', 'Redundant pumps, pressure tanks, and zone pressure regulation', 'Only gravity tanks', 'No specific requirements beyond the pump', 'B', 'High-rise booster systems require redundant pumps (lead/lag/standby), pressure tanks for surge protection, and zone PRVs to keep pressure below 80 psi at each floor.', 'IPC 606.5', 'hard'),
('MASTER', 'code_compliance', 'Interceptors (grease traps) are sized based on:', 'Number of sinks only', 'Flow rate in GPM and retention time', 'Building square footage', 'Number of employees', 'B', 'Grease interceptors are sized by determining GPM flow from connected fixtures and required retention time per local code and PDI G-101.', 'IPC 1003.3', 'medium'),
('MASTER', 'drainage', 'When a building drain changes direction horizontally, and the total DFU exceeds the branch limit, you must:', 'Use a larger fitting', 'Treat the downstream section as a building drain and re-size', 'Add a vent only', 'Reduce the pipe size', 'B', 'A horizontal offset in a building drain creates a new section that must be sized as a building drain based on the total DFU flowing through it.', 'IPC 711.1', 'hard'),
('MASTER', 'gas_piping', 'LP gas piping differs from natural gas piping because:', 'LP gas is lighter than air', 'LP gas has a higher specific gravity (1.52 vs 0.60) requiring larger pipe sizes and special ventilation', 'LP gas requires no regulator', 'There is no difference', 'B', 'LP gas is heavier than air (specific gravity 1.52) and has a higher BTU content per cubic foot. This affects pipe sizing and requires that LP gas piping never terminate in basements or low areas.', 'IPC 402.4', 'medium'),
('MASTER', 'water_supply', 'Legionella prevention in a domestic hot water system requires:', 'Water temperature below 100°F', 'Maintaining storage at 140°F and distribution at 120°F minimum with mixing valves', 'Using only copper piping', 'Monthly system draining', 'B', 'Legionella bacteria thrive between 77-113°F. Storing water at 140°F and using thermostatic mixing valves to deliver 120°F at fixtures controls Legionella while preventing scalding.', 'ASHRAE 188', 'hard'),
('MASTER', 'safety', 'A master plumber supervising a project must ensure confined space entry programs include:', 'Entry permits, atmospheric monitoring, attendant, and rescue plan', 'Only hard hats', 'Just a buddy system', 'Written permission from the owner', 'A', 'OSHA 1910.146 requires a comprehensive confined space program: entry permits, continuous atmospheric monitoring, a trained attendant, communication, and a rescue plan.', 'OSHA 1910.146', 'medium'),
('MASTER', 'code_compliance', 'Per IPC, storm drainage sizing is based on:', 'Building square footage only', 'Rainfall rate in inches per hour and roof area', 'Number of downspouts', 'Gutter size only', 'B', 'Storm drain sizing uses the local rainfall rate (inches per hour) and the projected roof area (including vertical surfaces receiving wind-driven rain).', 'IPC Table 1106.2', 'medium'),
('MASTER', 'fixtures', 'A healthcare facility with 100 beds requires fixture counts determined by:', 'Standard office occupancy tables', 'IPC Table 403.1 healthcare/institutional occupancy classification', 'The same as residential', 'Architect discretion only', 'B', 'Healthcare facilities use the institutional occupancy section of IPC Table 403.1, which specifies fixture ratios per bed count and staff count separately.', 'IPC Table 403.1', 'medium'),
('MASTER', 'drainage', 'Stack sizing for a 20-story building with 600 total DFU requires a minimum stack size of:', '4 inches', '5 inches', '6 inches', '8 inches', 'C', 'Per IPC Table 710.1(2), a drainage stack more than 3 stories with 600 DFU requires a 6-inch stack. A 5-inch stack handles only 428 DFU for stacks over 3 stories.', 'IPC Table 710.1(2)', 'hard'),
('MASTER', 'water_supply', 'Cross-connection control programs require annual testing of:', 'All backflow preventers regardless of type', 'Only RPZ assemblies', 'Only DCVA assemblies', 'No annual testing is required', 'A', 'All testable backflow prevention assemblies (RPZ, DCVA, PVB, SVB) must be tested annually by a certified tester and records maintained.', 'IPC 312.10', 'medium'),
('MASTER', 'gas_piping', 'A gas piping system serving multiple appliances must be sized using:', 'Only the largest appliance demand', 'The sum of all connected appliance BTU ratings on each pipe section', 'Average demand only', 'Peak hour gas use only', 'B', 'Each section of gas pipe is sized based on the total BTU demand of all appliances downstream of that section, using the longest length from the meter.', 'IPC 402.4', 'medium'),
('MASTER', 'code_compliance', 'When is a plumbing permit NOT required?', 'Replacing a faucet or valve with the same type and size', 'Adding a new bathroom', 'Replacing a water heater', 'Running new gas piping', 'A', 'Minor repairs and replacements (like-for-like faucet, valve, or fixture replacement) typically do not require a permit. New installations and water heaters do.', 'IPC 106.2', 'easy'),
('MASTER', 'drainage', 'An ejector pump serving a below-grade bathroom must have:', 'A sealed and vented basin with alarm', 'An open sump', 'No vent required', 'Only a check valve', 'A', 'Sewage ejector pumps require a sealed, gas-tight basin, a vent to the exterior, a check valve on the discharge, and an alarm to signal pump failure.', 'IPC 712.1', 'medium'),
('MASTER', 'water_supply', 'Thermal expansion in a closed plumbing system can increase pressure by approximately:', '10-20 psi', '50-100 psi', '100-200 psi or more', '5 psi maximum', 'C', 'In a closed system, heating water from 50°F to 140°F can raise pressure by 150 psi or more if no expansion device is installed, potentially causing T&P valve discharge or pipe failure.', 'IPC 607.3.2', 'hard'),
('MASTER', 'safety', 'A master plumber is legally responsible for:', 'Only their own work', 'All plumbing work performed under their license, including apprentices and journeymen', 'Only code compliance', 'Only permit applications', 'B', 'The master plumber license holder is legally responsible for all work performed under that license, including supervision, code compliance, and permit accuracy.', 'IPC 106.1', 'easy'),

-- ============================================================
-- MEDICAL_GAS — 20 questions
-- ============================================================
('MEDICAL_GAS', 'medical_gas', 'What ASSE standard governs the installation of medical gas systems?', 'ASSE 1010', 'ASSE 6010', 'ASSE 1060', 'ASSE 5000', 'B', 'ASSE 6010 (Professional Qualifications Standard for Medical Gas Systems Installers) governs the qualification of personnel installing medical gas and vacuum systems.', 'ASSE 6010', 'easy'),
('MEDICAL_GAS', 'medical_gas', 'What standard governs the inspection and testing of medical gas systems?', 'ASSE 6010', 'ASSE 6020', 'ASSE 6030', 'NFPA 55', 'B', 'ASSE 6020 covers the qualification of medical gas systems inspectors who verify and test completed installations.', 'ASSE 6020', 'easy'),
('MEDICAL_GAS', 'medical_gas', 'Medical gas piping must be joined by:', 'Soldering with lead-free solder', 'Brazing with BCuP series alloy in a nitrogen-purged environment', 'Threaded connections', 'Compression fittings', 'B', 'Medical gas copper piping must be brazed using BCuP-5 (or equivalent) silver brazing alloy with continuous nitrogen purge to prevent internal oxidation.', 'NFPA 99 §5.1.10', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'During brazing of medical gas piping, nitrogen purge flow rate should be:', 'As high as possible', 'Sufficient to prevent oxidation but not so high as to cool the joint — typically 10-20 SCFH', 'Not required', 'Only during testing', 'B', 'Nitrogen purge during brazing must be a slow, continuous flow (10-20 SCFH typical) to displace oxygen without cooling the braze joint. The purge must continue until the joint cools below oxidation temperature.', 'NFPA 99 §5.1.10.3', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'What color is the designated marker for medical oxygen piping?', 'Yellow', 'Green', 'Blue', 'White', 'B', 'Medical oxygen piping is identified by green labels/markers per CGA C-9. This is critical to prevent cross-connections between different gas systems.', 'CGA C-9', 'easy'),
('MEDICAL_GAS', 'medical_gas', 'What is the initial standing pressure test for a medical gas piping system?', '50 psi for 24 hours', '150 psi for 24 hours', '1.5 times working pressure for 24 hours', '200 psi for 10 minutes', 'B', 'The initial test requires pressurizing the entire system to 150 psi with oil-free, dry nitrogen for 24 hours with no pressure loss.', 'NFPA 99 §5.1.12.2', 'medium'),
('MEDICAL_GAS', 'safety', 'Medical gas cylinder storage rooms require:', 'Ordinary ventilation', 'A minimum of 1 air change per hour, no combustibles, and 1-hour fire-rated construction', 'No special requirements', 'Only a fire extinguisher', 'B', 'Medical gas storage rooms must have 1-hour fire-rated construction, no combustible storage, adequate ventilation, and signage per NFPA 99.', 'NFPA 99 §5.1.3.3', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'Cross-connection in medical gas systems is prevented primarily by:', 'Color coding only', 'Diameter Index Safety System (DISS) and Pin Index Safety System (PISS) connections', 'Labeling', 'Different pipe sizes only', 'B', 'DISS (large cylinders and station outlets) and PISS (small cylinders) use gas-specific non-interchangeable connections to physically prevent cross-connection.', 'CGA V-5', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'After installation, a medical gas system must pass which verification test?', 'Only a pressure test', 'Standing pressure test, cross-connection test, purge test, and particulate test', 'Visual inspection only', 'A flow test only', 'B', 'Complete verification includes standing pressure test (150 psi/24 hr), cross-connection test at each outlet, system purge, particulate test, and gas-specific purity verification.', 'NFPA 99 §5.1.12', 'hard'),
('MEDICAL_GAS', 'medical_gas', 'The cross-connection test for medical gas systems requires:', 'Testing one outlet per zone', 'Pressurizing each gas system individually and verifying no pressure appears at outlets of other gas systems', 'Only a visual check', 'Using soapy water on joints', 'B', 'Each piped gas is pressurized individually while all other systems are at 0 psi. Every outlet of every other gas system must show zero pressure to confirm no cross-connections.', 'NFPA 99 §5.1.12.3.4', 'hard'),
('MEDICAL_GAS', 'medical_gas', 'Medical vacuum systems require what type of pump exhaust?', 'Discharge into the building', 'Discharge to the outdoors away from any air intake', 'Discharge into the sewer', 'No exhaust requirement', 'B', 'Medical vacuum pump exhaust must terminate outdoors, at least 25 feet from any door, window, or air intake to prevent re-entrainment of contaminants.', 'NFPA 99 §5.1.8.3', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'WAGD (Waste Anesthetic Gas Disposal) systems are designed to:', 'Supply anesthetic gases', 'Capture and remove excess anesthetic gases from the breathing zone', 'Filter room air', 'Cool operating rooms', 'B', 'WAGD systems capture waste anesthetic gases (nitrous oxide, sevoflurane, etc.) from patient breathing circuits and exhaust them outdoors to protect healthcare workers.', 'NFPA 99 §5.1.8', 'easy'),
('MEDICAL_GAS', 'medical_gas', 'What copper tubing type is required for medical gas piping?', 'Type M', 'Type K or L, medical gas grade (cleaned and capped)', 'Standard Type L', 'Any copper tubing', 'B', 'Medical gas piping requires Type K or L copper that is specifically cleaned for oxygen service, degreased, and capped at the factory to prevent contamination.', 'NFPA 99 §5.1.10.1', 'medium'),
('MEDICAL_GAS', 'code_compliance', 'Zone valve boxes for medical gas systems must be:', 'Accessible only to maintenance', 'Visible and accessible in the corridor outside the zone they serve', 'Hidden in the ceiling', 'Locked in a mechanical room', 'B', 'Zone valve boxes must be installed in corridor walls or other visible locations outside the area served so they remain accessible during emergencies.', 'NFPA 99 §5.1.4.1', 'medium'),
('MEDICAL_GAS', 'medical_gas', 'The medical air compressor intake must be located:', 'Inside the mechanical room', 'Outdoors, above roof level, away from exhaust vents and loading docks', 'In the basement', 'Adjacent to the vacuum exhaust', 'B', 'Medical air intake must be in a clean outdoor location, above roof level, and at least 25 feet from any exhaust or contamination source.', 'NFPA 99 §5.1.3.5.2', 'medium'),
('MEDICAL_GAS', 'safety', 'Before beginning medical gas installation work, the installer must:', 'Have any plumbing license', 'Hold ASSE 6010 certification or work under direct supervision of an ASSE 6010 installer', 'Complete an online course', 'Only read the NFPA 99 standard', 'B', 'NFPA 99 requires that medical gas installers hold ASSE 6010 certification. Uncertified individuals may assist only under direct, on-site supervision of a certified installer.', 'NFPA 99 §5.1.10', 'easy'),
('MEDICAL_GAS', 'medical_gas', 'Alarm systems for medical gas must include:', 'Master alarms only', 'Master alarms at the security office, area alarms at each zone, and local alarms at the source', 'Only audible alarms', 'No alarms are required', 'B', 'NFPA 99 requires a three-level alarm system: master alarms (24/7 monitoring location), area alarms (at nursing stations for each zone), and local alarms (at source equipment).', 'NFPA 99 §5.1.9', 'hard'),
('MEDICAL_GAS', 'medical_gas', 'Nitrogen NF used in surgical tools operates at:', 'Standard 50 psi like oxygen', '160-200 psi for powering pneumatic surgical instruments', '15 psi', '500 psi', 'B', 'Nitrogen NF (National Formulary) for surgical tools operates at 160-200 psi, significantly higher than standard medical gases, and requires appropriately rated piping and regulators.', 'NFPA 99 §5.1.11', 'hard'),
('MEDICAL_GAS', 'code_compliance', 'Medical gas piping installed in a renovation must be verified by:', 'The installing contractor only', 'A third-party ASSE 6030 verifier independent of the installer', 'The building owner', 'The architect', 'B', 'NFPA 99 requires that verification of medical gas systems be performed by a party who holds ASSE 6030 certification and is not the installer or their direct employee.', 'NFPA 99 §5.1.12.1', 'medium'),
('MEDICAL_GAS', 'safety', 'If a medical gas system modification requires a temporary shutdown, the installer must:', 'Simply close the valve and begin work', 'Coordinate with the facility, notify affected areas, ensure patient safety, and use interim measures', 'Work only at night', 'Post a sign on the valve', 'B', 'Any shutdown of medical gas services requires written coordination with facility management, clinical notification, patient risk assessment, and provision of interim gas supply (portable cylinders) before work begins.', 'NFPA 99 §5.1.14', 'medium');
