-- 039_seed_windpal_cert_questions.sql
-- Cert prep question bank for WindPal (wind turbine): ~80 questions
-- ~20 per cert level: GWO_BST, GWO_BTT, ACP_TECH, SENIOR_TECH

INSERT INTO windpal.cert_prep_questions (cert_level, category, question, option_a, option_b, option_c, option_d, correct_answer, explanation, code_reference, difficulty) VALUES

-- ============================================================
-- GWO_BST (GWO Basic Safety Training) — 20 questions
-- ============================================================
('GWO_BST', 'safety', 'What does GWO stand for?', 'Global Wind Organization', 'General Wind Operations', 'Government Wind Oversight', 'Green Wind Optimization', 'A', 'GWO (Global Wind Organization) is the international body that sets safety training standards for the wind energy industry.', 'GWO BST Standard', 'easy'),
('GWO_BST', 'safety', 'The minimum number of attachment points required when working at heights on a wind turbine is:', '1', '2 (100% tie-off)', '3', 'None if below 10 meters', 'B', 'GWO and OSHA require 100% tie-off with two attachment points so the worker is always connected to an anchor when transferring between systems.', 'GWO WAH Standard', 'easy'),
('GWO_BST', 'safety', 'What is the maximum free-fall distance permitted for a personal fall arrest system?', '3 feet (0.9 m)', '6 feet (1.8 m)', '10 feet (3.0 m)', '12 feet (3.7 m)', 'B', 'OSHA and ANSI Z359 limit free-fall distance to 6 feet (1.8 m) maximum. The total fall distance including deceleration and harness stretch must also be calculated.', 'ANSI Z359.1', 'easy'),
('GWO_BST', 'safety', 'When climbing a wind turbine ladder, you should:', 'Carry tools in your hands for quick access', 'Use a tool bag attached to your harness or hoist tools separately', 'Wear tools on a belt without lanyards', 'Pass tools hand to hand on the ladder', 'B', 'Three points of contact must be maintained while climbing. Tools must be secured in bags or pouches, or hoisted separately to prevent dropped object hazards.', 'GWO BST Standard', 'easy'),
('GWO_BST', 'safety', 'The GWO First Aid module requires technicians to be able to:', 'Perform surgery', 'Provide CPR, treat wounds, and manage a casualty until professional help arrives', 'Only call emergency services', 'Drive an ambulance', 'B', 'GWO First Aid training covers CPR, AED use, wound management, and stabilization of casualties in remote/confined tower environments until emergency services arrive.', 'GWO First Aid Standard', 'easy'),
('GWO_BST', 'safety', 'Fire awareness training for wind turbines focuses on:', 'Fighting all fires regardless of size', 'Prevention, early detection, evacuation procedures, and using portable extinguishers on small fires only', 'Only electrical fires', 'Calling the fire department and waiting', 'B', 'GWO Fire Awareness covers fire prevention, identifying fire risks, evacuation from nacelle/tower, and using extinguishers only on small incipient fires. Large fires require immediate evacuation.', 'GWO Fire Awareness Standard', 'easy'),
('GWO_BST', 'safety', 'Manual handling training for wind turbine technicians emphasizes:', 'Lifting the heaviest loads possible', 'Proper lifting techniques, risk assessment, and using mechanical aids whenever possible', 'Only team lifting', 'Avoiding all manual lifting', 'B', 'GWO Manual Handling covers ergonomic principles, risk assessment of lifting tasks, proper body mechanics, and prioritizing mechanical aids to prevent musculoskeletal injuries.', 'GWO Manual Handling Standard', 'easy'),
('GWO_BST', 'safety', 'What type of harness is required for wind turbine climbing?', 'A standard construction harness', 'A full-body harness rated for fall arrest with front and dorsal attachment points', 'A chest harness only', 'A seat harness used in rock climbing', 'B', 'Wind turbine work requires a full-body fall arrest harness with front D-ring (for ladder climbing devices) and dorsal D-ring (for fall arrest), meeting ANSI Z359.11.', 'ANSI Z359.11', 'easy'),
('GWO_BST', 'safety', 'Before ascending a wind turbine, a technician must:', 'Sign in and go', 'Perform a pre-climb safety check: PPE inspection, weather assessment, LOTO verification, and communication check', 'Only check the weather', 'Inform the office by email', 'B', 'Pre-climb protocols include PPE inspection (harness, lanyards, helmet), weather check (wind speed limits, lightning), LOTO status verification, and confirming communication devices work.', 'GWO BST Standard', 'medium'),
('GWO_BST', 'safety', 'The maximum wind speed for safe turbine climbing is typically:', '10 mph (4.5 m/s)', '15 mph (6.7 m/s)', '25 mph (11 m/s) — varies by operator', '50 mph (22 m/s)', 'C', 'Most operators set climbing limits around 20-25 mph sustained wind. Exact limits vary by site and operator policy. Work at heights is prohibited in severe weather.', 'GWO WAH Standard', 'medium'),
('GWO_BST', 'safety', 'A controlled descent device (rescue descender) in a wind turbine is used for:', 'Rapid ascent', 'Emergency evacuation from the nacelle or hub when normal egress is blocked', 'Equipment lowering only', 'Lightning protection', 'B', 'Controlled descent devices allow technicians to evacuate from the nacelle to ground level in emergencies such as fire or medical events when the ladder is not usable.', 'GWO BST Standard', 'easy'),
('GWO_BST', 'safety', 'Personal fall limiters (SRL/retractable lifelines) must be inspected:', 'Annually only', 'Before each use and annually by a competent person', 'Only when damaged', 'Every 5 years', 'B', 'ANSI Z359 requires pre-use inspection by the user before each use and formal annual inspection by a competent person. Equipment involved in a fall arrest must be removed from service.', 'ANSI Z359.14', 'medium'),
('GWO_BST', 'safety', 'The leading cause of fatalities in the wind energy industry is:', 'Electrical shock', 'Falls from height', 'Struck-by incidents', 'Transportation accidents', 'B', 'Falls from height remain the leading cause of wind energy fatalities, which is why GWO Working at Heights is a mandatory BST module.', 'OSHA Fatality Data', 'easy'),
('GWO_BST', 'safety', 'When performing a nacelle rescue, the first priority is:', 'Lowering the casualty immediately', 'Scene safety — ensuring the turbine is stopped, LOTO applied, and no additional hazards exist', 'Calling for a helicopter', 'Administering medication', 'B', 'Scene safety always comes first. The turbine must be stopped and LOTO applied, additional hazards assessed, and the rescue plan reviewed before approaching the casualty.', 'GWO BST Standard', 'medium'),
('GWO_BST', 'safety', 'An AED (Automated External Defibrillator) should be used when:', 'A person has a broken arm', 'A person is unresponsive with no normal breathing or pulse', 'A person is conscious but dizzy', 'Only by paramedics', 'B', 'AEDs are used on unresponsive casualties with no pulse or abnormal breathing (cardiac arrest). They analyze the rhythm and advise shock only if ventricular fibrillation or pulseless VT is detected.', 'GWO First Aid Standard', 'easy'),
('GWO_BST', 'safety', 'Dropped object prevention in a wind turbine requires:', 'Nothing — the exclusion zone is sufficient', 'Tool tethering, barricaded drop zones, and secured loose items', 'Only a hard hat', 'Working fast to minimize exposure', 'B', 'All tools and equipment must be tethered to prevent dropping. Drop zones must be barricaded, and loose items secured. Even small objects falling 80+ meters can be lethal.', 'GWO BST Standard', 'easy'),
('GWO_BST', 'safety', 'Heat stress in a nacelle is managed by:', 'Working through it to finish quickly', 'Hydration, scheduled rest breaks, monitoring symptoms, and ventilation', 'Removing PPE to cool down', 'Only working at night', 'B', 'Nacelle temperatures can exceed 120°F. Heat stress management includes hydration, work/rest cycles, symptom monitoring, portable ventilation, and emergency response planning.', 'OSHA Heat Illness Prevention', 'easy'),
('GWO_BST', 'safety', 'Lightning protection during turbine work requires:', 'Grounding your harness', 'Evacuating the turbine when lightning is within 30 miles (48 km) per site-specific policy', 'Staying in the hub', 'Continuing work if thunder is distant', 'B', 'Most site protocols require turbine evacuation when lightning is detected within a specified range (typically 30 miles). Technicians must never be on the tower during electrical storms.', 'GWO BST Standard', 'medium'),
('GWO_BST', 'safety', 'The purpose of a Job Safety Analysis (JSA) before turbine work is to:', 'Satisfy paperwork requirements', 'Identify hazards, assess risks, and establish control measures for the specific task', 'Assign blame if an accident occurs', 'Speed up the work process', 'B', 'A JSA systematically breaks down each work step, identifies potential hazards, assesses risk, and documents control measures. It must be reviewed by the entire crew.', 'OSHA Recommended Practices', 'easy'),
('GWO_BST', 'safety', 'GWO BST certification is valid for:', '1 year', '2 years', '5 years', 'Lifetime', 'B', 'GWO BST modules are valid for 2 years, after which technicians must complete refresher training to maintain their certification.', 'GWO BST Standard', 'easy'),

-- ============================================================
-- GWO_BTT (GWO Basic Technical Training) — 20 questions
-- ============================================================
('GWO_BTT', 'electrical', 'The main generator in a modern variable-speed wind turbine is typically a:', 'DC generator', 'Doubly-fed induction generator (DFIG) or permanent magnet synchronous generator (PMSG)', 'Single-phase AC generator', 'Steam turbine generator', 'B', 'Modern turbines use either DFIG (with a partial-scale converter on the rotor) or PMSG (with a full-scale converter), both allowing variable-speed operation for maximum energy capture.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'electrical', 'A frequency converter in a wind turbine serves to:', 'Increase voltage only', 'Convert variable-frequency generator output to fixed-frequency grid power', 'Charge batteries', 'Reduce power output', 'B', 'The frequency converter (power electronics) converts the variable frequency/voltage from the generator to match the fixed grid frequency (50/60 Hz) and voltage.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'mechanical', 'The purpose of the yaw system is to:', 'Control blade pitch', 'Rotate the nacelle to face the rotor into the wind', 'Brake the rotor', 'Cool the gearbox', 'B', 'The yaw system uses electric or hydraulic motors with a large bearing to rotate the nacelle, keeping the rotor aligned with the wind direction for maximum energy capture.', 'IEC 61400-1', 'easy'),
('GWO_BTT', 'mechanical', 'The pitch system controls:', 'Yaw direction', 'The angle of each blade relative to the wind to regulate power and enable shutdown', 'Generator speed only', 'Tower vibration', 'B', 'Pitch control rotates each blade around its longitudinal axis. It regulates power output above rated wind speed and feathers blades to 90° for aerodynamic braking during shutdown.', 'IEC 61400-1', 'easy'),
('GWO_BTT', 'mechanical', 'Bolt torque values on a wind turbine are critical because:', 'They affect paint adhesion', 'Under-torqued bolts loosen from vibration; over-torqued bolts can yield or crack', 'They are approximate guidelines only', 'Only hub bolts matter', 'B', 'Wind turbines experience extreme cyclic loading. Proper bolt torque (and pre-tension) per manufacturer specifications prevents fatigue failures, loosening, and structural compromise.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'hydraulics', 'The hydraulic pitch system uses accumulators primarily for:', 'Storing hydraulic fluid', 'Providing emergency pitch-to-feather capability during power loss', 'Cooling the hydraulic oil', 'Filtering contaminants', 'B', 'Hydraulic accumulators store pressurized energy to drive blades to feather position (90°) during emergency shutdowns when the main hydraulic pump loses power.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'electrical', 'The transformer in a wind turbine steps voltage from:', 'Grid voltage down to generator voltage', 'Generator voltage (typically 690V) up to collection system voltage (typically 33-36kV)', 'AC to DC', 'High voltage to battery voltage', 'B', 'The pad-mount or nacelle transformer steps up from the generator output (typically 690V) to the wind farm collection system voltage (typically 33-36 kV) for efficient transmission.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'mechanical', 'The main bearing in a wind turbine supports:', 'Only the generator', 'The rotor hub and blades, transferring loads to the mainframe', 'The yaw system only', 'The tower base', 'B', 'The main bearing supports the full weight and aerodynamic loads of the rotor assembly (hub and blades), transferring these forces to the mainframe/bedplate.', 'IEC 61400-1', 'easy'),
('GWO_BTT', 'electrical', 'Grounding (earthing) of a wind turbine is essential to protect against:', 'Corrosion only', 'Lightning strikes and electrical faults', 'Wind loading', 'Noise', 'B', 'The turbine grounding system provides a low-impedance path for lightning current and fault current to dissipate safely to earth, protecting equipment and personnel.', 'IEC 61400-24', 'easy'),
('GWO_BTT', 'mechanical', 'A gearbox in a wind turbine increases:', 'Torque to the generator', 'Rotor speed to generator speed (typically 10-20 RPM to 1000-1800 RPM)', 'Blade pitch angle', 'Yaw rate', 'B', 'The gearbox steps up the slow rotor speed to the high speed required by the generator. Gear ratios are typically 1:80 to 1:100 depending on the design.', 'IEC 61400-4', 'easy'),
('GWO_BTT', 'hydraulics', 'Hydraulic fluid contamination in a pitch or brake system is detected by:', 'Visual color check only', 'Particle count analysis and filter differential pressure monitoring', 'Smelling the fluid', 'Checking fluid temperature only', 'B', 'Particle contamination is measured per ISO 4406 cleanliness codes using particle counters. Filter differential pressure gauges indicate when filters are saturated.', 'ISO 4406', 'medium'),
('GWO_BTT', 'electrical', 'LOTO (Lockout/Tagout) on a wind turbine must include:', 'Only the main breaker', 'All energy sources: electrical (main breaker, capacitors), mechanical (rotor lock, yaw lock), hydraulic (pressure bleed)', 'Only a tag on the control panel', 'Verbal notification only', 'B', 'Wind turbines contain multiple energy sources. Complete LOTO requires isolating electrical, mechanical (rotor lock pin), hydraulic (depressurize accumulators), and verifying zero energy.', 'OSHA 1910.147', 'medium'),
('GWO_BTT', 'mechanical', 'Blade bolt pre-tensioning is performed using:', 'A standard wrench', 'A hydraulic bolt tensioner to achieve precise and uniform clamp load', 'An impact wrench', 'Hand tightening', 'B', 'Blade bolts (root connection) require hydraulic tensioners to achieve the precise, high pre-tension values needed to resist cyclic fatigue loading. Torque wrenches alone cannot achieve the required accuracy.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'electrical', 'When measuring insulation resistance on a generator winding, a reading below the minimum indicates:', 'Normal operation', 'Moisture ingress or insulation degradation requiring investigation', 'The generator is brand new', 'The test equipment is faulty', 'B', 'Low insulation resistance (megohm readings below manufacturer minimums) indicates moisture contamination, dirt, or insulation breakdown that can lead to short circuits or ground faults.', 'IEC 60034-27', 'medium'),
('GWO_BTT', 'hydraulics', 'The purpose of a hydraulic accumulator pre-charge is:', 'To fill the accumulator with oil', 'To set the nitrogen gas pressure to the correct level for proper system response', 'To bleed air from the system', 'To test for leaks', 'B', 'Accumulators use compressed nitrogen gas on one side of a bladder. The pre-charge pressure must be set correctly to provide proper energy storage and system response.', 'IEC 61400-1', 'medium'),
('GWO_BTT', 'electrical', 'Capacitor banks in a wind turbine are used for:', 'Energy storage for backup power', 'Power factor correction to reduce reactive power', 'Lightning protection', 'Heating the nacelle', 'B', 'Capacitor banks provide power factor correction, compensating for the reactive power consumed by induction generators and transformers to maintain grid code compliance.', 'IEC 61400-21', 'medium'),
('GWO_BTT', 'mechanical', 'The yaw brake serves to:', 'Stop the rotor', 'Hold the nacelle in position and prevent unwanted yaw movement', 'Adjust blade pitch', 'Lock the main shaft', 'B', 'The yaw brake provides friction to hold the nacelle steady during operation and prevent wind-induced oscillation. It releases during active yaw adjustments.', 'IEC 61400-1', 'easy'),
('GWO_BTT', 'hydraulics', 'When servicing a hydraulic system, the first step is always to:', 'Open the reservoir', 'Depressurize the system and follow LOTO procedures', 'Replace all filters', 'Add fluid', 'B', 'Hydraulic systems store energy under high pressure. Accumulators and lines must be fully depressurized, and LOTO applied before any maintenance to prevent injection injuries.', 'OSHA 1910.147', 'easy'),
('GWO_BTT', 'electrical', 'Surge protection devices (SPDs) in a wind turbine protect against:', 'Overloads', 'Voltage transients from lightning and switching events', 'Underspeed conditions', 'Mechanical vibration', 'B', 'SPDs divert transient overvoltages to ground, protecting sensitive electronics (controllers, converters, sensors) from lightning-induced surges and switching transients.', 'IEC 61400-24', 'medium'),
('GWO_BTT', 'mechanical', 'Vibration monitoring (CMS) on a gearbox detects:', 'Only imbalance', 'Bearing wear, gear tooth damage, misalignment, and other developing faults', 'Temperature only', 'Oil level', 'B', 'Condition monitoring systems (CMS) use accelerometers to detect characteristic vibration signatures of bearing defects, gear tooth damage, and misalignment before catastrophic failure.', 'IEC 61400-25', 'medium'),

-- ============================================================
-- ACP_TECH (ACP Wind Technician) — 20 questions
-- ============================================================
('ACP_TECH', 'composites', 'Leading edge erosion on wind turbine blades is caused primarily by:', 'UV radiation only', 'Rain, hail, insects, and particulate impact at high tip speeds', 'Salt spray alone', 'Temperature cycling only', 'B', 'Leading edge erosion results from repeated impact of rain drops, hail, insects, and airborne particles at blade tip speeds exceeding 200 mph, progressively removing the coating and laminate.', 'IEC 61400-5', 'medium'),
('ACP_TECH', 'composites', 'A blade inspection revealing delamination requires:', 'Ignoring it if small', 'Assessment per the blade repair manual, typically involving removal of damaged material and vacuum-infused patch repair', 'Replacing the entire blade immediately', 'Painting over the area', 'B', 'Delamination must be assessed for extent using tap testing or ultrasound, then repaired per the OEM blade repair manual. Repairs typically involve grinding, layup, vacuum infusion, and curing.', 'IEC 61400-5', 'medium'),
('ACP_TECH', 'composites', 'When performing a composite blade repair, the work environment must be:', 'Any temperature', 'Temperature and humidity controlled per resin specifications, typically 60-85°F and below 80% RH', 'Only outdoors', 'Below freezing for resin curing', 'B', 'Composite resin systems require specific temperature and humidity ranges for proper cure. Working outside these parameters causes incomplete cure and weak repairs.', 'IEC 61400-5', 'medium'),
('ACP_TECH', 'electrical', 'When troubleshooting a pitch motor fault, the first step is to:', 'Replace the motor immediately', 'Check the fault code, verify power supply voltage, and measure motor winding resistance', 'Bypass the safety system', 'Reset and hope it clears', 'B', 'Systematic troubleshooting starts with reading fault codes from the pitch controller, verifying supply voltage, and measuring winding resistance to isolate the failed component.', 'IEC 61400-1', 'medium'),
('ACP_TECH', 'regulations', 'OSHA requires fall protection training to be provided:', 'Once in a career', 'Before the worker is exposed to fall hazards and as retraining when warranted', 'Only after an incident', 'Annually regardless', 'B', 'OSHA 1926.503 requires training before exposure to fall hazards, retraining when the worker does not demonstrate competency, and when workplace changes create new hazards.', 'OSHA 1926.503', 'easy'),
('ACP_TECH', 'electrical', 'Medium-voltage switching in a wind turbine pad-mount transformer requires:', 'No special precautions', 'Arc flash PPE, proper clearances, and only qualified personnel', 'Just rubber gloves', 'Only a hard hat', 'B', 'Medium-voltage (33-36 kV) switching requires arc flash hazard analysis, appropriate PPE category gear (rated for the incident energy), proper approach boundaries, and qualified electricians.', 'NFPA 70E', 'medium'),
('ACP_TECH', 'mechanical', 'Gearbox oil sampling should be analyzed for:', 'Color only', 'Particle count, water content, viscosity, and wear metal analysis', 'Temperature only', 'Smell', 'B', 'Comprehensive oil analysis includes ISO particle count, Karl Fischer water content, kinematic viscosity, and spectrometric wear metal analysis (Fe, Cu, Sn, Pb) to detect developing failures.', 'ISO 4406', 'medium'),
('ACP_TECH', 'hydraulics', 'A pitch cylinder that drifts slowly under load likely has:', 'Normal behavior', 'Internal seal wear or a leaking control valve', 'Low accumulator pre-charge', 'A blocked filter', 'B', 'Cylinder drift under load indicates internal leakage past the piston seals or a leaking proportional/servo valve allowing fluid to bypass the cylinder.', 'IEC 61400-1', 'medium'),
('ACP_TECH', 'safety', 'A confined space entry in a wind turbine hub requires:', 'No special precautions', 'Atmospheric testing, entry permit, attendant, and rescue plan', 'Only a flashlight', 'Permission from the landowner', 'B', 'The hub of a wind turbine is a permit-required confined space due to limited egress, potential atmospheric hazards, and engulfment risk from moving parts.', 'OSHA 1910.146', 'medium'),
('ACP_TECH', 'regulations', 'IEC 61400-1 primarily covers:', 'Blade manufacturing', 'Design requirements for wind turbine structural and mechanical safety', 'Electrical grid codes', 'Environmental impact assessment', 'B', 'IEC 61400-1 is the primary international standard for wind turbine design requirements, covering structural loads, safety systems, and design life considerations.', 'IEC 61400-1', 'easy'),
('ACP_TECH', 'electrical', 'Power curve testing of a wind turbine measures:', 'Only maximum output', 'Electrical power output versus wind speed to verify performance against the guaranteed curve', 'Reactive power only', 'Generator temperature', 'B', 'Power curve testing per IEC 61400-12 measures actual power output at various wind speeds using a calibrated met mast, verifying the turbine meets its guaranteed performance.', 'IEC 61400-12', 'medium'),
('ACP_TECH', 'composites', 'Non-destructive testing (NDT) methods for blade inspection include:', 'Only visual inspection', 'Ultrasonic testing, thermography, and tap testing', 'X-ray only', 'Destructive coupon testing', 'B', 'Blade NDT uses ultrasonic testing (for delamination depth), infrared thermography (for moisture and disbonds), and tap testing (for near-surface delamination).', 'IEC 61400-5', 'medium'),
('ACP_TECH', 'mechanical', 'Tower bolt torque checks are performed:', 'Only during commissioning', 'Per the maintenance schedule — typically at 6 months, 1 year, and then at regular intervals', 'Only if the turbine vibrates', 'Never after installation', 'B', 'Tower section bolts require re-torque checks at commissioning +6 months, +1 year, and then at scheduled maintenance intervals to account for embedment relaxation and cyclic loading.', 'IEC 61400-1', 'medium'),
('ACP_TECH', 'safety', 'Before performing up-tower rescue, the rescue team must verify:', 'That the casualty is conscious', 'Turbine LOTO, weather conditions, rescue equipment functionality, and communication', 'Only that a helicopter is available', 'Nothing — speed is the priority', 'B', 'Rescue preparation requires verifying turbine LOTO (rotor locked, electrically isolated), acceptable weather, functional rescue equipment, established communication, and a clear plan.', 'GWO BST Standard', 'medium'),
('ACP_TECH', 'electrical', 'Fiber optic cables in wind turbines are used for:', 'Power transmission', 'High-speed data communication immune to electromagnetic interference', 'Grounding', 'Blade heating', 'B', 'Fiber optic cables transmit SCADA and control data between nacelle, tower base, and substation. They are preferred because they are immune to the electromagnetic interference present in turbines.', 'IEC 61400-25', 'easy'),
('ACP_TECH', 'regulations', 'An aviation obstruction lighting system on a wind turbine is required when:', 'Always', 'The turbine exceeds 200 feet (61 m) AGL per FAA regulations', 'Only near airports', 'Only at night', 'B', 'FAA Advisory Circular 70/7460-1 requires obstruction lighting on structures exceeding 200 feet AGL, which includes virtually all modern utility-scale wind turbines.', 'FAA AC 70/7460-1', 'easy'),
('ACP_TECH', 'hydraulics', 'A hydraulic power unit low-pressure alarm in the pitch system indicates:', 'Normal standby condition', 'Potential leak, pump failure, or accumulator pre-charge loss requiring immediate investigation', 'The system is at full pressure', 'The blades are feathered', 'B', 'Low pitch hydraulic pressure is a safety-critical alarm. It could indicate a hose leak, pump failure, or accumulator bladder failure, any of which could prevent emergency feathering.', 'IEC 61400-1', 'hard'),
('ACP_TECH', 'mechanical', 'Yaw bearing grease must be applied:', 'Only when noise is heard', 'Per the maintenance schedule using the OEM-specified grease type and quantity', 'With any available grease', 'Only during commissioning', 'B', 'Yaw bearing greasing follows strict OEM intervals with specified grease type (typically EP lithium complex) and quantity. Wrong grease or over/under-greasing causes premature bearing failure.', 'IEC 61400-1', 'easy'),
('ACP_TECH', 'composites', 'When working with fiberglass and epoxy resins, required PPE includes:', 'No PPE needed', 'Chemical-resistant gloves, safety glasses, respirator with organic vapor cartridges, and protective clothing', 'Only gloves', 'Only a dust mask', 'B', 'Epoxy resins contain sensitizers that cause dermatitis and respiratory issues. Full PPE including nitrile gloves, eye protection, OV respirator, and coveralls is required.', 'OSHA 1910.134', 'easy'),
('ACP_TECH', 'electrical', 'Generator slip ring maintenance includes:', 'Replacing the generator', 'Inspecting brush wear, cleaning rings, checking spring tension, and measuring resistance', 'Only adding lubricant', 'No maintenance needed', 'B', 'Slip rings (on DFIG wound rotors) require regular inspection of carbon brush wear length, ring surface condition, spring tension, and contact resistance to prevent arcing and failure.', 'IEC 60034', 'medium'),

-- ============================================================
-- SENIOR_TECH (Senior Technician) — 20 questions
-- ============================================================
('SENIOR_TECH', 'electrical', 'Harmonic distortion from a wind turbine converter is limited by:', 'No standards exist', 'IEC 61400-21 and grid code requirements, using line filters and PWM control strategies', 'Adding more turbines', 'Reducing power output', 'B', 'IEC 61400-21 defines power quality requirements including harmonic limits. Converters use PWM switching patterns and LCL filters to keep harmonics within grid code limits.', 'IEC 61400-21', 'hard'),
('SENIOR_TECH', 'electrical', 'Low Voltage Ride Through (LVRT) capability requires a turbine to:', 'Disconnect immediately during a grid voltage dip', 'Remain connected and provide reactive current support during grid voltage dips', 'Increase active power during faults', 'Switch to island mode', 'B', 'LVRT/FRT capability keeps turbines connected during grid faults (voltage dips to 0-15% for 150-600 ms depending on grid code), providing reactive current to support voltage recovery.', 'IEC 61400-21', 'hard'),
('SENIOR_TECH', 'mechanical', 'Root cause analysis of a main bearing failure typically investigates:', 'Only lubrication records', 'Lubrication, alignment, loading history, vibration data, oil analysis trends, and operational conditions', 'Only visual inspection', 'The turbine age', 'B', 'RCA for main bearing failure requires holistic investigation: grease analysis, alignment measurements, CMS vibration trend review, SCADA load data, and metallurgical analysis of failed components.', 'IEC 61400-4', 'hard'),
('SENIOR_TECH', 'regulations', 'A NERC (North American Electric Reliability Corporation) compliance requirement for wind farms includes:', 'No regulations apply', 'Accurate modeling of plant reactive capability and providing frequency response', 'Only metering accuracy', 'Voluntary reporting', 'B', 'NERC standards (FAC, MOD, VAR) require wind farms to provide accurate dynamic models, maintain reactive power capability, and contribute to grid frequency regulation.', 'NERC FAC-001', 'hard'),
('SENIOR_TECH', 'electrical', 'Partial discharge testing on a medium-voltage cable or transformer winding detects:', 'Complete insulation failure', 'Incipient insulation degradation before catastrophic failure', 'Resistance only', 'Power output', 'B', 'Partial discharge (PD) testing detects micro-discharges within insulation voids that precede full breakdown. Trending PD levels allows proactive replacement before failure.', 'IEC 60270', 'hard'),
('SENIOR_TECH', 'mechanical', 'When specifying a crane for a main component replacement (gearbox or generator), the critical factors are:', 'Only crane capacity', 'Lift capacity at radius, boom length, ground bearing pressure, wind limits, and rigging plan', 'Cost only', 'Crane color', 'B', 'Heavy lifts require detailed planning: crane capacity at the specific radius/boom configuration, site access, ground conditions (bearing pressure), wind speed limits, and an engineered rigging plan.', 'ASME B30.5', 'medium'),
('SENIOR_TECH', 'composites', 'A structural spar cap repair on a blade requires:', 'Surface patch only', 'Engineering-approved repair procedure with proper fiber orientation, vacuum infusion, controlled cure, and load testing', 'Filling with putty', 'Duct tape and paint', 'B', 'Spar cap repairs are structurally critical. They require OEM or engineering-approved procedures with correct fiber layup orientation, vacuum infusion, temperature-controlled cure, and potentially proof loading.', 'IEC 61400-5', 'hard'),
('SENIOR_TECH', 'safety', 'As a senior technician supervising a team, you are responsible for:', 'Only your own safety', 'Overall site safety, JSA review, ensuring team competency and PPE compliance, and stop-work authority', 'Only production targets', 'Equipment inventory', 'B', 'The senior tech/lead is responsible for overall crew safety, reviewing and approving JSAs, verifying team qualifications, enforcing PPE compliance, and exercising stop-work authority.', 'OSHA General Duty Clause', 'easy'),
('SENIOR_TECH', 'electrical', 'SCADA system cybersecurity for a wind farm should follow:', 'No cybersecurity needed', 'IEC 62443 and NERC CIP standards for industrial control system security', 'Standard IT security only', 'Physical security only', 'B', 'Wind farm SCADA systems are industrial control systems that must follow IEC 62443 (industrial cybersecurity) and, for bulk power system assets, NERC CIP standards.', 'IEC 62443', 'hard'),
('SENIOR_TECH', 'mechanical', 'Fatigue analysis of a wind turbine tower uses:', 'Static load calculations only', 'Rainflow counting of load cycles and S-N curve comparison per IEC 61400-1 design lifetime', 'Visual inspection only', 'Paint thickness measurements', 'B', 'Tower fatigue assessment uses rainflow cycle counting of measured or simulated loads compared against material S-N (Wohler) curves to determine remaining design life.', 'IEC 61400-1', 'hard'),
('SENIOR_TECH', 'regulations', 'Environmental compliance for a wind farm includes monitoring:', 'Nothing post-construction', 'Avian and bat mortality, noise levels, shadow flicker, and wetland impacts', 'Only visual appearance', 'Electricity production only', 'B', 'Post-construction environmental compliance requires monitoring bird/bat fatalities (curtailment programs), noise at property boundaries, shadow flicker, and any wetland or habitat impacts.', 'USFWS Guidelines', 'medium'),
('SENIOR_TECH', 'electrical', 'Commissioning a new wind turbine includes which electrical test?', 'Only turning it on', 'Insulation resistance, protective relay testing, grounding resistance, and grid code compliance verification', 'Visual inspection only', 'Running at full power immediately', 'B', 'Electrical commissioning includes megger testing (insulation resistance), relay trip testing, ground grid resistance measurement, power quality verification, and LVRT compliance testing.', 'IEC 61400-1', 'medium'),
('SENIOR_TECH', 'hydraulics', 'Predictive maintenance on a hydraulic pitch system uses:', 'Run-to-failure strategy', 'Trend analysis of pressure, temperature, oil particle counts, and cylinder position feedback', 'Calendar-based replacement only', 'No maintenance strategy', 'B', 'Predictive maintenance combines trending of system pressure, oil analysis (particle counts, water), accumulator pre-charge decay rates, and cylinder response times to predict failures.', 'ISO 4406', 'medium'),
('SENIOR_TECH', 'mechanical', 'Tower natural frequency must avoid:', 'All frequencies', 'The rotor frequency (1P) and blade passing frequency (3P) to prevent resonance', 'Only earthquake frequencies', 'Generator frequency', 'B', 'Tower design must place its natural frequency between 1P (rotor rotational frequency) and 3P (blade passing frequency) to avoid resonance. This is called a "soft-stiff" design.', 'IEC 61400-1', 'hard'),
('SENIOR_TECH', 'composites', 'Lightning damage to a blade tip is assessed using:', 'Visual inspection only', 'Visual inspection, ultrasonic testing for internal damage, and receptor resistance measurement', 'Tap testing alone', 'Thermal imaging alone', 'B', 'Lightning strikes can cause hidden internal damage (delamination, carbon tracking) beyond visible surface damage. UT detects internal delamination and resistance measurements verify the down-conductor path integrity.', 'IEC 61400-24', 'hard'),
('SENIOR_TECH', 'electrical', 'When analyzing SCADA data for performance optimization, key indicators include:', 'Only total energy production', 'Capacity factor, availability, power curve deviation, component temperatures, and error frequency', 'Turbine color code', 'Only wind speed data', 'B', 'Performance analysis uses capacity factor trends, time-based and energy-based availability, actual vs. warranted power curve analysis, component temperature trends, and top-10 fault analysis.', 'IEC 61400-26', 'medium'),
('SENIOR_TECH', 'safety', 'A Management of Change (MOC) process is required when:', 'Performing routine maintenance', 'Making any non-routine modification to equipment, procedures, or personnel roles that could affect safety', 'Only during commissioning', 'Only when changing oil', 'B', 'MOC ensures that any change to equipment, operating procedures, materials, or organizational structure is properly reviewed for safety impacts before implementation.', 'OSHA PSM 1910.119', 'medium'),
('SENIOR_TECH', 'regulations', 'Decommissioning a wind turbine requires:', 'Abandoning it in place', 'Full removal of above-ground structures, foundation to specified depth, and site restoration per permit conditions', 'Only removing the blades', 'Selling it to a new owner', 'B', 'Decommissioning typically requires complete removal of turbine, foundation removal to 3-4 feet below grade, road removal or regrading, and site restoration per the original land use permit.', 'Local Permit Conditions', 'medium'),
('SENIOR_TECH', 'mechanical', 'Direct-drive turbines eliminate the gearbox but require:', 'No special considerations', 'A larger, heavier generator with many pole pairs and a full-scale power converter', 'Smaller blades', 'Higher rotor speed', 'B', 'Direct-drive designs use large-diameter, multi-pole generators (PMSG or EESG) that are heavier but eliminate gearbox failures. They require full-scale converters to handle the full power output.', 'IEC 61400-1', 'medium'),
('SENIOR_TECH', 'electrical', 'Energy storage integration with a wind farm can provide:', 'No benefit', 'Frequency regulation, ramp rate control, and capacity firming to improve grid reliability', 'Only backup power for the substation', 'Reduced energy production', 'B', 'Battery energy storage systems (BESS) paired with wind farms provide frequency response, smooth output ramp rates, shift energy to peak demand, and firm variable capacity.', 'IEC 61400-21', 'medium');
