-- 040_seed_liftpal_cert_questions.sql
-- Cert prep question bank for LiftPal (elevator/lift): ~80 questions
-- ~20 per cert level: CET, QEI, CAT, SENIOR_TECH

INSERT INTO liftpal.cert_prep_questions (cert_level, category, question, option_a, option_b, option_c, option_d, correct_answer, explanation, code_reference, difficulty) VALUES

-- ============================================================
-- CET (Certified Elevator Technician) — 20 questions
-- ============================================================
('CET', 'codes_standards', 'ASME A17.1 is the primary code governing:', 'Escalator manufacturing', 'Safety requirements for elevators, escalators, and moving walks', 'Building fire codes', 'Electrical wiring methods', 'B', 'ASME A17.1/CSA B44 is the Safety Code for Elevators and Escalators, establishing minimum safety requirements for the design, construction, installation, operation, inspection, testing, and maintenance of elevators.', 'ASME A17.1', 'easy'),
('CET', 'electrical', 'The purpose of a door interlock on an elevator hoistway door is to:', 'Improve door closing speed', 'Prevent the car from moving unless the hoistway door is closed and locked', 'Control lighting in the car', 'Adjust door opening width', 'B', 'Door interlocks are a critical safety device that prevents car movement unless the hoistway door is fully closed and mechanically locked. They are verified to be in the safety circuit.', 'ASME A17.1 §2.12', 'easy'),
('CET', 'mechanical', 'The minimum number of suspension ropes required for a traction elevator is:', '1', '2', '3', '4', 'C', 'ASME A17.1 requires a minimum of 3 suspension ropes (or chains) for traction elevators to provide adequate safety factor and redundancy.', 'ASME A17.1 §2.20.2', 'easy'),
('CET', 'safety', 'Before working on top of an elevator car, a technician must:', 'Simply ride to the top floor', 'Place the car on inspection operation, activate the car top stop switch, and follow LOTO procedures', 'Just open the hoistway door', 'Notify the building manager only', 'B', 'Car top procedures require placing the elevator on inspection operation (reduced speed, maintained-pressure controls), activating the car top emergency stop, and LOTO per OSHA and A17.1.', 'ASME A17.1 §2.26.1', 'easy'),
('CET', 'electrical', 'A selector in an elevator system is used to:', 'Control door speed', 'Determine and display the car position in the hoistway', 'Adjust motor voltage', 'Monitor rope tension', 'B', 'The selector tracks the car position in the hoistway, providing position information to the controller for floor leveling, dispatching, and position indication.', 'ASME A17.1', 'easy'),
('CET', 'mechanical', 'Governor rope tension is maintained by:', 'The drive sheave', 'A weighted governor tension sheave at the bottom of the hoistway', 'Spring clips', 'The counterweight', 'B', 'A tension sheave with attached weight at the pit maintains proper governor rope tension and prevents the rope from jumping the governor sheave grooves.', 'ASME A17.1 §2.18', 'easy'),
('CET', 'electrical', 'The safety circuit in an elevator is:', 'A convenience feature', 'A series circuit of all safety switches that must be complete before the car can run', 'A parallel circuit for redundancy', 'The lighting circuit', 'B', 'The safety circuit is a series string of normally-closed contacts (governor switch, door interlocks, pit stop, car top stop, buffer switches) that must all be closed for the controller to run the car.', 'ASME A17.1 §2.26', 'easy'),
('CET', 'mechanical', 'The purpose of compensation chains or ropes on a traction elevator is to:', 'Provide emergency braking', 'Compensate for the weight of the suspension ropes as the car moves through the hoistway', 'Operate the doors', 'Balance the governor', 'B', 'Compensation ropes or chains offset the changing weight of suspension ropes on each side of the sheave as the car travels, maintaining balanced traction on high-rise installations.', 'ASME A17.1 §2.20.10', 'medium'),
('CET', 'safety', 'The minimum pit depth for a typical traction elevator is determined by:', 'Building aesthetics', 'ASME A17.1 based on car speed, buffer stroke, and required clearance', 'The elevator manufacturer only', 'Local building codes only', 'B', 'Pit depth must accommodate the fully compressed buffer plus required running clearance beneath the car platform and counterweight per A17.1 calculations.', 'ASME A17.1 §2.2.2', 'medium'),
('CET', 'electrical', 'An elevator motor drive using VVVF technology means:', 'Variable Voltage Variable Frequency — adjusts both voltage and frequency to control motor speed', 'Very Varied Velocity Function', 'Variable Ventilation and Velocity Fan', 'Vertical Voltage Variable Factor', 'A', 'VVVF (Variable Voltage Variable Frequency) drives precisely control AC motor speed by varying both the voltage and frequency of the power supply, enabling smooth acceleration and leveling.', 'ASME A17.1', 'medium'),
('CET', 'mechanical', 'The traction ratio is the relationship between:', 'Car speed and motor speed', 'The tensions on the car side and counterweight side of the drive sheave', 'Door opening speed and closing speed', 'Rope diameter and groove depth', 'B', 'The traction ratio (T1/T2) must not exceed the available traction. If it does, ropes slip on the sheave. Proper counterweight balance (40-50% of rated load) maintains safe traction.', 'ASME A17.1 §2.20.1', 'medium'),
('CET', 'codes_standards', 'An elevator car must have an emergency means of communication that:', 'Only works during business hours', 'Connects to authorized personnel 24/7 and activates automatically within a set time', 'Is optional for freight elevators', 'Requires a cell phone', 'B', 'ASME A17.1 §2.27.1.1.6 requires hands-free two-way communication that activates automatically if not answered, connecting to personnel available 24/7 for passenger rescue.', 'ASME A17.1 §2.27.1.1.6', 'easy'),
('CET', 'electrical', 'Leveling is the process of:', 'Adjusting the building floor', 'Automatically aligning the car floor with the landing floor within a specified tolerance', 'Balancing the counterweight', 'Testing the governor', 'B', 'Leveling brings the car sill to within a specified tolerance (typically ±1/4 inch) of the landing sill. Modern drives use encoders for precise positioning.', 'ASME A17.1 §2.26.1', 'easy'),
('CET', 'safety', 'Pit safety requirements include:', 'No requirements for the pit', 'A pit stop switch, pit light, pit ladder (if over 35 inches deep), and GFCI outlet', 'Only a light switch', 'Only a drain', 'B', 'The pit must have a stop switch (accessible from the pit access door), a light switch, a GFCI convenience outlet, a ladder if depth exceeds 35 inches, and adequate drainage.', 'ASME A17.1 §2.2.2', 'easy'),
('CET', 'mechanical', 'Wire ropes for elevators are inspected for:', 'Color fading only', 'Broken wires, corrosion, reduction in diameter, distortion, and proper lubrication', 'Length only', 'Manufacturer date only', 'B', 'Rope inspection per A17.2 looks for broken wires per lay, cross-section reduction, corrosion, birdcaging, kinking, core protrusion, and adequate lubrication.', 'ASME A17.2', 'easy'),
('CET', 'electrical', 'The machine room temperature for an elevator must be maintained between:', 'Any temperature', '55°F and 95°F (13°C to 35°C) per ASME A17.1', '32°F and 120°F', 'Below 50°F for equipment cooling', 'B', 'Machine room temperature must be maintained within the range specified by A17.1 and the equipment manufacturer to ensure proper operation of controllers, drives, and lubrication.', 'ASME A17.1 §2.8', 'medium'),
('CET', 'codes_standards', 'Firefighters Emergency Operation (Phase I and Phase II) is required on elevators serving floors:', 'Above 3 stories only', 'Above 25 feet (7.6 m) above or below the designated level per ASME A17.1', 'In all buildings', 'Only in hospitals', 'B', 'Phase I recall and Phase II in-car operation are required on elevators with a travel of more than 25 feet above or below the designated level (ground floor).', 'ASME A17.1 §2.27.3', 'medium'),
('CET', 'mechanical', 'The counterweight typically weighs:', 'Equal to the car weight', 'The car weight plus 40-50% of the rated load capacity', 'Twice the car weight', 'Less than the car weight', 'B', 'Counterweighting at car weight plus 40-50% of rated load minimizes the maximum traction ratio and motor horsepower requirements, balancing the system near its average operating load.', 'ASME A17.1 §2.20.3', 'medium'),
('CET', 'safety', 'A red stop switch on top of the car must:', 'Be momentary contact', 'Be a maintained contact switch that requires manual reset and is accessible from the car top', 'Reset automatically after 30 seconds', 'Be key-operated only', 'B', 'The car top stop switch must be a maintained (non-self-resetting) red switch that removes power from the drive and stops the car. It must be manually reset before the car can move.', 'ASME A17.1 §2.26.1.5', 'easy'),
('CET', 'electrical', 'Door operator electric eyes (light curtains) serve to:', 'Save energy', 'Detect obstructions in the door opening and reopen the doors to prevent contact with passengers', 'Count passengers', 'Control car lighting', 'B', 'Light curtains project an infrared grid across the door opening. Any interruption causes the doors to reopen, preventing injury to passengers entering or exiting.', 'ASME A17.1 §2.13', 'easy'),

-- ============================================================
-- QEI (Qualified Elevator Inspector) — 20 questions
-- ============================================================
('QEI', 'inspection', 'ASME A17.2 is the guide for:', 'Elevator installation', 'Inspection of elevators, escalators, and moving walks', 'Elevator manufacturing', 'Building design', 'B', 'ASME A17.2 provides guidance for inspecting elevators, escalators, and moving walks, including procedures, frequencies, and acceptance criteria.', 'ASME A17.2', 'easy'),
('QEI', 'inspection', 'A Category 1 test of the governor and safeties requires:', 'Full speed testing', 'Testing at rated speed or less to verify the governor trips and safeties set', 'Only a visual inspection', 'No car on the ropes', 'B', 'Category 1 testing verifies governor tripping speed and safety application at rated speed or less. Category 5 (full load, full speed) is the most comprehensive test.', 'ASME A17.1 §8.6.4.19', 'medium'),
('QEI', 'inspection', 'The annual inspection of an elevator must verify that door reopening devices:', 'Are removed', 'Function properly and comply with the kinetic energy and force requirements of A17.1', 'Are disabled after 20 seconds', 'Only work on the lobby floor', 'B', 'Door reopening devices must be tested for proper operation. The door closing force must not exceed 30 lbf, and kinetic energy must not exceed 7 ft-lbs per A17.1 §2.13.4.', 'ASME A17.1 §2.13.4', 'medium'),
('QEI', 'codes_standards', 'ASME A17.3 covers:', 'New installations', 'Safety requirements for existing elevators (retroactive code)', 'Escalator manufacturing', 'Dumbwaiters only', 'B', 'ASME A17.3 establishes safety requirements that apply retroactively to existing elevators, addressing life-safety upgrades such as door restrictors, firefighters operation, and hoistway ventilation.', 'ASME A17.3', 'easy'),
('QEI', 'inspection', 'An inspector finds hoistway door gibs worn beyond allowable limits. This requires:', 'No action', 'Immediate correction — doors could derail, creating a fall hazard into the hoistway', 'Repair within one year', 'Documentation only', 'B', 'Worn door gibs can allow a hoistway door to be displaced outward, creating a fall hazard. This is an immediate safety violation requiring prompt repair.', 'ASME A17.1 §2.11', 'medium'),
('QEI', 'inspection', 'The car-to-hoistway door clearance (running clearance) must not exceed:', '1/4 inch (6 mm)', '3/4 inch (19 mm)', '1 inch (25 mm)', '2 inches (50 mm)', 'B', 'The clearance between the car door and hoistway door must not exceed 3/4 inch to prevent fingers from being inserted between the doors while the car is moving.', 'ASME A17.1 §2.11.8', 'medium'),
('QEI', 'electrical', 'During an acceptance inspection, the inspector must verify that the firefighters Phase I recall:', 'Is optional', 'Returns the car to the designated level, opens the doors, and removes it from normal service upon smoke detector activation or key switch operation', 'Only works with Phase II', 'Speeds up the elevator', 'B', 'Phase I recall must bring the car non-stop to the designated level (or alternate level if smoke is on the designated floor), open the doors, and take the car out of service.', 'ASME A17.1 §2.27.3.1', 'medium'),
('QEI', 'inspection', 'Buffer stroke testing for an oil buffer requires:', 'Visual inspection only', 'Verification that the buffer plunger returns to full extended position and the oil level is correct', 'Dropping the car on the buffer', 'No testing for oil buffers', 'B', 'Oil buffer inspection verifies plunger return (no sticking), correct oil level, no leaks, and proper mounting. Full compression testing (Category 5) is done at specified intervals.', 'ASME A17.2', 'medium'),
('QEI', 'safety', 'An inspector discovering an elevator operating without a functioning governor must:', 'Note it for next inspection', 'Issue an immediate shutdown order — the elevator cannot safely stop in an overspeed condition', 'Allow 30 days for repair', 'Reduce the speed rating', 'B', 'A non-functioning governor means the overspeed protection system is inoperable. This is an immediate life-safety hazard requiring the elevator to be taken out of service.', 'ASME A17.1 §2.18', 'easy'),
('QEI', 'codes_standards', 'The NFPA 72 requirement relevant to elevators is:', 'Sprinkler requirements', 'Smoke detector placement for elevator recall, machine room protection, and hoistway protection', 'Only fire alarm pull stations', 'Exit signage', 'B', 'NFPA 72 specifies smoke detector locations for elevator recall (lobby, machine room, hoistway) and integration with the buildings fire alarm system for Phase I operation.', 'NFPA 72', 'medium'),
('QEI', 'inspection', 'A Category 5 full-load full-speed safety test is performed:', 'Annually', 'At 5-year intervals per ASME A17.1', 'Only at installation', 'Monthly', 'B', 'Category 5 testing (full-load, full-speed governor and safety test) is the most rigorous test, performed at 5-year intervals per A17.1 maintenance and testing requirements.', 'ASME A17.1 §8.6.4.19', 'hard'),
('QEI', 'inspection', 'Escalator comb plate clearances must be checked to ensure:', 'Aesthetics', 'The gap between comb teeth and step treads does not exceed 3/16 inch to prevent entrapment', 'Proper speed only', 'Lighting levels', 'B', 'Comb-to-step tread clearance must not exceed 3/16 inch per A17.1 to prevent objects and body parts from being drawn into the gap at the comb plate.', 'ASME A17.1 §6.1.3.5', 'medium'),
('QEI', 'electrical', 'An inspector verifying GFCI protection in the machine room checks that:', 'All receptacles are standard outlets', 'All 125V single-phase 15- and 20-amp receptacles have GFCI protection per NEC', 'Only the light circuit has GFCI', 'No GFCI is required', 'B', 'NEC requires GFCI protection for receptacles in elevator machine rooms, pits, and on car tops as they are considered maintenance areas with potential wet conditions.', 'NEC 620.85', 'medium'),
('QEI', 'inspection', 'Rope equalization on a traction elevator ensures:', 'All ropes are the same color', 'All suspension ropes carry an equal share of the load to prevent uneven wear', 'Ropes do not need equalization', 'The car runs faster', 'B', 'Rope equalizer springs or hitches at the car or counterweight ensure all ropes share the load equally. Unequal tension causes accelerated wear on loaded ropes and reduced traction.', 'ASME A17.1 §2.20.9', 'medium'),
('QEI', 'codes_standards', 'Seismic requirements for elevators are found in:', 'No seismic requirements exist', 'ASME A17.1 Section 8.4, covering seismic switches, rope retainers, and guide rail brackets', 'NFPA 72 only', 'ADA only', 'B', 'ASME A17.1 §8.4 specifies seismic requirements including seismic switches (trigger levels), counterweight and car frame derailment protection, and guide rail bracket spacing.', 'ASME A17.1 §8.4', 'hard'),
('QEI', 'inspection', 'During a 1-year inspection, the inspector must verify that the machine brake:', 'Has any lining remaining', 'Can hold 125% of rated load with the car at the top floor and the machine de-energized', 'Operates quietly', 'Is painted red', 'B', 'The machine brake must stop and hold the car with 125% of rated load. Brake shoe/pad wear, spring tension, and adjustment are checked to ensure adequate stopping and holding torque.', 'ASME A17.1 §2.24', 'hard'),
('QEI', 'accessibility', 'ADA requirements for elevator car controls include:', 'No specific requirements', 'Buttons no higher than 48 inches (54 inches for side approach), raised/Braille markings, and audible signals', 'Only visual indicators', 'Controls on the outside only', 'B', 'ADA and A17.1 §2.27 require car controls within reach ranges, raised characters and Braille, audible floor announcements, and visible indicators for accessibility.', 'ASME A17.1 §2.27 / ADA', 'easy'),
('QEI', 'inspection', 'An elevator with a speed of 200 fpm requires what type of buffer?', 'Spring buffers', 'Oil buffers', 'Either spring or oil', 'Rubber buffers', 'C', 'Spring buffers may be used up to 200 fpm. Oil buffers are required above 200 fpm. At exactly 200 fpm, either type is acceptable per A17.1.', 'ASME A17.1 §2.22', 'medium'),
('QEI', 'inspection', 'A QEI inspector must hold certification from:', 'Any engineering organization', 'NAESA International (formerly QEI Inc.) or an equivalent recognized authority', 'The elevator manufacturer', 'OSHA directly', 'B', 'QEI certification is issued by NAESA International and requires passing written and practical examinations demonstrating competency in elevator codes and inspection procedures.', 'ASME QEI-1', 'easy'),
('QEI', 'safety', 'Hoistway access key switches must be:', 'Available to all building tenants', 'Restricted to authorized personnel and must extinguish the hall lantern and prevent car movement with the door open', 'Self-resetting after use', 'Identical to building master keys', 'B', 'Hoistway access switches are restricted-access devices that prevent the car from moving while the hoistway door is open on inspection, protecting personnel from being struck.', 'ASME A17.1 §2.12.7', 'medium'),

-- ============================================================
-- CAT (Certified Accessibility Technician) — 20 questions
-- ============================================================
('CAT', 'accessibility', 'ASME A17.1 Section 2.27 addresses:', 'Freight elevators', 'Elevator accessibility requirements for persons with disabilities', 'Escalator handrails', 'Machine room ventilation', 'B', 'Section 2.27 (previously known as the "handicapped" section) covers all accessibility provisions including car size, controls, signals, and communication for persons with disabilities.', 'ASME A17.1 §2.27', 'easy'),
('CAT', 'accessibility', 'The minimum inside car platform dimension for an accessible elevator is:', '48 inches wide by 51 inches deep', '54 inches wide by 60 inches deep', '68 inches wide by 51 inches deep', '80 inches wide by 65 inches deep', 'C', 'ADA requires a minimum car size of 68 inches wide by 51 inches deep (for center-opening doors) to accommodate a wheelchair user and an attendant.', 'ADA §4.10.9', 'medium'),
('CAT', 'accessibility', 'Elevator car control buttons must have raised characters that are:', 'At least 1/2 inch high', 'At least 5/8 inch high with Braille immediately to the left', 'Flat with color contrast only', 'Illuminated only, no tactile', 'B', 'Car control buttons require raised characters at least 5/8 inch high with Grade 2 Braille placed to the left of the button, per ADA and A17.1.', 'ASME A17.1 §2.27.2', 'medium'),
('CAT', 'accessibility', 'Audible floor passing signals in an accessible elevator must:', 'Sound only in the lobby', 'Sound once for up direction and twice for down direction (or provide verbal annunciation)', 'Be silent', 'Sound continuously', 'B', 'Hall lanterns or audible signals must sound once for up and twice for down, or provide verbal annunciation of car direction, to assist visually impaired passengers.', 'ASME A17.1 §2.27.4', 'easy'),
('CAT', 'accessibility', 'The maximum height for the highest car control button in an accessible elevator (front approach) is:', '42 inches', '48 inches', '54 inches', '60 inches', 'B', 'Car controls must be no higher than 48 inches above the finished floor for a front approach by a wheelchair user. Side approach allows up to 54 inches.', 'ADA §4.10.12', 'easy'),
('CAT', 'accessibility', 'Door dwell time (minimum time doors remain open) for an accessible elevator is:', '3 seconds', '5 seconds', '8 seconds', '10 seconds', 'B', 'Accessible elevators must hold doors open for a minimum of 5 seconds to allow wheelchair users adequate time to enter or exit the car.', 'ASME A17.1 §2.27.3', 'easy'),
('CAT', 'accessibility', 'The two-way communication system in an accessible elevator must include:', 'Only a telephone handset', 'Both audible and visible signals to accommodate hearing and visual impairments', 'A text message system only', 'No specific requirements', 'B', 'The emergency communication system must provide both audible (speaker/microphone) and visible (indicator light) features so persons with hearing or visual disabilities can communicate.', 'ASME A17.1 §2.27.1.1.6', 'medium'),
('CAT', 'accessibility', 'Hall call buttons for accessible elevators must be centered at:', '28 inches above the floor', '36 inches above the floor', '42 inches above the floor', '48 inches above the floor', 'C', 'Hall call buttons must be centered at 42 inches above the finished floor, within the accessible reach range for wheelchair users.', 'ADA §4.10.3', 'easy'),
('CAT', 'accessibility', 'Elevator door opening width for an accessible car must be at least:', '32 inches', '36 inches', '42 inches', '48 inches', 'B', 'ADA requires a minimum clear door opening width of 36 inches to allow passage of a wheelchair.', 'ADA §4.10.9', 'easy'),
('CAT', 'accessibility', 'Raised floor designations on both door jambs are required at:', 'Only the lobby floor', 'Every floor served by the elevator', 'Only accessible floors', 'Only emergency exit floors', 'B', 'Raised characters and Braille floor designations must be provided on both jambs at every floor landing, centered at 60 inches above the finished floor.', 'ASME A17.1 §2.27.2', 'easy'),
('CAT', 'accessibility', 'An accessible elevator must provide verbal annunciation of:', 'Only emergency messages', 'Floor stops, direction of travel, and floor identification', 'Only the lobby floor', 'Maintenance schedules', 'B', 'Verbal (audible) annunciation of floors and direction of travel assists visually impaired passengers in navigating the building independently.', 'ASME A17.1 §2.27.4', 'easy'),
('CAT', 'codes_standards', 'The ADA Standards for Accessible Design are enforced by:', 'ASME', 'The Department of Justice (DOJ)', 'The elevator manufacturer', 'OSHA', 'B', 'The DOJ enforces ADA standards for public accommodations and state/local government facilities. The Department of Transportation enforces transit-related ADA requirements.', 'ADA Title III', 'easy'),
('CAT', 'accessibility', 'Car position indicators in an accessible elevator must:', 'Be audible only', 'Be both visual (minimum 1/2 inch characters) and audible', 'Be located outside the car only', 'Only show the next floor', 'B', 'Car position indicators must provide visual indication (minimum 1/2 inch high characters) and audible indication so all passengers can determine the car location.', 'ASME A17.1 §2.27.4', 'medium'),
('CAT', 'accessibility', 'Stretcher-size (ambulance) elevator requirements include a minimum car inside dimension of:', '68 by 51 inches', '84 by 54 inches', '60 by 48 inches', '72 by 60 inches', 'B', 'Stretcher-size elevators must have minimum inside dimensions of 84 inches deep by 54 inches wide (with center-opening doors) to accommodate a standard ambulance stretcher.', 'ASME A17.1 §2.27.1', 'medium'),
('CAT', 'accessibility', 'When retrofitting an existing elevator for ADA compliance under A17.3, the order of priority for modifications is:', 'Cosmetic upgrades first', 'Safety items first, then accessibility items in order of greatest impact', 'Only car interior finishes', 'Random selection by the owner', 'B', 'A17.3 provides a prioritized approach: safety upgrades first, then accessibility features that provide the greatest benefit (controls, signals, communication) given available resources.', 'ASME A17.3', 'medium'),
('CAT', 'accessibility', 'Destination dispatch elevator systems must provide accessible interfaces that include:', 'Only touchscreen entry', 'Tactile keypads, audible feedback, and visual confirmation so all users can select destinations', 'Voice-only activation', 'No accessibility requirements for new technology', 'B', 'Destination dispatch systems must provide accessible input (tactile keys, not just touchscreens) and output (audible confirmation, visual display) per ADA and A17.1.', 'ASME A17.1 §2.27', 'hard'),
('CAT', 'electrical', 'Emergency power operation for accessible elevators requires:', 'No requirements', 'Automatic transfer to standby power with the ability to return cars to the designated landing', 'Only battery-powered lighting', 'Manual generator start', 'B', 'Emergency power systems must automatically transfer and provide enough power to move the car to the nearest landing, open the doors, and maintain emergency communication and lighting.', 'ASME A17.1 §2.27.1', 'medium'),
('CAT', 'accessibility', 'The maximum gap between the elevator car sill and the hoistway landing sill is:', '3/4 inch', '1-1/4 inches', '1-1/2 inches', '2 inches', 'B', 'The gap must not exceed 1-1/4 inches to prevent wheelchair casters and cane tips from catching, which could cause falls during boarding and exiting.', 'ASME A17.1 §2.27.5', 'medium'),
('CAT', 'accessibility', 'Leveling accuracy for an accessible elevator must be within:', '1 inch', '1/2 inch', '1/4 inch', '1/8 inch', 'B', 'The car must level and maintain its position within 1/2 inch of the landing sill to ensure wheelchair users can safely cross the threshold without a tripping hazard.', 'ASME A17.1 §2.27.5', 'medium'),
('CAT', 'codes_standards', 'When accessibility and safety code requirements conflict, the resolution is:', 'Accessibility always prevails', 'Safety requirements take precedence, and an equivalent accessible solution must be found', 'The building owner decides', 'Neither code applies', 'B', 'When A17.1 safety requirements conflict with ADA accessibility requirements, safety takes precedence. However, an alternative means of providing equivalent accessibility must be sought.', 'ASME A17.1 §1.3', 'hard'),

-- ============================================================
-- SENIOR_TECH — 20 questions
-- ============================================================
('SENIOR_TECH', 'electrical', 'Regenerative drives on traction elevators:', 'Waste energy as heat', 'Return energy to the building electrical system when the car decelerates or runs with a light load going down', 'Only work on hydraulic elevators', 'Increase energy consumption', 'B', 'Regenerative drives convert the kinetic energy of deceleration (and overhauling loads) back to AC power fed to the building grid, reducing energy consumption by 20-40%.', 'ASME A17.1', 'medium'),
('SENIOR_TECH', 'electrical', 'Destination dispatch systems improve building efficiency by:', 'Assigning passengers to specific cars based on their destination floor, reducing stops and travel time', 'Increasing car speed', 'Eliminating the need for door operators', 'Reducing the number of elevators needed', 'A', 'Destination dispatch groups passengers going to the same or nearby floors into the same car, dramatically reducing the number of stops and improving round-trip time.', 'ASME A17.1', 'easy'),
('SENIOR_TECH', 'mechanical', 'Machine-room-less (MRL) elevators locate the machine:', 'On the roof', 'In the hoistway, typically at the top, with the controller in an adjacent wall-mounted cabinet', 'In the basement', 'In each car', 'B', 'MRL designs place the gearless traction machine at the top of the hoistway on the guide rail structure, with the controller in a locked cabinet on the top landing.', 'ASME A17.1 §2.8', 'easy'),
('SENIOR_TECH', 'hydraulic', 'Underground hydraulic elevator cylinders (jacks) require:', 'No special protection', 'A PVC liner (casing) and environmental monitoring for oil leaks to protect groundwater', 'Replacement every 5 years', 'Only surface-level inspection', 'B', 'Underground cylinders must be installed in a PVC casing or equipped with a leak detection system to prevent hydraulic oil from contaminating soil and groundwater.', 'ASME A17.1 §3.18.3', 'medium'),
('SENIOR_TECH', 'hydraulic', 'A hydraulic elevator power unit consists of:', 'Only a motor', 'A motor, pump, control valve, oil reservoir, and associated piping', 'A gearbox and sheave', 'A counterweight and governor', 'B', 'The hydraulic power unit includes the electric motor, positive displacement pump, directional control valve, oil reservoir (tank), pressure relief valve, and associated piping.', 'ASME A17.1 §3.25', 'easy'),
('SENIOR_TECH', 'hydraulic', 'Hydraulic elevator oil temperature must be monitored because:', 'It affects car lighting', 'Elevated temperature degrades oil viscosity, accelerates seal wear, and can cause erratic operation', 'Cold oil improves performance', 'Temperature has no effect', 'B', 'High oil temperature reduces viscosity, causing internal valve leakage, erratic leveling, and accelerated component wear. A heat exchanger or oil cooler may be needed in high-duty applications.', 'ASME A17.1 §3.25', 'medium'),
('SENIOR_TECH', 'electrical', 'IoT-based elevator monitoring systems provide:', 'No useful data', 'Real-time performance analytics, predictive maintenance alerts, and remote diagnostics', 'Only door cycle counts', 'Only energy usage data', 'B', 'Modern IoT monitoring captures door cycles, motor current, vibration, temperature, ride quality, and fault codes, enabling predictive maintenance and reducing callback rates.', 'ASME A17.1', 'easy'),
('SENIOR_TECH', 'mechanical', 'Rope replacement criteria include:', 'Only visible broken wires', 'Broken wires exceeding code limits, diameter reduction over 6%, evidence of core failure, or severe corrosion', 'Rope age alone', 'Color change only', 'B', 'A17.1 and A17.2 specify rope replacement when broken wires per strand per lay exceed limits, diameter reduces more than 6%, core deterioration is evident, or corrosion is severe.', 'ASME A17.2', 'medium'),
('SENIOR_TECH', 'codes_standards', 'ASME A17.6 covers:', 'Elevator installation', 'Elevator suspension, compensation, and governor systems', 'Dumbwaiters', 'Escalator steps', 'B', 'ASME A17.6 provides standards specifically for elevator suspension (ropes, belts), compensation, and governor systems, including materials, design, and inspection criteria.', 'ASME A17.6', 'medium'),
('SENIOR_TECH', 'safety', 'A senior technician performing modernization must ensure:', 'Only the new equipment meets current code', 'The entire elevator system meets A17.1 current edition for new work and A17.3 for existing components', 'No code review is needed', 'Only the car interior is updated', 'B', 'Modernization requires new components to meet current A17.1, while existing components must comply with A17.3. A full code review ensures the combined system is safe and compliant.', 'ASME A17.1 / A17.3', 'medium'),
('SENIOR_TECH', 'hydraulic', 'A holeless hydraulic elevator uses:', 'A cylinder bored into the ground', 'Telescoping above-ground cylinders or roped hydraulic arrangements to avoid underground cylinders', 'A traction machine', 'No hydraulic components', 'B', 'Holeless hydraulic designs use telescoping cylinders or roped (2:1) configurations entirely above ground, eliminating the need for a drilled hole and underground cylinder casing.', 'ASME A17.1 §3.18', 'easy'),
('SENIOR_TECH', 'electrical', 'When troubleshooting intermittent door faults, a senior technician should:', 'Replace the entire door operator', 'Analyze SCADA/controller fault logs, check door track alignment, clutch adjustment, and obstruction device sensitivity', 'Increase door close force', 'Disable the door reopening device', 'B', 'Systematic troubleshooting uses controller fault history to identify patterns, then inspects mechanical components (track, rollers, clutch, gibs) and electrical components (contacts, sensors, wiring).', 'ASME A17.1', 'medium'),
('SENIOR_TECH', 'mechanical', 'Guide shoe or roller guide maintenance is critical because worn guides cause:', 'Only noise', 'Excessive car vibration, poor ride quality, and potential safety issues with car positioning', 'No issues', 'Faster elevator speed', 'B', 'Worn guide shoes or roller guides allow excessive car sway and vibration, degrading ride quality, causing door problems, and potentially affecting safety equipment clearances.', 'ASME A17.1 §2.23', 'medium'),
('SENIOR_TECH', 'codes_standards', 'Elevator maintenance control programs (MCP) per A17.1 must include:', 'No documentation required', 'Written procedures, schedules, records of maintenance performed, and callback tracking', 'Only annual inspection records', 'Verbal agreements only', 'B', 'A17.1 §8.6 requires written maintenance control programs documenting procedures, intervals, completed work, test results, and performance tracking (callbacks and shutdowns).', 'ASME A17.1 §8.6', 'medium'),
('SENIOR_TECH', 'hydraulic', 'Unintended car movement (UCM) protection devices are required to:', 'Speed up leveling', 'Detect and stop unintended car movement away from the landing with the doors open', 'Only protect against overspeed', 'Improve ride comfort', 'B', 'UCM protection (per A17.1 §2.19.2) detects car movement away from the landing with doors open (due to valve failure, etc.) and applies a stopping device to prevent a fall hazard.', 'ASME A17.1 §2.19.2', 'hard'),
('SENIOR_TECH', 'electrical', 'Battery lowering on a hydraulic elevator allows:', 'Full speed operation during power failure', 'Controlled lowering of the car to the lowest landing using battery power to operate the control valve', 'The car to be raised', 'Indefinite operation', 'B', 'Battery lowering provides emergency egress by using battery power to activate the down valve, allowing the car to lower by gravity to the lowest landing and open the doors.', 'ASME A17.1 §3.27', 'medium'),
('SENIOR_TECH', 'safety', 'When supervising a crew performing hoistway work, the senior technician must ensure:', 'Workers stay inside the car only', 'All workers have proper fall protection, the car is on inspection, and no other cars in the hoistway can approach the work zone', 'Only one worker has PPE', 'Work is done as quickly as possible', 'B', 'Hoistway work safety requires fall protection per OSHA, car on inspection operation, multi-car hoistway coordination (barriers, LOTO of adjacent cars), and continuous communication.', 'OSHA 1910.147 / ASME A17.1', 'medium'),
('SENIOR_TECH', 'mechanical', 'Elevator ride quality is measured using:', 'Passenger surveys only', 'Accelerometers measuring vibration, jerk, and noise in three axes against ISO 18738 standards', 'Speed tests only', 'Door timing', 'B', 'Ride quality analysis uses triaxial accelerometers to measure acceleration, jerk (rate of change of acceleration), and vibration against ISO 18738 criteria for passenger comfort.', 'ISO 18738', 'hard'),
('SENIOR_TECH', 'electrical', 'Elevator cybersecurity concerns include:', 'No cybersecurity risks exist', 'Unauthorized access to networked controllers, SCADA systems, and building management interfaces', 'Only physical key security', 'Only passenger data privacy', 'B', 'Modern elevators connected to building networks and remote monitoring systems are vulnerable to cyber threats. Access controls, encryption, and network segmentation are essential security measures.', 'ASME A17.1', 'hard'),
('SENIOR_TECH', 'codes_standards', 'When multiple elevators share a hoistway, separation requirements include:', 'No separation needed', 'Screens or guards to prevent contact between cars and counterweights in adjacent hoistways', 'Only paint color differences', 'Separate machine rooms only', 'B', 'A17.1 requires screens/guards between cars and counterweights of adjacent elevators in the same hoistway to prevent contact and protect personnel working on top of one car while adjacent cars move.', 'ASME A17.1 §2.1.1', 'hard');
