-- 041_seed_liftpal_reference.sql
-- Seed the liftpal.lift_reference table with core elevator & lift reference data.

INSERT INTO liftpal.lift_reference (category, title, equipment_type, system_type, specification, content_json) VALUES

-- ── Elevator Codes & Standards (ASME A17.1) ────────────────────────
('codes_standards', 'ASME A17.1 — Rule 102.2: Machine Room Access', 'Generic', 'machine_room', 'Machine room requirements',
 '{"code":"ASME A17.1-2019 Rule 102.2","requirement":"Machine rooms shall be enclosed, ventilated, and accessible only to authorized personnel","key_points":["Permanent lighting required (min 200 lux)","Temperature range 55-95°F (13-35°C)","No piping unrelated to elevator in machine room","Floor drain or sump pump required","Door must be self-closing, self-locking"],"notes":"Local AHJ may impose additional requirements beyond A17.1"}'::jsonb),

('codes_standards', 'ASME A17.1 — Rule 204.1: Car Capacity and Loading', 'Generic', 'car', 'Car rated load requirements',
 '{"code":"ASME A17.1-2019 Rule 204.1","requirement":"Car capacity plate must be posted and load weighing device required for dispatching","rated_load_examples":[{"car_area_sqft":29.1,"max_load_lbs":2500},{"car_area_sqft":38.0,"max_load_lbs":3500},{"car_area_sqft":50.2,"max_load_lbs":4500}],"notes":"Capacity based on 1 person = 150 lbs per ASME; local codes may use different factors"}'::jsonb),

('codes_standards', 'ASME A17.1 — Rule 211: Safety Devices Testing', 'Generic', 'safety', 'Periodic safety test requirements',
 '{"code":"ASME A17.1-2019 Rule 211","category_1_test":{"interval":"every 1 year","description":"No-load safety test at rated speed or governor tripping speed","applies_to":"All traction elevators"},"category_5_test":{"interval":"every 5 years","description":"Full-load safety test at governor tripping speed","applies_to":"All traction elevators with rated speed > 150 fpm"},"category_3_test":{"interval":"every 3 years","description":"Full-load safety test for hydraulic elevators"},"notes":"All tests must be witnessed by an AHJ inspector or QEI"}'::jsonb),

('codes_standards', 'ASME A17.1 — Rule 300: Hoistway Requirements', 'Generic', 'hoistway', 'Hoistway construction and clearances',
 '{"code":"ASME A17.1-2019 Rule 300","key_requirements":["Hoistway enclosed entire height with fire-rated construction","Pit depth per code based on rated speed","Overhead clearance minimum per car speed","Hoistway venting required (min 3.5% of hoistway area)","Smoke detectors at top of hoistway and in machine room"],"pit_clearances":{"min_pit_depth_in":24,"refuge_space_required":true},"notes":"Running clearance between car and hoistway wall: 3/4 in max"}'::jsonb),

-- ── Wire Rope Specifications ───────────────────────────────────────
('wire_rope', 'Hoist Rope Selection — Traction Elevators', 'Traction', 'ropes', 'Standard hoist rope specifications',
 '{"common_diameters_in":["3/8","1/2","9/16","5/8"],"common_constructions":["8x19 Seale","8x25 filler wire","9x25 filler wire"],"core":"fiber core (FC) or independent wire rope core (IWRC)","minimum_ropes":3,"safety_factor":{"passenger":7.6,"freight":7.0},"d_D_ratio":"rope diameter to sheave diameter min 40:1","notes":"IWRC preferred for high-rise and heavy-duty; rope gauge all ropes monthly, replace when any rope loses 6% diameter"}'::jsonb),

('wire_rope', 'Governor Rope Specifications', 'Generic', 'governor', 'Governor rope requirements',
 '{"typical_diameter_in":"3/8","construction":"6x19 or 8x19","minimum_safety_factor":8,"material":"improved plow steel or better","attachment":"wedge socket or swaged fitting","inspection":"Check for broken wires, kinks, corrosion at each PM","replacement_criteria":"Replace if 3+ broken wires in one lay length or visible corrosion pitting","notes":"Governor rope tension must maintain positive traction on governor sheave"}'::jsonb),

('wire_rope', 'Compensation Rope/Chain Specs', 'Traction', 'ropes', 'Compensating rope or chain requirements',
 '{"purpose":"Compensate for weight of hoist ropes on car vs counterweight side","types":["Compensating ropes (looped at bottom)","Compensating chains (roller chain)","Compensating cables with tension sheave"],"required_when":"Travel exceeds approximately 100 ft","weight":"Must match hoist rope weight per foot of travel","notes":"Compensating sheave in pit must have guard; inspect chain for wear and elongation"}'::jsonb),

-- ── Door Operator Specifications ───────────────────────────────────
('door_operator', 'GAL MOVFR Door Operator Setup', 'Generic', 'doors', 'GAL MOVFR door operator adjustments',
 '{"type":"AC closed-loop door operator","opening_time_sec":{"center_opening":1.5,"side_opening":2.5},"closing_time_sec":{"center_opening":3.0,"side_opening":4.0},"nudging_force_lbs":2.5,"kinetic_energy_limit_ft_lbs":0.29,"key_adjustments":["Open speed potentiometer","Close speed potentiometer","Nudging speed","Hold-open time (1-30 sec adjustable)","Stall force / close force limit"],"notes":"ADA requires min 3 sec door hold time at lobby; kinetic energy must not exceed 7 ft-lbs at any point in closing"}'::jsonb),

('door_operator', 'Center-Opening vs Side-Opening Door Comparison', 'Generic', 'doors', 'Door opening type specifications',
 '{"center_opening":{"panels":2,"travel":"each panel = half opening width","speed":"faster — panels move simultaneously","common_widths_in":[42,48],"pros":"Faster open/close, balanced mechanical load"},"side_opening":{"panels":"1 or 2 (2-speed)","travel":"panel(s) slide to one side","speed":"slower — single direction travel","common_widths_in":[36,42,48],"pros":"Better for freight, stretcher-capable openings"},"two_speed_side_opening":{"panels":2,"description":"Fast panel moves 2x speed of slow panel","common_for":"Hospital/stretcher elevators"}}'::jsonb),

('door_operator', 'Door Detector & Reopening Devices', 'Generic', 'doors', 'Door protection device specs',
 '{"types":[{"name":"3D infrared curtain","technology":"Multi-beam infrared array across full door opening","coverage":"Full height and width","standard":"Most modern installations"},{"name":"Mechanical safety edge","technology":"Physical edge with switch on leading door edge","coverage":"Leading edge only","standard":"Legacy systems, code minimum"},{"name":"Proximity / presence sensor","technology":"Infrared or ultrasonic sensor detecting objects near door","coverage":"Door opening zone","standard":"Supplemental to primary device"}],"nudging_requirement":"After 20+ sec of door held open, doors may close at reduced speed and force with audible signal","notes":"A17.1 requires door reopening device on all automatic passenger elevators"}'::jsonb),

-- ── Controller Types & Troubleshooting ─────────────────────────────
('controllers', 'Relay Logic Controller Troubleshooting', 'Generic', 'controller', 'Legacy relay-based controller diagnostics',
 '{"type":"Relay logic (pre-microprocessor)","common_brands":["Otis","Westinghouse","Haughton","Dover"],"troubleshooting_steps":["Check relay coil voltage with meter","Verify contact condition (pitting, welding)","Trace circuit with print — follow the sequence","Check safety string continuity","Inspect timer relays for proper delay","Look for loose terminal connections"],"common_faults":["Welded relay contacts — car runs past floor","Open safety string — car will not run","Intermittent connection — random shutdowns","Timer relay drift — doors open/close erratically"],"notes":"Always have wiring prints on site; label any wires before disconnecting"}'::jsonb),

('controllers', 'Microprocessor Controller — Serial Communication Faults', 'Generic', 'controller', 'Modern controller communication troubleshooting',
 '{"type":"Microprocessor / serial","common_platforms":["Otis Elevonic 411","ThyssenKrupp TAC","Schindler Miconic","KONE EcoDisc"],"serial_protocols":["CAN bus","RS-485","Proprietary serial"],"troubleshooting":["Check controller fault log / event buffer","Verify serial cable termination resistors","Check for EMI sources near serial cables","Verify baud rate and address settings","Swap suspect boards to isolate","Check power supply voltages to PCBs"],"common_faults":["Communication timeout — car stops responding","Position error — re-learn floor heights","Encoder fault — check connections and alignment","IGBT fault — check drive module and gate signals"]}'::jsonb),

('controllers', 'Variable Frequency Drive (VFD) Basics', 'Generic', 'controller', 'VFD drive parameters for elevator motors',
 '{"purpose":"Speed control for AC elevator motors","key_parameters":["Base frequency (typically 60 Hz)","Acceleration ramp time (1.5-3.0 sec typical)","Deceleration ramp time (1.5-3.0 sec typical)","Current limit (110-150% of motor FLA)","Carrier frequency (4-8 kHz typical)","Encoder pulses per revolution"],"common_drives":["Yaskawa A1000 / L1000","KEB F5","ABB ACS880","Magnetek HPV900"],"troubleshooting":["Check DC bus voltage","Verify encoder feedback","Check motor thermistor circuit","Review drive fault history","Measure output phase balance"]}'::jsonb),

-- ── Hydraulic System Specifications ────────────────────────────────
('hydraulic', 'Holeless Hydraulic Jack Types', 'Hydraulic', 'jack', 'Holeless hydraulic jack configurations',
 '{"types":[{"name":"Twin-post holeless","description":"Two cylinders beside car, roped 2:1","max_travel_ft":30,"pros":"No bore hole needed, balanced lifting"},{"name":"Single-post holeless","description":"Single telescopic cylinder beside car, roped 2:1","max_travel_ft":25,"pros":"Smaller footprint"},{"name":"In-ground single-stage","description":"Single cylinder in bored hole below pit","max_travel_ft":25,"pros":"Simple, reliable, direct acting"},{"name":"In-ground multi-stage telescopic","description":"2 or 3 stage cylinder in shorter bore hole","max_travel_ft":60,"pros":"Higher travel with shorter bore hole"}],"notes":"Holeless designs eliminate bore hole environmental concerns and PVC liner requirements"}'::jsonb),

('hydraulic', 'Hydraulic Valve Settings — Standard Adjustments', 'Hydraulic', 'power_unit', 'Control valve specifications',
 '{"valves":[{"name":"Up speed (bypass)","function":"Controls oil flow to jack — sets up speed","adjustment":"Needle valve, CW to slow"},{"name":"Down speed","function":"Controls return oil flow — sets down speed","adjustment":"Needle valve, CW to slow"},{"name":"Relief valve","function":"Overpressure protection","setting":"150% of working pressure","notes":"Seal after setting — do not adjust in field without authorization"},{"name":"Lowering valve / check valve","function":"Prevents car from drifting down when idle","test":"Car should not drift more than 1/2 in. in 5 min with rated load"},{"name":"Manual lowering valve","function":"Emergency lowering","location":"In machine room, clearly labeled"}],"working_pressure_psi":"typically 250-500 PSI depending on load and roping","notes":"Always check pressure with calibrated gauge during setup"}'::jsonb),

('hydraulic', 'Hydraulic Oil Specifications', 'Hydraulic', 'power_unit', 'Elevator hydraulic fluid requirements',
 '{"oil_type":"Anti-wear hydraulic oil (AW)","viscosity_grades":["AW 32 (cold climates)","AW 46 (standard)","AW 68 (warm climates)"],"temperature_range":{"min_f":60,"max_f":150,"ideal_f":"85-110"},"oil_change_interval":"Every 3-5 years or when analysis indicates","sampling_interval_months":12,"key_tests":["Viscosity","Acid number (TAN)","Water content (< 0.1%)","Particle count"],"typical_volume_gal":"30-80 depending on jack size","notes":"Bio-based fluids available for environmentally sensitive installations; never mix oil types"}'::jsonb),

-- ── Safety Device Specifications ───────────────────────────────────
('safety_devices', 'Governor Types and Settings', 'Traction', 'governor', 'Overspeed governor specifications',
 '{"types":[{"name":"Flyball centrifugal","description":"Rotating weights on arms, most common","tripping_speed":"115% of rated speed"},{"name":"Disk type","description":"Spring-loaded disk with friction shoes","tripping_speed":"115% of rated speed"},{"name":"Electronic","description":"Encoder-based speed monitoring with solenoid release","tripping_speed":"Programmable, typically 115%"}],"overspeed_switch":"First stage — cuts power to motor at 110-115% rated speed","mechanical_trip":"Second stage — activates car safeties via governor rope","testing":"Annual no-load test; 5-year full-load test","notes":"Governor must be recalibrated if car speed is changed; tripping speed stamped on governor data plate"}'::jsonb),

('safety_devices', 'Car Safety Types — Traction Elevators', 'Traction', 'safeties', 'Car safety device classifications',
 '{"types":[{"name":"Type A — Instantaneous","description":"Wedge clamp, abrupt stop","max_speed_fpm":125,"application":"Low-speed elevators only"},{"name":"Type B — Progressive","description":"Spring or oil buffer mechanism, gradual deceleration","max_speed_fpm":"No limit","application":"All speeds, required above 125 fpm"},{"name":"Type C — Oil buffer safety","description":"Combined safety with integral oil buffer","max_speed_fpm":"No limit","application":"High-speed installations"}],"deceleration_limit_g":1.0,"testing_requirements":"Annual no-load, 5-year full-load","notes":"Safety jaw clearance typically 1/8 in. to rail — verify at each annual test"}'::jsonb),

('safety_devices', 'Buffer Types and Sizing', 'Generic', 'buffers', 'Pit buffer specifications',
 '{"types":[{"name":"Spring buffers","max_speed_fpm":200,"description":"Stored energy type, spring compression","stroke":"Sized for rated speed"},{"name":"Oil buffers","max_speed_fpm":"No limit","description":"Dissipative type, oil displacement through orifice","stroke":"Based on gravity stopping distance at 115% rated speed","oil_type":"Hydraulic oil, check level monthly"}],"required_locations":["Under car in pit","Under counterweight in pit"],"testing":"Spring buffers — compress annually; oil buffers — full plunger compression annually, return time < 90 sec","notes":"Buffers must have rated capacity for full car load at 115% of rated speed"}'::jsonb),

('safety_devices', 'Interlock & Door Lock Requirements', 'Generic', 'doors', 'Hoistway door interlock specifications',
 '{"function":"Prevent car from running unless all hoistway doors are closed and locked","interlock_types":[{"name":"Mechanical interlock","description":"Physical latch engages when door fully closed"},{"name":"Electrical contact","description":"Switch confirms locked position, part of safety circuit"}],"requirements":["Hoistway door must be locked when car is away from floor","Car cannot run unless all door contacts are made","Unlocking zone: 18 in. above and below floor level","Retiring cam unlocks hoistway door only when car is in zone"],"testing":"Monthly — attempt to open each hoistway door with car away from floor","notes":"Interlock switch contacts must be positively opened — no spring-return contacts in safety circuit"}'::jsonb),

-- ── Motor Specifications ───────────────────────────────────────────
('motor_specs', 'Geared Traction Machine — Standard Specs', 'Traction', 'machine', 'Geared traction motor specifications',
 '{"type":"Geared traction","motor":"AC or DC, coupled to worm gear reducer","speed_range_fpm":"25-450","gear_type":"Worm gear with bronze ring gear","gear_ratio":"Typically 12:1 to 40:1","lubrication":"Gear oil ISO VG 460, check level monthly","bearing_type":"Sleeve or roller bearings","common_manufacturers":["Imperial / Hollister-Whitney","ELPRO","Torin"],"maintenance":["Check gear oil level and condition monthly","Listen for gear noise changes","Check motor brush condition (DC) quarterly","Verify brake operation and adjustment","Monitor motor temperature"],"notes":"Geared machines limited to ~450 fpm; above that, gearless required"}'::jsonb),

('motor_specs', 'Gearless Traction Machine — High-Rise Specs', 'Traction', 'machine', 'Gearless traction motor specifications',
 '{"type":"Gearless traction","motor":"DC or permanent magnet AC (PMAC)","speed_range_fpm":"400-2500+","drive":"Direct drive — sheave mounted on motor shaft","bearing_type":"Roller bearings, sealed or grease-lubricated","common_manufacturers":["Otis","Kone","ThyssenKrupp","Schindler"],"dc_motor_maintenance":["Brush inspection and replacement","Commutator resurfacing","Armature testing (growler test)","Field winding insulation testing"],"pmac_motor_maintenance":["Bearing lubrication per schedule","Encoder alignment verification","Winding insulation resistance test"],"notes":"PMAC gearless machines dominate new installations — lower energy, no brushes, compact"}'::jsonb),

('motor_specs', 'Machine Room-Less (MRL) Motor Specifications', 'Traction', 'machine', 'MRL elevator machine specs',
 '{"type":"MRL (Machine Room-Less)","motor":"Permanent magnet AC (PMAC), flat profile","location":"Mounted in hoistway at top, on guide rail or structural bracket","speed_range_fpm":"100-500","drive":"Gearless direct drive","controller_location":"Cabinet on top floor landing wall or in hoistway","advantages":["No machine room required","Lower energy consumption","Reduced building cost"],"maintenance_considerations":["Work performed from top of car — fall protection required","Limited space for tools and parts","Hoistway ventilation critical for drive cooling","Rescue operation via hand-crank or battery lowering"],"notes":"MRL installations require ASME A17.1 Section 2.7 compliance; maintenance access provisions mandatory"}'::jsonb),

-- ── Load Calculations & Ratings ────────────────────────────────────
('load_ratings', 'Elevator Capacity Calculation — ASME A17.1', 'Generic', 'car', 'Load rating per platform area',
 '{"code":"ASME A17.1 Table 2.16.1.1","capacity_chart":[{"platform_area_sqft":21.7,"rated_load_lbs":2000,"persons":13},{"platform_area_sqft":29.1,"rated_load_lbs":2500,"persons":16},{"platform_area_sqft":38.0,"rated_load_lbs":3500,"persons":23},{"platform_area_sqft":44.8,"rated_load_lbs":4000,"persons":26},{"platform_area_sqft":50.2,"rated_load_lbs":4500,"persons":30}],"person_weight_lbs":150,"notes":"Freight elevators rated differently — Class A, B, C1, C2, C3 per A17.1 Section 2.16.2; stretcher-capable min 5000 lbs"}'::jsonb),

('load_ratings', 'Counterweight Calculation', 'Traction', 'ropes', 'Counterweight sizing formula',
 '{"formula":"CW = Car Weight + (40-50% of Rated Load)","standard_ratio":0.40,"example":{"car_weight_lbs":4000,"rated_load_lbs":3500,"counterweight_lbs":5400,"calculation":"4000 + (0.40 × 3500) = 5400 lbs"},"purpose":"Balance system so motor only lifts/lowers the load difference","balanced_load":"Car with 40-50% rated load weighs same as counterweight","notes":"Over-counterweighting wastes energy on empty runs; under-counterweighting wastes energy on full-load up runs"}'::jsonb),

('load_ratings', 'Traction Ratio and Rope Slip Limits', 'Traction', 'ropes', 'Traction drive limitations',
 '{"traction_formula":"T1/T2 ≤ e^(μθ)","variables":{"T1":"Tension on heavy side","T2":"Tension on light side","mu":"Coefficient of friction (rope in groove)","theta":"Wrap angle in radians"},"groove_types":[{"name":"U-groove","mu":0.09,"notes":"Lowest traction, longest rope life"},{"name":"V-groove","mu":0.17,"notes":"Highest traction, fastest rope wear"},{"name":"Undercut U-groove","mu":0.13,"notes":"Best balance of traction and rope life — most common"}],"notes":"If traction ratio exceeded, ropes slip on sheave — dangerous condition; regrooving sheave changes traction characteristics"}'::jsonb),

-- ── Inspection Intervals & Requirements ────────────────────────────
('inspections', 'QEI Annual Inspection Checklist', 'Generic', 'all_systems', 'Annual inspection requirements per ASME A17.2',
 '{"code":"ASME A17.2 Guide for Inspection","inspector_qualification":"QEI (Qualified Elevator Inspector) certified","key_inspection_items":["Machine room condition and equipment","Hoistway condition and clearances","Car enclosure, platform, and sling","Car and hoistway door operation and locks","Safety devices (governor, safeties, buffers)","Firefighters emergency operation (Phase I and II)","Emergency power operation","ADA compliance (signals, timing, controls)","Wire rope condition and gauging","Controller and wiring condition","Pit condition and equipment"],"testing_required":["Category 1 safety test","Firefighters operation test","Standby power test","Door force and timing test"],"notes":"Inspector issues test tags — post in car and machine room; deficiencies require correction within specified timeframe"}'::jsonb),

('inspections', 'Monthly Maintenance Inspection Items', 'Generic', 'all_systems', 'Routine monthly maintenance checks',
 '{"tasks":[{"area":"Machine room","checks":["Oil levels (gear, hydraulic)","Motor temperature","Brake pad condition and gap","Controller cleanliness","Unusual noises"]},{"area":"Hoistway","checks":["Door gibs and tracks","Interlock function","Guide shoe or roller condition","Traveling cable condition","Hoistway lighting"]},{"area":"Car top","checks":["Car top inspection station operation","Sheave condition and guarding","Governor rope tension","Hoist rope condition"]},{"area":"Pit","checks":["Pit cleanliness and dryness","Buffer condition and oil level","Compensation sheave guard","Pit stop switch and light","Governor tension sheave"]}],"notes":"Maintain written log of all monthly inspections; note and report any code violations immediately"}'::jsonb),

('inspections', 'Five-Year Full-Load Safety Test', 'Traction', 'safety', 'Category 5 full-load test procedure',
 '{"code":"ASME A17.1 Rule 8.6.4.20","interval_years":5,"test_procedure":["Car loaded to rated capacity","Car run down at governor tripping speed","Governor mechanically trips, activating car safeties","Car must stop within code-specified distance","Measure slide marks on guide rails","Inspect safeties, governor, ropes after test"],"acceptance_criteria":{"deceleration_max_g":1.0,"slide_marks":"Even marks on both rails, within rated distance","rope_damage":"No broken wires, no permanent deformation"},"post_test":["Reset governor","Inspect and reset car safeties","Check guide rail condition","Return car to service only after full inspection"],"notes":"Must be witnessed by AHJ inspector or QEI; schedule well in advance as building will lose elevator service"}'::jsonb),

('inspections', 'Firefighters Emergency Operation Test — Phase I & II', 'Generic', 'fire_service', 'Fire service operation testing',
 '{"code":"ASME A17.1 Rule 2.27","phase_1":{"trigger":"Smoke detector activation or key switch in lobby","action":"All elevators return to designated landing (usually lobby)","doors":"Open and remain open","override":"Fire department key switch only"},"phase_2":{"trigger":"Fire department key switch in car","action":"Firefighter has manual control of car","door_operation":"Doors open only while hold-open button pressed","features":["Car runs on constant pressure buttons","Door close on release","Independent service — ignores hall calls","Visual signal if car in fire-affected zone"]},"testing_frequency":"Monthly or per AHJ requirement","notes":"Phase I recall takes priority over all other calls; shunt trip on sprinkler-equipped hoistways must be tested"}'::jsonb);
