-- Auto-clear flagged_quality on items where two independent Opus 4.7 passes
-- both voted A (internally consistent, no concerns).
-- Source: c:/tmp/voltpal_opus_triage.json (triage run 2026-05-25)
-- 122 questions + 67 content sections = 189 total

begin;

-- ── Questions (122) ─────────────────────────────────────────────
with cleared(cert_level, module_number, question_text) as (values
  ($vp$APPRENTICE$vp$, 2, $vp$Code-making panel decisions, in the event of conflicts with manufacturers' instructions, give priority to which?$vp$),
  ($vp$APPRENTICE$vp$, 2, $vp$Working space in front of electrical equipment must be a minimum of how wide?$vp$),
  ($vp$APPRENTICE$vp$, 2, $vp$Why do many electricians use state-specific code books rather than the unmodified NEC?$vp$),
  ($vp$APPRENTICE$vp$, 2, $vp$Adoption of the latest NEC edition by a state or local jurisdiction:$vp$),
  ($vp$APPRENTICE$vp$, 2, $vp$Which of these is an example of a major change between NEC code cycles that you should research before working in a newly-adopted jurisdiction?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$PVC conduit must be supported as required by:$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$What's the temperature rating of XHHW-2 insulation in wet locations?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$What is the maximum conduit fill for a raceway containing more than two conductors?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$For one conductor in a single raceway, the maximum permitted fill is:$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$Each yoke or strap containing a device (switch, receptacle) counts as how many conductors for box fill?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$Equipment rated over 100 amps is generally permitted to use the 75°C ampacity column when the terminations are listed for 75°C. Equipment 100 amps or less defaults to which column?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$When more than three current-carrying conductors are installed in a single raceway, what must you apply to the conductors' ampacity?$vp$),
  ($vp$APPRENTICE$vp$, 3, $vp$Ambient temperature correction factors are applied when ambient temperature differs from:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$The minimum service rating for a one-family dwelling is generally:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$GFCI protection is required for 125-V, single-phase, 15- and 20-A receptacles installed in dwelling unit:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$How often should a GFCI device be tested by the user?$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$GFCI protection is required for which type of pool equipment per NEC 680?$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$Can a combination AFCI breaker provide protection for an existing receptacle outlet when replacing a non-AFCI receptacle?$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$In dwelling unit rooms (excluding bathrooms, kitchens, etc.), receptacles must be placed so that no point along the floor line of any wall space is more than:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$Receptacle outlets in kitchen countertop spaces must generally be installed so that no point along the wall counter is more than:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$On a multi-level dwelling, stairways with 6 or more risers require:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$Bathroom receptacles in dwelling units must be installed:$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$A receptacle installed for a refrigerator in a dwelling unit kitchen may be:$vp$),
  ($vp$APPRENTICE$vp$, 5, $vp$What is the most common cause of fatal electrical incidents during 'verification of de-energized state'?$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$Walk through: which receptacle in a typical dwelling does NOT require GFCI protection per NEC 210.8(A)?$vp$),
  ($vp$APPRENTICE$vp$, 4, $vp$In a hallway 12 ft long in a dwelling unit, are receptacles required?$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$Per NEC §230.79(C), the minimum service rating for a one-family dwelling is:$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$Per NEC §240.4(D), small conductors (10 AWG and smaller copper) have specific overcurrent protection limits. For 14 AWG copper, the max OCPD is:$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$Per NEC §240.4(D), the maximum OCPD for 12 AWG copper is:$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$Per NEC §240.4(D), the maximum OCPD for 10 AWG copper is:$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$The 'tap rule' in NEC §240.21 allows tap conductors smaller than the OCPD on the line side, under specific conditions. The shortest standard tap length is:$vp$),
  ($vp$JOURNEYMAN$vp$, 1, $vp$Per NEC §240.21(B)(2), the 25-ft tap rule allows tap conductors up to 25 ft long when:$vp$),
  ($vp$JOURNEYMAN$vp$, 2, $vp$A motor disconnect rated more than 100 hp must be:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Cable tray fill for power and lighting cables larger than 4/0 AWG per §392.22(A)(1) requires:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Single conductors 1/0 AWG and larger in cable tray require:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Cable tray supports must be installed:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Per §368.17, busway tap conductors of unlimited length are permitted where:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Article 376 metal wireways are permitted to contain conductors filling not more than what percent of the wireway's cross-section?$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$Per §376.22(B), splices and taps in metal wireways are permitted to fill not more than what percent of the wireway cross-section at any point?$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$If you have 4 × 500 kcmil THWN conductors in a single conduit and need to choose the trade size, you would:$vp$),
  ($vp$JOURNEYMAN$vp$, 3, $vp$The 'high leg' on a 240V delta system is approximately:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.52(A)(3), a concrete-encased electrode (Ufer) consists of:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.52(A)(5), ground rods must:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.53(A)(2), if a single ground rod has a resistance to ground greater than 25 ohms, the installer must:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.53(A)(3), where two ground rods are used as a grounding electrode, they must be installed:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.28(D), the main bonding jumper size is determined from:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Load-side bonding jumpers (e.g., bonding metal water pipe to the panel) are sized per:$vp$),
  ($vp$JOURNEYMAN$vp$, 4, $vp$Per §250.118, where liquidtight flexible metal conduit (LFMC) is used as EGC, length is limited to:$vp$),
  ($vp$JOURNEYMAN$vp$, 5, $vp$Per §450.21, an indoor dry transformer rated 112.5 kVA or less must be installed:$vp$),
  ($vp$JOURNEYMAN$vp$, 5, $vp$A transformer vault per §450.41 must:$vp$),
  ($vp$JOURNEYMAN$vp$, 5, $vp$Per §450.3(B) and §240.21(C), secondary tap conductors from a transformer:$vp$),
  ($vp$JOURNEYMAN$vp$, 6, $vp$What is the maximum acceptable resistance for a low-impedance ground path per industry practice?$vp$),
  ($vp$NFPA_70E$vp$, 2, $vp$If the voltage class of the equipment is over 1000 V, what generally happens to the limited approach boundary?$vp$),
  ($vp$NFPA_70E$vp$, 2, $vp$For fixed-circuit parts at 50 V to 300 V, is there a limited approach boundary distance?$vp$),
  ($vp$NFPA_70E$vp$, 2, $vp$Per NFPA 70E 130.5(H), equipment likely to require examination, adjustment, servicing, or maintenance while energized must be marked with:$vp$),
  ($vp$NFPA_70E$vp$, 2, $vp$A field arc flash label that lacks a working distance or incident energy and only shows a PPE category is:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$If incident energy at the working distance is 12 cal/cm², which PPE category is required?$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$PPE Category 2 typically includes:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$PPE Category 3 differs from Category 2 primarily by:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$Incident energy levels above what value typically require avoiding energized work entirely?$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$An IE of 1.5 cal/cm² at a working distance, with AFB at 36 inches, means:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$The 'two-second rule' in IEEE 1584 / NFPA 70E refers to:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$When can the table method (Table 130.7(C)(15)) NOT be used?$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$A 480 V panelboard with available fault current of 25 kA and clearing time of 2 cycles. Can you use the table method?$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$The required date on an arc flash label per NFPA 70E is:$vp$),
  ($vp$NFPA_70E$vp$, 3, $vp$An arc flash label that shows 'PPE Category 2' but no incident energy value is:$vp$),
  ($vp$MASTER$vp$, 1, $vp$An apartment building has 10 electric ranges, each rated 16 kW. Per Table 120.55 Note 1, the demand calculation is:$vp$),
  ($vp$MASTER$vp$, 1, $vp$Per Table 120.55 Note 6, when one counter-mounted cooking unit and two wall-mounted ovens are supplied from a single branch circuit and located in the same room, the calculated load is:$vp$),
  ($vp$MASTER$vp$, 1, $vp$An apartment building has 10 dwelling units, each with a 5500 VA electric clothes dryer. The calculated dryer demand load per §120.54 and Table 120.54 is:$vp$),
  ($vp$MASTER$vp$, 1, $vp$The optional dwelling calculation per §120.82 typically yields a LOWER demand than the standard method when:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.86(A), the engineer's calculation must ensure that downstream circuit breakers in a series combination:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.86 (referencing §110.22), series combination systems shall be field-marked with:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §700.32, emergency system(s) OCPDs shall be selectively coordinated with all supply-side OCPDs. 'Selective coordination' means:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §700.32, selective coordination of emergency system OCPDs shall be selected by:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §620.62, where multiple elevators are powered by a single feeder, the OCPDs in any path of the feeder shall:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §645.27, OCPDs for critical operations data systems are required to be:$vp$),
  ($vp$MASTER$vp$, 2, $vp$For a single-phase 120 V branch circuit drawing 16 A through 100 ft (one-way) of 12 AWG copper (resistance ≈ 1.93 Ω/1000 ft), the approximate voltage drop is:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.21(C), the 25-ft transformer secondary conductor tap rule requires (among other conditions):$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §110.9, equipment intended to interrupt current at fault levels shall have:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §110.10, the overcurrent protective devices, total impedance, component short-circuit current ratings, and equipment ratings shall be:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §250.122(F), when ungrounded conductors are installed in parallel in multiple raceways, the EGC:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §310.15(E)(3), the neutral conductor of a 4-wire 3-phase wye circuit supplying nonlinear loads shall be:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §310.15(E)(1), the neutral conductor of a 3-phase 4-wire wye circuit carrying ONLY balanced linear loads shall be:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.4(B), the next-higher standard OCPD rating may be used (above the conductor ampacity) when:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §110.16, the arc flash label shall include the date:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §215.4(A) Exception No. 1, where the assembly (including feeder OCPDs) is listed for operation at 100% of its rating, the conductor ampacity:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §330.10, Type MC cable is permitted for use in:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §340.10, Type UF cable is suitable for:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 Table 430.52(C)(1), a 3-phase squirrel cage motor (other than Design B energy-efficient) with time-delay (dual-element) fuse short-circuit/ground-fault protection is sized at maximum:$vp$),
  ($vp$MASTER$vp$, 2, $vp$When using fuses for selective coordination, the typical ratio between upstream and downstream fuse current ratings should be at least:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §110.26(E), within the dedicated electrical space, sprinkler protection is:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.21(B)(1), a 10-ft feeder tap is permitted when the tap conductors have ampacity:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.21(B)(2), a 25-ft feeder tap requires the tap conductor ampacity be at least:$vp$),
  ($vp$MASTER$vp$, 2, $vp$Per NEC 2026 §240.21(B)(5), an outside feeder tap of unlimited length is permitted provided:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §500.7(F), the nonincendive circuit protection technique is permitted in:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §517.20(A), wet procedure locations shall be provided with special protection against electric shock by either an isolated power system OR:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §517.30 / §517.41, a Type 1 Essential Electrical System (Hospital) consists of:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §518.4, wiring methods permitted in assembly occupancies generally include all wiring methods of Chapter 3 EXCEPT for limited-energy applications, where:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §547.28 and §547.10, an equipotential plane is required in livestock confinement areas to:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §680.22(A)(1), where a permanently installed pool is installed, at least one 125 V 15- or 20-ampere receptacle on a general-purpose branch circuit shall be located:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §680.22(A)(2), receptacles providing power for water-pump motors or other loads directly related to the circulation/sanitation system shall be located at least how far from the inside walls of the pool, with GFCI protection?$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §680.22(C), switching devices shall be located at least what distance horizontally from the inside walls of a pool, unless separated by a permanent barrier or listed for closer installation?$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §695.4(A), an individual power source for an electric motor-driven fire pump must be capable of carrying indefinitely the sum of:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §695.4(B)(3), the OCPDs supplying a fire pump shall be:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §701.12, legally required standby systems shall provide power within not more than:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §501.140, flexible cord used in Class I, Division 1 or 2 locations shall be:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §505.2, the Zone system (Class I Zones 0/1/2) is an alternative classification to Class I Divisions 1/2 of Article 500. The Zone system is based on:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §500.8(D), the maximum surface temperature for equipment installed in a Class II, Division 1 location for combustible dusts shall not exceed:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §501.30(A), in Class I locations the use of double locknuts (one inside and one outside the enclosure) for grounding/bonding metal raceways is:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §250.102(C) referenced through §501.30, the bonding jumper at hazardous-location boundary terminations shall be sized per:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §690.12, the 'array boundary' for rapid shutdown purposes is defined as:$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §700.24 / §700.25 references, emergency luminaires equipped with control inputs (e.g., dimming or sensing inputs):$vp$),
  ($vp$MASTER$vp$, 3, $vp$Per NEC 2026 §695.8(D), the voltage at the contactor load terminals to which the fire pump motor is connected shall not drop more than what percentage below the motor's voltage rating when operating at 115% of FLA?$vp$),
  ($vp$MASTER$vp$, 4, $vp$What is the correct distinction between OSHA electrical regulations (29 CFR 1910 Subpart S and 29 CFR 1926 Subpart K) and the NEC?$vp$),
  ($vp$MASTER$vp$, 4, $vp$In a standard AIA-format owner-contractor agreement (such as AIA A101), the contractor's primary obligation regarding code compliance is to:$vp$),
  ($vp$MASTER$vp$, 4, $vp$When preparing a bid for an electrical installation, the contractor's responsibility regarding code compliance is to:$vp$),
  ($vp$MASTER$vp$, 4, $vp$Workers' compensation insurance, required by most state laws for electrical contractors with employees, provides:$vp$),
  ($vp$MASTER$vp$, 4, $vp$Commercial general liability (CGL) insurance for an electrical contractor primarily covers:$vp$),
  ($vp$MASTER$vp$, 4, $vp$A mechanic's lien (or construction lien) is a statutory right that allows:$vp$),
  ($vp$MASTER$vp$, 4, $vp$The primary purpose of lockout/tagout procedures (OSHA 29 CFR 1910.147 and NFPA 70E §120) is to:$vp$),
  ($vp$MASTER$vp$, 4, $vp$Under NFPA 70E, there are two recognized methods for determining arc-rated PPE for a specific task:$vp$),
  ($vp$MASTER$vp$, 4, $vp$On a commercial project, the design engineer's stamped electrical plans specify a method that, while permitted by code, results in conductors that exceed §110.14(C) terminal temperature limitations at the panelboard. The electrical contractor notices this during installation. The appropriate action is:$vp$)
)
update voltpal.training_questions q
set flagged_quality = false
from cleared c
where q.cert_level = c.cert_level
  and q.module_id = (select id from voltpal.training_modules where cert_level = c.cert_level and module_number = c.module_number)
  and q.question_text = c.question_text;

-- ── Content sections (67) ───────────────────────────────────
with cleared(cert_level, module_number, section_number) as (values
  ($vp$APPRENTICE$vp$, 3, 3),
  ($vp$APPRENTICE$vp$, 3, 5),
  ($vp$APPRENTICE$vp$, 5, 3),
  ($vp$APPRENTICE$vp$, 5, 4),
  ($vp$APPRENTICE$vp$, 5, 5),
  ($vp$JOURNEYMAN$vp$, 1, 4),
  ($vp$JOURNEYMAN$vp$, 1, 5),
  ($vp$JOURNEYMAN$vp$, 2, 3),
  ($vp$JOURNEYMAN$vp$, 2, 4),
  ($vp$JOURNEYMAN$vp$, 2, 5),
  ($vp$JOURNEYMAN$vp$, 3, 2),
  ($vp$JOURNEYMAN$vp$, 6, 2),
  ($vp$JOURNEYMAN$vp$, 6, 4),
  ($vp$JOURNEYMAN$vp$, 6, 5),
  ($vp$NFPA_70E$vp$, 1, 31),
  ($vp$NFPA_70E$vp$, 1, 34),
  ($vp$NFPA_70E$vp$, 1, 35),
  ($vp$NFPA_70E$vp$, 1, 36),
  ($vp$NFPA_70E$vp$, 2, 7),
  ($vp$NFPA_70E$vp$, 2, 8),
  ($vp$NFPA_70E$vp$, 2, 11),
  ($vp$NFPA_70E$vp$, 3, 13),
  ($vp$NFPA_70E$vp$, 3, 16),
  ($vp$NFPA_70E$vp$, 3, 18),
  ($vp$NFPA_70E$vp$, 4, 10),
  ($vp$NFPA_70E$vp$, 4, 11),
  ($vp$NFPA_70E$vp$, 4, 25),
  ($vp$NFPA_70E$vp$, 4, 26),
  ($vp$NFPA_70E$vp$, 4, 28),
  ($vp$NFPA_70E$vp$, 4, 29),
  ($vp$NFPA_70E$vp$, 4, 30),
  ($vp$MASTER$vp$, 1, 7),
  ($vp$MASTER$vp$, 1, 8),
  ($vp$MASTER$vp$, 1, 18),
  ($vp$MASTER$vp$, 1, 19),
  ($vp$MASTER$vp$, 1, 23),
  ($vp$MASTER$vp$, 1, 25),
  ($vp$MASTER$vp$, 1, 29),
  ($vp$MASTER$vp$, 2, 13),
  ($vp$MASTER$vp$, 2, 14),
  ($vp$MASTER$vp$, 2, 19),
  ($vp$MASTER$vp$, 2, 20),
  ($vp$MASTER$vp$, 2, 25),
  ($vp$MASTER$vp$, 2, 29),
  ($vp$MASTER$vp$, 2, 31),
  ($vp$MASTER$vp$, 2, 35),
  ($vp$MASTER$vp$, 3, 2),
  ($vp$MASTER$vp$, 3, 4),
  ($vp$MASTER$vp$, 3, 7),
  ($vp$MASTER$vp$, 3, 8),
  ($vp$MASTER$vp$, 3, 22),
  ($vp$MASTER$vp$, 3, 25),
  ($vp$MASTER$vp$, 3, 26),
  ($vp$MASTER$vp$, 3, 27),
  ($vp$MASTER$vp$, 3, 29),
  ($vp$MASTER$vp$, 4, 7),
  ($vp$MASTER$vp$, 4, 10),
  ($vp$MASTER$vp$, 4, 13),
  ($vp$MASTER$vp$, 4, 14),
  ($vp$MASTER$vp$, 4, 17),
  ($vp$MASTER$vp$, 4, 19),
  ($vp$MASTER$vp$, 4, 20),
  ($vp$MASTER$vp$, 4, 23),
  ($vp$MASTER$vp$, 4, 25),
  ($vp$MASTER$vp$, 4, 26),
  ($vp$MASTER$vp$, 4, 29),
  ($vp$MASTER$vp$, 4, 30)
)
update voltpal.training_module_content mc
set requires_sme_check = false
from cleared c
where mc.module_id = (select id from voltpal.training_modules where cert_level = c.cert_level and module_number = c.module_number)
  and mc.section_number = c.section_number;

-- ── Verification ───────────────────────────────────────────────────────
do $$
declare v_q_flagged int; v_c_flagged int; v_q_total int;
begin
  select count(*) into v_q_total from voltpal.training_questions;
  select count(*) into v_q_flagged from voltpal.training_questions where flagged_quality = true;
  select count(*) into v_c_flagged from voltpal.training_module_content where requires_sme_check = true;
  raise notice 'Post-clear: questions total=%, questions still flagged=% (expect 177), content still flagged=% (expect 113)',
    v_q_total, v_q_flagged, v_c_flagged;
  if v_q_flagged <> 177 then raise exception 'question flagged count mismatch: % vs 177', v_q_flagged; end if;
  if v_c_flagged <> 113 then raise exception 'content flagged count mismatch: % vs 113', v_c_flagged; end if;
end $$;

commit;
